Add Varied analysis to the reverse mode
vgvassilev/clad pull request #1084
Opened 2024-09-06 13:17 UTC by ovdiiuv

This PR adds Varied analysis support in the reverse mode, fixes wrong jacobian results and updates tests.

2024-09-07 17:43 UTC, vgvassilev reviewed
Here is a partial review. Please address the clang-tidy complaints as most of them are good. I'd also rely on @PetroZarytskyi here for a review.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +  auto* entry = &m_CFG->getEntry();
We should expand the type here.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +  for (const auto& i : m_VariedDecls)
We should expand the type here.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +  for (const auto succ : block.succs()) {
We should expand the type here.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    if (!succ)
When `succ` can be null? Would that even enter the loop?

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +      succData = new VarsData(*m_BlockData[block.getBlockID()]);
I am a little uncomfortable in allocating `VarsData` in random places in the code. Could this be done in a single place, or maybe behind some helper function?

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +      for (const auto& i : *m_BlockData[block.getBlockID()])
We should expand the type here.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +  for (const auto& i : *m_BlockData[block.getBlockID()])
We should expand the type here.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    mergeData->insert(i);
We should expand the type here.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +bool VariedAnalyzer::VisitCallExpr(CallExpr* CE) { return true; }
Can't we omit these, as there is no implementation in there and that's the default behavior.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +  for (auto* D : DS->decls()) {
We should expand the type here.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +        auto& curBranch = getCurBlockVarsData();
We should expand the type here.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +        if (curBranch.find(VD) == curBranch.end() && m_Varied)
```suggestion
        if (m_Varied && curBranch.find(VD) == curBranch.end())
```

Should be faster.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    auto& curBranch = getCurBlockVarsData();
We should expand the type here.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    if (curBranch.find(VD) == curBranch.end() && m_Varied && m_Marking)
```suggestion
    if (m_Varied && m_Marking && curBranch.find(VD) == curBranch.end())
```

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +}
That's a good suggestion.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +#include "clang/AST/RecursiveASTVisitor.h"
That's a good suggestion too. We just need to put as an include protector `LIB_DIFFERENTIATOR_ACTIVITYANALYZER_H`.

2024-09-07 17:43 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +#include <iostream>
Good suggestion, too.

2024-09-09 10:48 UTC, PetroZarytskyi requested changes
Thank you for your work. I didn't mention pullbacks and call exprs because we already made huge progress there yesterday. Overall, the PR looks awesome. Its simplicity makes me feel that TBR was overcomplicated. I think we made the right decision to start with a simplified implementation.

2024-09-09 10:48 UTC, PetroZarytskyi commented on lib/Differentiator/ActivityAnalyzer.h
> +    // VarData* getExprVarData(const clang::Expr* E, bool addNonConstIdx = false);
Perhaps this should be removed.

2024-09-09 10:48 UTC, PetroZarytskyi commented on lib/Differentiator/ActivityAnalyzer.cpp
> +        m_shouldPushSucc = false;
Does ``m_shouldPushSucc`` have to be a field in the activity analyzer? I believe the variable is only used in this function and it's always ``true`` before this line. Can we declare it, let's say, on line 59?

2024-09-09 10:48 UTC, PetroZarytskyi commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    m_VariedDecls.insert(i);
I remember we discussed using ``m_BlockData[0]`` (the final CFG block) to get the results and get rid of ``m_VariedDecls``. Is the idea still relevant?

2024-09-09 10:48 UTC, PetroZarytskyi commented on lib/Differentiator/ActivityAnalyzer.h
> +    struct VarsData {
I believe you took this struct from TBR. I mostly added it as a wrapper of ``std::set<const clang::VarDecl*>`` able to keep track of the previous block, i.e. ``m_Prev``. Your analysis doesn't seem to utilize ``m_Prev``. If so, you could replace VarsData with plain ``std::set<const clang::VarDecl*>``. 
For simplicity, you could do
 ```using VarsData = std::set<const clang::VarDecl*>;```

2024-09-09 10:48 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (VDDerived && m_DiffReq.shouldHaveAdjoint(const_cast<VarDecl*>(VD)))
We might have fixed this during one of hour calls but I'll leave a reminder just in case. You can make the ``shouldHaveAdjoint`` take a const VarDecl*. This way, we can get rid of the const casts.

2024-09-09 10:48 UTC, PetroZarytskyi commented on test/Analyses/ActivityReverse.cpp
> +}
The tests look great. Perhaps we should add tests for function calls / pullbacks once they are supported.

2024-09-09 11:02 UTC, ovdiiuv commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    m_VariedDecls.insert(i);
I believe that `m_BlockData[0]` isn't always the last one. There has to be a workaround but I'd keep it the way it is for now

2024-09-09 12:39 UTC, ovdiiuv commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    if (!succ)
If some block isn't executed, it isn't included in the CFG but might be among the successors.
For example something like 
```
double f(double x){
  double g = 0;
  if(0){
    g = x;
  }
  return g;
}
```
requires that.

2024-09-09 14:42 UTC, PetroZarytskyi commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    m_shouldPushSucc = true;
This is valid, the statement is useless now.

2024-09-09 14:47 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (!m_DiffReq.shouldHaveAdjoint(const_cast<VarDecl*>(VD)))
I believe the const cast is unnecessary now.

2024-09-09 14:49 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +
This can be removed.

2024-09-09 14:49 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +
And this.

2024-09-09 20:29 UTC, ovdiiuv commented on lib/Differentiator/ActivityAnalyzer.cpp
> +      succData = new VarsData(*m_BlockData[block.getBlockID()]);
Can you please elaborate? I don't think I understand what you mean and why should we do so.

2024-09-09 20:45 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    if (!succ)
Then we should be able to write a test case for this.

2024-09-09 20:49 UTC, vgvassilev reviewed
Please check the resolved conversations as some are not really resolved by adding the requested change.

2024-09-09 20:49 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    m_VariedDecls.insert(i);
We should capture this in a fixme note in the codebase.

2024-09-10 13:48 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +void VariedAnalyzer::merge(VarsData* targetData, VarsData* mergeData) {
This is a good suggestion.

2024-09-10 13:48 UTC, vgvassilev commented on test/Jacobian/FunctionCalls.C
>  }
Why did we need to modify these tests when AA is off by default?

2024-09-10 13:48 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +  m_BlockPassCounter.resize(m_CFG->size(), 0);
I do not see where this member is being used. Maybe drop it?

2024-09-10 13:48 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +class VariedAnalyzer : public clang::RecursiveASTVisitor<VariedAnalyzer> {
We should write doxygen-style documentation to this class and it's api.

2024-09-10 13:48 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +using namespace clang;
We must not include `using namespace` in header files. I wonder why clang-tidy does not complain about it.

2024-09-10 13:48 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +  VarsData& getCurBlockVarsData() { return *m_BlockData[m_CurBlockID]; }
```suggestion
  VarsData& getCurBlockVarsData() { return *m_BlockData[m_CurBlockID]; }
  const VarsData& getCurBlockVarsData() const { return const_cast<VariedAnalyzer*>(this)->getCurBlockVarsData()}
```

2024-09-10 13:48 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +  void VisitCFGBlock(const clang::CFGBlock& block);
We should probably rename this as the other Visit methods are "derived" from the RecursiveASTVisitor.

2024-09-10 13:48 UTC, vgvassilev commented on lib/Differentiator/CMakeLists.txt
> +  ActivityAnalyzer.cpp
We use alphabetical order.

2024-09-10 13:48 UTC, vgvassilev commented on lib/Differentiator/DiffPlanner.cpp
> +      if (!DVI.empty()) {
Inverting the condition would help readability.

2024-09-10 14:11 UTC, ovdiiuv commented on test/Jacobian/FunctionCalls.C
>  }
Those Jacobin tests weren't correct and the changes I've made somehow fixed the problem with jacobians

2024-09-10 14:23 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +        VarsData& curBranch = getCurBlockVarsData();
```suggestion
       const VarsData& curBranch = getCurBlockVarsData();
```

2024-09-10 14:23 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    VarsData& curBranch = getCurBlockVarsData();
```suggestion
   const VarsData& curBranch = getCurBlockVarsData();
```

We should extract this into a utility function which does `getCurBlockVarsData` and `find`.

2024-09-10 14:23 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +bool VariedAnalyzer::isVaried(const VarDecl* VD) {
```suggestion
bool VariedAnalyzer::isVaried(const VarDecl* VD) const {
```

2024-09-11 12:38 UTC, ovdiiuv commented on lib/Differentiator/ActivityAnalyzer.h
> +    return std::unique_ptr<VarsData>(new VarsData(std::move(toAssign)));
make_unique doesn't work on C++11, so I think we could keep it as it is

2024-09-11 17:35 UTC, vgvassilev reviewed
We should add tests for the missing codecov reports.

2024-09-11 17:35 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    auto IDIter = std::prev(m_CFGQueue.end());
We need to specify the type here.

2024-09-11 17:35 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +      TraverseStmt(const_cast<clang::Stmt*>(S));
We should drop the `const` qualifier from the `block` parameter.

2024-09-11 17:35 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    if (!succ)
Still no test going here.

2024-09-11 17:35 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    }
```suggestion
    if (!isa<VarDecl>(D))
       return continue;
    if (Expr* init = cast<VarDecl>(D)->getInit()) {
        m_Varied = false;
        TraverseStmt(init);
        m_Marking = true;
        if (m_Varied)
          copyVarToCurBlock(VD);
        m_Marking = false;
    }
```

2024-09-11 17:35 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    if (m_Varied && m_Marking)
I am not generally happy with the state that we collect up and down the visitation process. Is there a way to avoid this somehow?

2024-09-11 17:35 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +/// @brief Class that implemets Varied part of the Activity analysis.
```suggestion
/// Class that implemets Varied part of the Activity analysis.
```

No need of brief - it is deprecated and default now.

2024-09-11 17:35 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +  /// @return Unique pointer to a new object of type Varsdata.
```suggestion
  /// A helper method to allocate VarsData
  /// \param toAssign - Parameter to initialize new VarsData with.
  /// \return Unique pointer to a new object of type Varsdata.
```

This is the style we use. Can you update the rest?

2024-09-11 17:35 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +  static void merge(VarsData* targetData, VarsData* mergeData);
```suggestion
```

The diagnostic was to make something file static, not a class static.

2024-09-11 17:35 UTC, vgvassilev commented on lib/Differentiator/DiffPlanner.cpp
> +      if (!DVI.empty()) {
I meant inverting the condition of `!DVI.empty()`. We should bring back the `HasNoAnalysisRun` change.

2024-09-11 17:35 UTC, vgvassilev commented on test/Jacobian/FunctionCalls.C
>  }
We should move that change in a separate PR.

2024-09-11 18:44 UTC, ovdiiuv commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    auto IDIter = std::prev(m_CFGQueue.end());
okay, I was frightened by its type tho.

2024-09-14 09:14 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +static inline void mergeVarsData(VarsData* targetData, VarsData* mergeData) {
This function should go in the cpp file.

2024-09-15 15:57 UTC, vgvassilev commented
Can you rebase this PR?

2024-09-15 19:44 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +  }
```suggestion
  VarDecl *VD = dyn_cast<VarDecl>(DRE->getDecl());
  if (!VD)
    return true;
  if (isVaried(VD))
    m_Varied = true;

  if (m_Varied && m_Marking)
    copyVarToCurBlock(VD);
```

2024-09-15 19:44 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +  VarsData& getCurBlockVarsData() { return *m_BlockData[m_CurBlockID]; }
We need documentation here, too.

2024-09-15 19:44 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +  /// \param FD Function to run the analysis on.
```suggestion
  /// \param[in] FD Function to run the analysis on.
```

2024-09-15 19:44 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +  /// \param toAssign - Parameter to initialize new VarsData with.
```suggestion
  /// \param toAssign[in] - Parameter to initialize new VarsData with.
```

2024-09-23 16:22 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    if (!isa<VarDecl>(D))
A test here could be `class C{} c;` that produces a DeclStmt whose Stmt is not a VarDecl.

2024-09-30 05:04 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +      if (m_Varied || 1) {
This probably should change to what it was before.

2024-10-05 17:17 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +using VarsData = std::set<const clang::VarDecl*>;
This can go in the class definition.

2024-10-05 17:17 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +/// statements in the reverse mode, improving generated codes efficiency.
The documentation should go to the class definition.

2024-10-05 17:17 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +bool VariedAnalyzer::VisitInitListExpr(InitListExpr* ILE) { return true; }
ping.

2024-10-05 17:17 UTC, vgvassilev commented on test/Jacobian/FunctionCalls.C
> +
Redundant new lines.

2024-10-05 17:17 UTC, vgvassilev commented on test/Gradient/FunctionCalls.C
> -// CHECK: void do_nothing_pullback(double *u, double *v, double *w, double _d_y, double *_d_u, double *_d_v, double *_d_w) {
Why did we need this change?

2024-10-05 17:17 UTC, vgvassilev commented on test/Gradient/FunctionCalls.C
> -// CHECK: void do_nothing_pullback(double *u, double *v, double *w, double _d_y, double *_d_u, double *_d_v, double *_d_w);
Why this change was needed?

2024-10-05 18:43 UTC, ovdiiuv commented on test/Gradient/FunctionCalls.C
> -// CHECK: void do_nothing_pullback(double *u, double *v, double *w, double _d_y, double *_d_u, double *_d_v, double *_d_w);
We used to remove non varied parameters from the adjoint, but it'd crash cms example, so I removed it for now.

2024-10-06 20:16 UTC, PetroZarytskyi requested changes

2024-10-06 20:16 UTC, PetroZarytskyi commented on lib/Differentiator/ActivityAnalyzer.cpp
> +  }
Why do we need to set these modes to ``true`` here? And even if so, shouldn't we also set ``m_Marking`` to ``false`` afterward?

2024-10-06 20:16 UTC, PetroZarytskyi commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    m_Varied = true;
Doesn't this portion of the code repeat what comes next? Perhaps we should keep one of these.

2024-10-06 20:16 UTC, PetroZarytskyi commented on lib/Differentiator/ActivityAnalyzer.cpp
> +}
It looks like this function will make ``targetData`` and ``mergeData`` identical. Do we need them both to be modified? Even if we do, we can probably do ``*mergedata = *targetdata`` instead of the last two lines.

2024-10-06 20:56 UTC, ovdiiuv commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    m_Varied = true;
yes

2024-10-06 20:58 UTC, ovdiiuv commented on lib/Differentiator/ActivityAnalyzer.cpp
> +      if (!isa<BinaryOperator>(subexpr))
See #1106

2024-10-07 17:26 UTC, ovdiiuv commented on lib/Differentiator/ActivityAnalyzer.cpp
> +  }
1. To support something like `double* ptr = &var`. Pointers are set varied by default, but if `var` isn't varied clad would crash when generating an adjoint for `ptr`.
2. Probably yes.

2024-10-09 21:13 UTC, ovdiiuv commented on lib/Differentiator/ActivityAnalyzer.h
> +using VarsData = std::set<const clang::VarDecl*>;
It'd throw an error because merge is file-static

2024-10-10 05:05 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +bool VariedAnalyzer::VisitInitListExpr(InitListExpr* ILE) { return true; }
If this does not do anything you can even drop the VisitInitListExpr altogether.

2024-10-10 05:07 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +using VarsData = std::set<const clang::VarDecl*>;
In that case you will use it as `VariedAnalyzer::VarsData` or just make it take `std::set<const clang::VarDecl*>`

2024-10-10 05:08 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +  /// statements in the reverse mode, improving generated codes efficiency.
This does not seem to be at the right place either. It needs to go before the class definition.

2024-10-10 05:08 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.h
> +  std::set<const clang::VarDecl*>& m_VariedDecls;
```suggestion
  VarsData& m_VariedDecls;
```

2024-10-12 22:45 UTC, PetroZarytskyi approved these changes

2024-10-12 22:46 UTC, PetroZarytskyi commented
LGTM

2024-10-13 06:02 UTC, vgvassilev reviewed
We are almost there. Please add tests on the missing branches.

2024-10-13 06:02 UTC, vgvassilev commented on test/Gradient/FunctionCalls.C
> -// CHECK: void do_nothing_pullback(double *u, double *v, double *w, double _d_y, double *_d_u, double *_d_v, double *_d_w);
I am not sure I follow, Does not that change the pullback signatures randomly? @PetroZarytskyi.

2024-10-14 17:28 UTC, vgvassilev commented on lib/Differentiator/ActivityAnalyzer.cpp
> +    if (Expr* init = cast<VarDecl>(D)->getInit()) {
Here we will crash if `D` is not a `VarDecl`.

2024-10-15 17:30 UTC, vgvassilev approved these changes
LGTM!

2024-10-15 18:37 UTC, merged