Add support of CUDA builtins
vgvassilev/clad pull request #1092
Opened 2024-09-12 10:13 UTC by kchristin22

2024-09-12 15:07 UTC, parth-07 reviewed
Looks great!

2024-09-12 15:07 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +  for(int i = 0; i < 10; i++) {
Why are we not using lit/FileCheck for verifying derivatives?

2024-09-12 15:58 UTC, kchristin22 commented on test/CUDA/GradientKernels.cu
> +  for(int i = 0; i < 10; i++) {
I didn't want to print every value when I ran the test locally. I will change this to a smaller array and print the result at once

2024-09-13 06:43 UTC, parth-07 requested changes

2024-09-13 06:43 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +  add.execute_kernel(dim3(1), dim3(5, 1, 1), dummy_out, dummy_in, d_out, d_in);
Shouldn't `dummy_out` and `dummy_in` pointers be of size 5 ints? Currently, they are of size 1 int.

2024-09-13 06:43 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +  cudaMalloc(&d_in, 5 * sizeof(int));
Please initialize `d_in` values to `0` to avoid any undefined behavior.

2024-09-14 10:35 UTC, parth-07 approved these changes
Looks good to me.

2024-09-14 10:36 UTC, parth-07 reviewed
Can you please squash all the commits into one?

2024-09-14 10:59 UTC, kchristin22 commented
> Can you please squash all the commits into one?

This will be done automatically when merging this PR

2024-09-14 11:11 UTC, parth-07 commented
> This will be done automatically when merging this PR

The primary goal of squashing commits manually in this case is to properly write and structure the commit message.

2024-09-14 13:35 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +// CHECK:    void add_kernel_2_grad(int *out, int *in, int *_d_out, int *_d_in) {
Can you investigate why we don't have `__attribute__((device))` here?

Clang is printing `__attribute__((device))` if we replace `clang::CUDADeviceAttr::CreateImplicit` call in `m_Derivative->addAttr(clang::CUDADeviceAttr::CreateImplicit(m_Context));` with `m_Derivative->addAttr(clang::CUDADeviceAttr::Create(m_Context));`

2024-09-14 13:52 UTC, kchristin22 commented on test/CUDA/GradientKernels.cu
> +// CHECK:    void add_kernel_2_grad(int *out, int *in, int *_d_out, int *_d_in) {
Yes, I've seen that. The attribute is "hidden" only for the compiler to see when using implicit. I can change that to the explicit creation (`Create` instead of `CreateImplicit`) for clarity purposes if necessary in another PR.

2024-09-14 14:03 UTC, kchristin22 commented on test/CUDA/GradientKernels.cu
> +// CHECK:    void add_kernel_2_grad(int *out, int *in, int *_d_out, int *_d_in) {
My concern is that it may confuse the user into thinking that it is not a kernel actually being executed (as we don't print the overload)

2024-09-14 14:14 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +// CHECK:    void add_kernel_2_grad(int *out, int *in, int *_d_out, int *_d_in) {
Please create an issue for using `Create` instead of `CreateImplicit`. 

> My concern is that it may confuse the user into thinking that it is not a kernel actually being executed (as we don't print the overload)

I think it is more misleading to not show any attribute at all. Having the attribute present is also necessary for customers wanting to independently use Clad generated-derivatives.

2024-09-15 11:33 UTC, kchristin22 commented on test/CUDA/GradientKernels.cu
> +// CHECK:    void add_kernel_2_grad(int *out, int *in, int *_d_out, int *_d_in) {
>  Having the attribute present is also necessary for customers wanting to independently use Clad generated-derivatives.

But the attribute is not the correct one if the users want to execute the function themselves, as they would expect to have the multi-threaded execution offered in a global kernel. The attribute should be `__global__` instead of `__device__`. A work-around would be to prepend the string `"__global__ "`  before the printing or dumping to source file if we want this to be intuitive.

2024-09-15 18:00 UTC, parth-07 commented
The commit message says:

> Added support of CUDA grid configuration builtin variables. Builtins tested: threadIdx, blockIdx, blockDim, gridDim, warpSize

The pull-request does not seem to have tests for `gridDim` and `warpSize`. Can you either remove them from the commit message or add tests for them?

2024-09-24 15:10 UTC, merged