Handle write-race conditions in CUDA kernels: Add atomic operation
vgvassilev/clad pull request #1104
Opened 2024-09-24 09:49 UTC by kchristin22

In case two or more threads read from the same address, when computing the reverse mode derivative this is translated into two or more threads writing in the same position:
```
__global__ void kernel(int *a, int *b) {
  int index = threadIdx.x + blockIdx.x * blockDim.x;
  a[2 * index] = b[0];
  a[2 * index + 1] = b[0];
}

void kernel_grad(int *a, int *b, int *_d_a, int *_d_b) {
    unsigned int _t1 = blockIdx.x;
    unsigned int _t0 = blockDim.x;
    int _d_index = 0;
    int index0 = threadIdx.x + _t1 * _t0;
    int _t2 = a[2 * index0];
    a[2 * index0] = b[0];
    int _t3 = a[2 * index0 + 1];
    a[2 * index0 + 1] = b[0];
    {
        a[2 * index0 + 1] = _t3;
        int _r_d1 = _d_a[2 * index0 + 1];
        _d_a[2 * index0 + 1] = 0;
        _d_b[0] += _r_d1;
    }
    {
        a[2 * index0] = _t2;
        int _r_d0 = _d_a[2 * index0];
        _d_a[2 * index0] = 0;
       _d_b[0] += _r_d0;
    }
}
``` 
A simple solution to this problem is to make the last plus-assign op atomic:
```
__global__ void kernel(int *a, int *b) {
  int index = threadIdx.x + blockIdx.x * blockDim.x;
  a[2 * index] = b[0];
  a[2 * index + 1] = b[0];
}

void kernel_grad(int *a, int *b, int *_d_a, int *_d_b) {
    unsigned int _t1 = blockIdx.x;
    unsigned int _t0 = blockDim.x;
    int _d_index = 0;
    int index0 = threadIdx.x + _t1 * _t0;
    int _t2 = a[2 * index0];
    a[2 * index0] = b[0];
    int _t3 = a[2 * index0 + 1];
    a[2 * index0 + 1] = b[0];
    {
        a[2 * index0 + 1] = _t3;
        int _r_d1 = _d_a[2 * index0 + 1];
        _d_a[2 * index0 + 1] = 0;
        atomicAdd(&_d_b[0], _r_d1);
    }
    {
        a[2 * index0] = _t2;
        int _r_d0 = _d_a[2 * index0];
        _d_a[2 * index0] = 0;
        atomicAdd(&_d_b[0], _r_d0);
    }
}
```

2024-09-26 06:06 UTC, parth-07 reviewed
Overall looks good.

2024-09-26 06:06 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        for (auto decl : lookupResult) {
Also, can we use unresolved lookup in `Sema::ActOnCallExpr` as we do in `DerivativeBuilder::BuildCallToCustomDerivativeOrNumericalDiff` instead of explicitly finding the correct `atomicAdd` declaration?

2024-09-26 06:06 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        addToCurrentBlock(atomicCall, direction::reverse);
Please shift this entire `if` path in a separate function such as `CudaAddAssign`.

2024-10-01 17:09 UTC, parth-07 requested changes

2024-10-01 17:09 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +                                                            clang::Expr* RHS) {
Why is the function not using `RHS`?

2024-10-01 17:09 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (m_DiffReq->hasAttr<clang::CUDAGlobalAttr>() ||
The same `if`-condition is repeated at two places. Can you please create a separate function for this such as: `if (shouldUseCUDAAtomicOps())`?

2024-10-02 08:05 UTC, kchristin22 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +                                                            clang::Expr* RHS) {
Great observation! It was left from the copy-paste. I'll fix it.

2024-10-02 12:02 UTC, kchristin22 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (m_DiffReq->hasAttr<clang::CUDAGlobalAttr>() ||
Should I make this a variable or a function of `ReverseModeVisitor`?

2024-10-02 15:12 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (m_DiffReq->hasAttr<clang::CUDAGlobalAttr>() ||
Function sounds better to me.

2024-10-03 17:31 UTC, parth-07 approved these changes
Looks good.

2024-10-05 20:43 UTC, merged