Add support of CUDA nested calls: Kernel call inside a host function and device function call inside kernel
vgvassilev/clad pull request #1111
Opened 2024-10-07 10:23 UTC by kchristin22

Add initial support of kernels and device functions as pullback functions. This PR doesn't handle the reverse ordering of any other cuda function prior to the original kernel call inside the host function.

2024-10-07 13:00 UTC, vgvassilev commented
In a separate PR we should probably move the cuda specific builtins into a separate header.

2024-10-08 20:05 UTC, parth-07 requested changes
We should have separate PRs for enabling kernel calls in a host function and device function call inside a kernel.

2024-10-08 20:05 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +              // if the derived param is not an array subscript and thus stored
Why don't we need to get the pointer/array for array subscript expressions? Both `*_d_param` and `_d_param[idx]` have non-pointer types, right?

2024-10-08 20:57 UTC, parth-07 commented on include/clad/Differentiator/ReverseModeVisitor.h
> +    std::unordered_map<const clang::ValueDecl*, clang::Expr*> m_ParamVariables;
It is only used to determine if a `ValueDecl*` is a function parameter, can we make it a `std::unordered_set` instead of map?

2024-10-13 05:50 UTC, parth-07 commented
Can you please rebase the pull-request on top of `origin/master`?

2024-10-13 07:02 UTC, vgvassilev commented
> Can you please rebase the pull-request on top of `origin/master`?

Done. @kchristin22 we need a better commit message.

2024-10-13 07:21 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +//CHECK-NEXT:                *_d_in += _d_y;
Why are we not using `atomicAdd` here for `_d_in` and `_d_val`?

2024-10-13 09:54 UTC, kchristin22 commented on test/CUDA/GradientKernels.cu
> +//CHECK-NEXT:                *_d_in += _d_y;
Because local vars are passed to this function for `_d_in` and `_d_val` when it's being called in `kernel_with_device_call_grad_0_2`:
```
double _r0 = 0.;
double _r1 = 0.;
device_fn_pullback_1(in[index0], val, _r_d0, &_r0, &_r1);
atomicAdd(_d_val, _r1);
```

2024-10-13 09:58 UTC, kchristin22 commented
> Done. @kchristin22 we need a better commit message.

On it!

2024-10-13 10:35 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +//CHECK-NEXT:                *_d_in += _d_y;
Oh, okay, You are right.

2024-10-13 10:45 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +// CHECK: __attribute__((device)) void device_fn_2_pullback_0_1(double *in, double val, double _d_y, double *_d_val) {
Why don't we have `_d_in` parameter in this pullback function?

2024-10-13 10:49 UTC, kchristin22 commented on test/CUDA/GradientKernels.cu
> +// CHECK: __attribute__((device)) void device_fn_2_pullback_0_1(double *in, double val, double _d_y, double *_d_val) {
Because `in` was not part of the `clad::gradient` arg list

2024-10-13 10:59 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +// CHECK: __attribute__((device)) void device_fn_2_pullback_0_1(double *in, double val, double _d_y, double *_d_val) {
That should not matter. We still need to compute derivatives with respect to `in` to correctly compute derivatives w.r.t `out` and `val`.

2024-10-13 11:05 UTC, kchristin22 commented on test/CUDA/GradientKernels.cu
> +// CHECK: __attribute__((device)) void device_fn_2_pullback_0_1(double *in, double val, double _d_y, double *_d_val) {
How could it affect the result though since we treat `in` as a value? Why should we be interested in its adjoint?

2024-10-13 12:14 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +// CHECK: __attribute__((device)) void device_fn_2_pullback_0_1(double *in, double val, double _d_y, double *_d_val) {
In the current example, this would not matter whether we compute adjoints with respect to `in` or not. But in a general case, it will matter.

Consider a simple example:

```cpp
double fn(double u, double v) {
  v = u;
  double res = v;
  return res;
}

auto fn_grad = clad::gradient(fn, "u");
```
Here, `v` is not a part of `clad::gradient` arg list. However, we still need to compute its derivative to correctly compute the derivative of `u`. The `clad::gradient` arg list contains the arguments in whose derivative the user is interested in. It does not mean that the remaining arguments are constants/non-differentiable.

2024-10-13 12:43 UTC, kchristin22 commented on test/CUDA/GradientKernels.cu
> +// CHECK: __attribute__((device)) void device_fn_2_pullback_0_1(double *in, double val, double _d_y, double *_d_val) {
Yes, but `clad` would already define `_d_v` internally as a local var, wouldn't it?

2024-10-13 20:08 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +// CHECK: __attribute__((device)) void device_fn_2_pullback_0_1(double *in, double val, double _d_y, double *_d_val) {
It ideally should, but it seems that Clad does not declare local var `_d_v` if `v` is a pointer. That's understandable because we do not know the size of the array/pointer, however, this does make Clad behavior inconsistent between a pointer/array arg and a non-pointer arg. Let's leave it for now.

2024-10-13 20:22 UTC, parth-07 approved these changes
Looks good, except for one nitpick comment.

2024-10-13 20:22 UTC, parth-07 commented on include/clad/Differentiator/ReverseModeVisitor.h
> +    std::unordered_set<const clang::ParmVarDecl*> m_GlobalArgs;
Can we please rename `m_GlobalArgs` to `m_CUDAGlobalArgs` for more clarity and intent?

2024-10-14 09:17 UTC, kchristin22 commented
Done!

2024-10-14 13:54 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +          // GPU
```suggestion
          // Check whether this param is in the global memory of the GPU
```

2024-10-14 13:54 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      for (auto param : params)
That's a good suggestion.

2024-10-14 13:54 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        m_CUDAGlobalArgs.emplace(param);
Codecov complains about missing coverage here: can we add a test that goes here?

2024-10-14 13:54 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +            BuildCallToCudaAtomicAdd(outputArgs[i], gradExpr));
Can we add a test case here?

2024-10-15 09:50 UTC, kchristin22 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        m_CUDAGlobalArgs.emplace(param);
Yes, good observation. This should actually be included in the other PR regarding kernel pullbacks. There's a test there. I'm removing it for now.

2024-10-15 15:18 UTC, kchristin22 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +            BuildCallToCudaAtomicAdd(outputArgs[i], gradExpr));
After taking a closer look into this, this condition would always be false, since this function is only called when the callback function doesn't include any pointers as args. When this is the case, local vars (f.i. `_r0`) are used as outputs call args (`&_r0` -> `double *_d_a` (output callback function parameter))

2024-10-15 17:26 UTC, vgvassilev approved these changes
LGTM!

2024-10-15 17:27 UTC, merged