Add support of cuda kernels as pullback functions
vgvassilev/clad pull request #1114
Opened 2024-10-12 14:05 UTC by kchristin22

2024-10-16 06:22 UTC, parth-07 requested changes

2024-10-16 06:22 UTC, parth-07 commented on include/clad/Differentiator/ExternalRMVSource.h
> +  /// \param CallArgs
`CallArgs` and `ArgResultDecls` mentioned in comments are not present in the function.

2024-10-16 06:22 UTC, parth-07 commented on include/clad/Differentiator/DerivativeBuilder.h
> +        clang::Expr* config = nullptr);
Can we rename `config` to `execConfig` or `CUDAExecConfig` for more clarity?

2024-10-16 06:22 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    // If the function is a global kernel, all its parameters reside in the
This comment is not strictly true. For example, for the kernel `__global__ void SomeKernel(float *a, int val)`, `val` is passed by value and will not reside in the global memory of the GPU. However, its derivative will reside in the global memory of the GPU so the behavior is correct. Can you please update this comment?

2024-10-16 06:22 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (clad::utils::hasNonDifferentiableAttribute(KCE)) {
Can you please add a test for non-differentiable CUDA kernel?

2024-10-16 06:22 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      return StmtDiff(Call, zero);
Why are we returning `zero` instead of a `nullptr` here?

2024-10-16 06:22 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +  ReverseModeVisitor::VisitCUDAKernelCallExpr(const CUDAKernelCallExpr* KCE) {
It seems that there is a lot of code-duplication in `VisitCallExpr` and `VisitCUDAKernelCallExpr`. Can you please refactor the codes to reduce code-duplication? Can we accomodate `CUDAKernelCallExpr` functionality in `VisitCallExpr` instead of having a new visitor function?

2024-10-20 20:55 UTC, parth-07 requested changes

2024-10-20 20:55 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +//CHECK-NEXT:        clad::custom_derivatives::cudaMemcpy_pullback(out_host, out, 10 * sizeof(double), cudaMemcpyDeviceToHost, _d_out_host, _d_out, &_r0, &_r1);
This will copy the contents of `_d_out_host` to `_d_out`, right? We should not override the seeds (`_d_out`) provided by a user. Users set the seed values to get the derivatives they want.

2024-10-20 20:55 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +//CHECK-NEXT:    double *_d_out_host = (double *)malloc(10 * sizeof(double));
Should we zero-initialize `_d_out_host`? Currently, its value is undefined and its value is being used. Accessing an undefined value can result in undefined-behavior.

2024-10-20 20:55 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +//CHECK-NEXT:    kernel_call_pullback<<<1, 10>>>(out, in, _d_out, _d_in);
Should we call `cudaDeviceSynchronize` before `cudaFree` calls?

2024-10-21 13:35 UTC, kchristin22 commented on test/CUDA/GradientKernels.cu
> +//CHECK-NEXT:    kernel_call_pullback<<<1, 10>>>(out, in, _d_out, _d_in);
These should be executed in order so no need

2024-10-21 13:36 UTC, kchristin22 commented on test/CUDA/GradientKernels.cu
> +//CHECK-NEXT:    double *_d_out_host = (double *)malloc(10 * sizeof(double));
Yes, but this is out of the scope of this PR

2024-10-21 15:48 UTC, kchristin22 commented on test/CUDA/GradientKernels.cu
> +//CHECK-NEXT:        clad::custom_derivatives::cudaMemcpy_pullback(out_host, out, 10 * sizeof(double), cudaMemcpyDeviceToHost, _d_out_host, _d_out, &_r0, &_r1);
I updated that part to use a local array for cudaMemcpy and then add the data to _d_out (via atomicAdd if its a device pointer)

2024-10-21 20:49 UTC, parth-07 requested changes

2024-10-21 20:49 UTC, parth-07 commented on include/clad/Differentiator/BuiltinDerivatives.h
> +  for (int i = blockIdx.x * blockDim.x + threadIdx.x; i < N;
```suggestion
  for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < N;
```

`int i` and `size_t N` have different types, thus different ranges. You can use `auto` as well.

2024-10-21 20:49 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    // If the function is a global kernel, all its parameters reside in the
This review has not been addressed. The same comment was present at two places. It seems that you have fixed the similar comment at other place. Can you please fix this as well?

2024-10-21 20:49 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +  kernel_call<<<1, 10>>>(out, in);
Can you please add another test in which the function first copies content from the host memory to device memory before calling the kernel?

2024-10-21 20:49 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +//CHECK-NEXT:        clad::custom_derivatives::cudaMemcpy_pullback(out_host, out, 10 * sizeof(double), cudaMemcpyDeviceToHost, _d_out_host, _d_out, &_r0, &_r1);
That sounds great!

2024-10-21 20:49 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +//CHECK-NEXT:    double *_d_out_host = (double *)malloc(10 * sizeof(double));
It is directly affecting this PR. We should not rely on undefined behavior nor should we merge test containing undefined behavior. Can you please fix the zero-initialize issue in a separate PR?

2024-10-21 21:02 UTC, parth-07 commented on test/CUDA/GradientKernels.cu
> +//CHECK-NEXT:    kernel_call_pullback<<<1, 10>>>(out, in, _d_out, _d_in);
> meaning the previous GPU ops will finish before free is executed as they are all executed in the default stream.

What if there are no `cudaFree` calls? Should we call `cudaDeviceSynchronize` in that case?

> Maybe it would be worth it to add them in case the user uses another stream for the kernel, as they should also include cudaDeviceSynchronize() in the original kernel. What do you think?

I believe we should not add additional `cudaDeviceSynchronize` calls because of multiple streams currently. We can add support for multiple stream by adding extra synchronization calls if the need arises.

2024-10-22 21:01 UTC, kchristin22 commented on test/CUDA/GradientKernels.cu
> +//CHECK-NEXT:    kernel_call_pullback<<<1, 10>>>(out, in, _d_out, _d_in);
They are supported for derivative kernel execution though. I can remove the `cudaDeviceSynchronize` calls from `cudaMemcpy_pullback`, but I think it doesn't hurt to keep them, as they will be added in the future either way.

2024-10-22 22:46 UTC, kchristin22 commented on test/CUDA/GradientKernels.cu
> +  kernel_call<<<1, 10>>>(out, in);
Yes, I altered this example to make it complete

2024-10-28 09:54 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +              const_cast<DeclContext*>(FD->getDeclContext()), true, true,
```suggestion
              const_cast<DeclContext*>(FD->getDeclContext()), /*forCustomDerv=*/true, /*namespaceShouldExist=*/true,
```

2024-10-28 09:54 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +              const_cast<DeclContext*>(FD->getDeclContext()), true, true,
Likewise.

2024-10-29 05:49 UTC, parth-07 approved these changes
Looks good.

2024-10-29 06:43 UTC, merged