Initialize derivative pointers that are allocated through malloc or realloc
vgvassilev/clad pull request #1124
Opened 2024-10-23 12:00 UTC by kchristin22

This PR identifies calls to `malloc` or `realloc` and for the derivative pointers it:
* replaces `malloc` with `calloc`
* adds a `calloc` call after `realloc`

2024-10-24 17:59 UTC, parth-07 requested changes

2024-10-24 17:59 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +  Expr* ReverseModeVisitor::CheckAndBuildCallToCalloc(Expr* RHS) {
Why is this function so complicated? Instead of manually parsing the `size` expression to determine `calloc` arguments, can we simply create the call as `calloc(1, sizeExpr)` where `sizeExpr` is from the original malloc call `malloc(sizeExpr)`?

2024-10-24 17:59 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        if (opCode == BO_Assign && derivedR)
Why is this required? I thought this PR is only modifying the differentiation of `malloc` calls.

2024-10-24 17:59 UTC, parth-07 commented on lib/Differentiator/VisitorBase.cpp
> +      NSD = utils::LookupNSD(m_Sema, nmspace, /*shouldExist=*/true);
Instead of adding so many conditions in this function, can you please modify `utils::LookupNSD` to return top-level namespace declaration if `nmspace` is an empty string?

2024-10-25 05:31 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        if (auto* declRef = dyn_cast<DeclRefExpr>(implCast->getSubExpr()))
```suggestion
      if (auto* declRef = dyn_cast<DeclRefExpr>(callExpr->IgnoreImpCasts()))
```

2024-10-25 05:31 UTC, vgvassilev commented on test/Gradient/Pointers.C
> +// CHECK-NEXT:     T *_d_t = (T *)calloc(n, sizeof(T));
Instead of rewiring malloc to calloc, can we do malloc and them memset? This would theoretically work better if we have a user-provided `malloc` operation.

2024-10-25 09:46 UTC, kchristin22 commented on test/Gradient/Pointers.C
> +// CHECK-NEXT:     T *_d_t = (T *)calloc(n, sizeof(T));
I tried that in the beginning, but if the user uses `memset` afterwards on the same pointer, the `memset` call would be repeated again:
```cpp
T *_d_t = (T *)malloc(n * sizeof(T));
memset(_d_t, 0, n * sizeof(T)); // emplace memset call after malloc
T *t = (T *)malloc(n * sizeof(T));
memset(_d_t, 0, n * sizeof(T));
memset(t, 0, n * sizeof(T));
```
And I don't think we should skip creating the second `memset`- meaning when we encounter a `memset` call in the original function, we should assign its derivative on the derivative pointer as well, because it's not necessary for a `memset` call to follow a `malloc` call.

I'm not sure I understand why using `memset` instead should make a difference when the `malloc` function is user provided, as either way we wouldn't be able to tell it's a memory allocation function, so we wouldn't add the `memset` call afterwards f.i. Currently, we only check for C memory functions.

2024-10-25 09:53 UTC, kchristin22 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +  Expr* ReverseModeVisitor::CheckAndBuildCallToCalloc(Expr* RHS) {
`calloc` function is used like so:
```cpp
void* calloc( size_t num, size_t size );

Allocates memory for an array of num objects of size and initializes all bytes in the allocated storage to zero.
```
While the same `malloc` call would look like: (T*)malloc(num * size)

So we have to split that `sizeExpr` into num and size.

2024-10-25 09:57 UTC, kchristin22 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        if (opCode == BO_Assign && derivedR)
I took it one step further and covered realloc as well where there's not a decl stmt, but this may be required for malloc functions also. For example:
```cpp
double *ptr = nullptr;
ptr = (double *)malloc(10 * sizeof(double));
```

2024-10-25 10:35 UTC, vgvassilev commented on test/Gradient/Pointers.C
> +// CHECK-NEXT:     T *_d_t = (T *)calloc(n, sizeof(T));
Here is the example I have in mind: https://godbolt.org/z/rfabzjTa8

If we rewire the memory calls that would ignore the use-defined logic in `malloc`...

2024-10-25 10:40 UTC, kchristin22 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +  Expr* ReverseModeVisitor::CheckAndBuildCallToCalloc(Expr* RHS) {
I see what you mean now, I was worried that it wouldn't initialize the whole block correctly if we treated it as one, but I think it should work after all. I will change that.

2024-10-25 10:49 UTC, kchristin22 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +  Expr* ReverseModeVisitor::CheckAndBuildCallToCalloc(Expr* RHS) {
I will revert back to `memset` after Vassil's comment so I mark this as resolved.

2024-10-25 11:52 UTC, kchristin22 commented on lib/Differentiator/VisitorBase.cpp
> +      NSD = utils::LookupNSD(m_Sema, nmspace, /*shouldExist=*/true);
If I understand correctly, the function you're mentioning already does that, so I can revert my changes altogether. Can you take a look?

2024-10-25 18:14 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    // FIXME: revert this when this is integrated in the activity analysis pass.
@ovdiiuv, can you comment here?

2024-10-26 11:31 UTC, ovdiiuv commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    // FIXME: revert this when this is integrated in the activity analysis pass.
I thought about that recently. I don't think it has to be reverted, rather modified to track arguments that are elements of constant sets for example. This would resolve #682.

2024-10-26 12:36 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    // FIXME: revert this when this is integrated in the activity analysis pass.
But that should be part of the analysis not here, right? That is, it needs to be implemented on your end.

2024-10-26 12:42 UTC, parth-07 commented on lib/Differentiator/VisitorBase.cpp
> +      NSD = utils::LookupNSD(m_Sema, nmspace, /*shouldExist=*/true);
`utils::LookupNSD` does not seem to return top-level namespace (translation unit decl) if `nmspec` is an empty string. Why do you think it does?

2024-10-26 12:51 UTC, ovdiiuv commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    // FIXME: revert this when this is integrated in the activity analysis pass.
No, I think it's the right place.

2024-10-27 11:44 UTC, parth-07 approved these changes

2024-10-27 11:46 UTC, merged