Fix for Parenthesis issue in gradients
vgvassilev/clad pull request #1180
Opened 2024-12-20 06:40 UTC by toshit3q34

This resolves the issue with two or more consecutive negative signs while dumping the code.
While copying the code to m_Code, changes include iterating the loop and checking when there are two or more consecutive negative signs and resolves them to be either '-' or ' ' depending on the parity.

Eg.
-(-(-1))*(x) 
Before :  _d_x += - - -1 * 1;
After : _d_x += -1 * 1;

The differentiate remains intact.
Fixes : #1098

2024-12-20 07:00 UTC, vgvassilev requested changes

2024-12-20 07:00 UTC, vgvassilev commented on include/clad/Differentiator/Differentiator.h
> +CUDA_HOST_DEVICE void ResolveParenthesis(char* temp, const char* code) {
We do not do textual parsing and transformations. The solution must be on AST level in one of our Visitor classes. You should check our documentation for more details.

2024-12-20 07:00 UTC, vgvassilev commented on include/clad/Differentiator/Differentiator.h
> +/// Add value to the end of the tape, return the same value.
Running clang-format on the entire file is not a good idea. We should run it only on the changes with `git-clang-format HEAD~`.

2024-12-21 21:37 UTC, toshit3q34 commented
@vgvassilev Thanks! I went through the documentation and have fixed the issue in the `BuildParens` function of `VisitorBase` class. The tests compile without a problem but CHECK-NEXT shows error in 5 tests due to mistmaching body statements.
Example : 
Expected : `-_d_x * x + -x * _d_x`
After the changes : `(-_d_x) * x + (-x) * _d_x`

What should be done to deal with such instances or those 5 tests need to be changed ?

2024-12-22 18:15 UTC, toshit3q34 commented
@vgvassilev Codecov test is failing because there is no test to check those lines.
Example : `f(x) = (-1) * (-(-x))`
So should I add a file for such tests ?

2024-12-22 19:03 UTC, vgvassilev commented on lib/Differentiator/VisitorBase.cpp
> +  Expr* VisitorBase::RemoveFirstUnaryMinus(Expr* E, SourceLocation OpLoc) {
Rather than removing the minus we should figure out where we synthesize the minus and we need parens.

2024-12-22 19:22 UTC, toshit3q34 commented on lib/Differentiator/VisitorBase.cpp
> +  Expr* VisitorBase::RemoveFirstUnaryMinus(Expr* E, SourceLocation OpLoc) {
I tried to do that at first and was able to do it as well. However for some cases like :
`f(x) = (-(-1)) * (-(-(x)))` if we try to parenthesize, the output becomes `(-(-(-(-1))*1))` which looks quite cluttered and redundant. Similar thing also happens when we try for higher powers like 
`f(x) = (-1) * (-x) * (-x) * (-x)`
Would you recommend continuing to parenthesize in such cases, or would it be acceptable to simplify the representation for clarity?

2024-12-22 20:27 UTC, vgvassilev commented on lib/Differentiator/VisitorBase.cpp
> +  Expr* VisitorBase::RemoveFirstUnaryMinus(Expr* E, SourceLocation OpLoc) {
It's better to add parenthesis only at the places where it is necessary.

2024-12-22 20:35 UTC, toshit3q34 commented on lib/Differentiator/VisitorBase.cpp
> +  Expr* VisitorBase::RemoveFirstUnaryMinus(Expr* E, SourceLocation OpLoc) {
Okay sure. Can you please specify the expected output of `f_grad()` for `f(x) = (-(-1)) * (-(-(x)))` so that I have a basis to work with and can modify accordingly. Thanks.

2025-01-10 16:26 UTC, toshit3q34 commented
@vgvassilev I hope you have reviewed the code. I have done the following two things :
1. Reduce unary minus when done on the same operand to avoid clutter. example : `---2 becomes -2`
2. Add parenthesis when unary minus is added in front of compound statement as asked before. 
example : `--1*x becomes -(-1*x)`

The codecov tests fail because there are no tests which check either of the above conditions. 
Is there anything else that I need to change ?

2025-01-10 17:24 UTC, vgvassilev commented
Can you add a few tests demonstrating this pull request works?

2025-01-11 14:15 UTC, toshit3q34 commented
@vgvassilev I have added a test file containing two tests which covers the above stated scenarios. You may review it now.

2025-01-21 20:59 UTC, parth-07 approved these changes
Looks good.

2025-01-22 11:36 UTC, vgvassilev approved these changes
LGTM!

2025-01-22 16:51 UTC, merged