Generate code for Enzyme autodiff for functions with Pointer/array arguments
vgvassilev/clad pull request #466
Opened 2022-06-29 05:02 UTC by Nirhar

For functions of type
	```double myfunction(double* arr){...};```
OR 	```double myfunction(double arr[3]){...};```

we generate derivative code of type:
```	
        void d_myfunction(double* arr, clad::array_ref<double> _d_arr){
		double* d_arr = _d_arr.ptr();
		__enzyme_autodiff_myfunction(myfunction, arr, d_arr);
	}
```

Further on enzyme will handle the function differentiation

2022-06-29 09:16 UTC, parth-07 commented
> @vgvassilev @parth-07 The clad code in this pull request throws the error
> 
> "cannot initialize a parameter of type 'double (double *)' with an lvalue of type 'double (double *)'"
> 
> during compilation of the below code:
> 
> ```c++
> #include "clad/Differentiator/Differentiator.h"
> double f(double *arr) { return arr[0] * arr[1]; }
> int main() {
>     auto f_grad=clad::gradient<clad::opts::use_enzyme>(f);
> }
> ```
> 
> Any idea how to resolve this?

Are you able to print generated derived function? If yes, can you please paste that in a comment here?

2022-06-29 14:11 UTC, Nirhar commented
@parth-07 No, I am not able to print the generated function. The same error is thrown when I attempt to print it.

2022-06-29 16:27 UTC, Nirhar commented
> > @parth-07 No, I am not able to print the generated function. The same error is thrown when I attempt to print it.
> 
> Have you tried printing the derived function using the flag `-fdump-derived-fn`?

Yes I tried that, the generated function does not contain the __enzyme_autodiff function call

2022-06-29 16:27 UTC, Nirhar commented
> > "cannot initialize a parameter of type 'double (double *)' with an lvalue of type 'double (double *)'"
> 
> The error suggests that you are using an incorrect value category (https://en.cppreference.com/w/cpp/language/value_category) for the function argument of the call to `__enzyme_autodiff_`. Correctly generating `clang::DeclRefExpr` node may fix the issue. You can use, `Sema::BuildDeclRefExpr` or `VisitorBase::BuildDeclRef` for correctly generating it.

Okay let me try this out

2022-07-05 05:14 UTC, Nirhar commented
This code runs on my machine, but here the tests throw the error ``` fatal: could not create work tree dir 'Enzyme': Permission denied```. How do I deal with this @vgvassilev @parth-07 ?

2022-07-05 10:58 UTC, Nirhar commented
Now I am getting the below error in the CI tests:
```
CMake Error: Could not open file for write in copy operation /usr/local/EnzymeAD/tmp/Enzyme-mkdirs.cmake.tmp
```
I am not getting this error on my machine. How do I resolve this @vgvassilev @parth-07?

2022-07-05 14:06 UTC, parth-07 commented on test/lit.cfg
>      lit_config.note('using auto diff lib: %r' % config.cladlib)
We should branch these if conditions into one.

2022-07-05 14:09 UTC, parth-07 commented on CMakeLists.txt
> +  BUILD_COMMAND ninja
If I recall correctly, ubuntu GitHub runners do not include the Ninja build system by default. Can you make sure if it is installed in a runner or not?

2022-07-05 14:15 UTC, parth-07 commented
> Now I am getting the below error in the CI tests:
> 
> ```
> CMake Error: Could not open file for write in copy operation /usr/local/EnzymeAD/tmp/Enzyme-mkdirs.cmake.tmp
> ```
> 
> I am not getting this error on my machine. How do I resolve this @vgvassilev @parth-07?

It seems to be a permission issue. Can you try to install it in a non-root directory? And also, check if we are missing the right permissions somewhere.

2022-07-05 14:38 UTC, Nirhar commented on test/lit.cfg
>      lit_config.note('using auto diff lib: %r' % config.cladlib)
done

2022-07-05 14:42 UTC, Nirhar commented
> > Now I am getting the below error in the CI tests:
> > ```
> > CMake Error: Could not open file for write in copy operation /usr/local/EnzymeAD/tmp/Enzyme-mkdirs.cmake.tmp
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am not getting this error on my machine. How do I resolve this @vgvassilev @parth-07?
> 
> It seems to be a permission issue. Can you try to install it in a non-root directory? And also, check if we are missing the right permissions somewhere.

Currently I am installing Enzyme in the "CMAKE_INSTALL_PREFIX". I think in the CI machines this is in some root directory. Where do I install it, is the build_dir a good place?

2022-07-05 15:34 UTC, parth-07 commented
> > > Now I am getting the below error in the CI tests:
> > > ```
> > > CMake Error: Could not open file for write in copy operation /usr/local/EnzymeAD/tmp/Enzyme-mkdirs.cmake.tmp
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I am not getting this error on my machine. How do I resolve this @vgvassilev @parth-07?
> > 
> > 
> > It seems to be a permission issue. Can you try to install it in a non-root directory? And also, check if we are missing the right permissions somewhere.
> 
> Currently I am installing Enzyme in the "CMAKE_INSTALL_PREFIX". I think in the CI machines this is in some root directory. Where do I install it, is the build_dir a good place?

You can just specify a non-root directory for the `CMAKE_INSTALL_PREFIX` option in the CMake configure command.

2022-07-05 15:36 UTC, parth-07 commented
> Where do I install it, is the build_dir a good place?

Any non-root directory should work for the debugging purpose right now. We would like things to work as expected when the user is installing in root locations as well. Thus the main goal is to find the underlying issue that's causing the CMake configuration to fail.

2022-07-05 17:47 UTC, Nirhar commented
Its mentioned in the Enzyme website that Enzyme has been tested against LLVM 7,8,9,10,11,12. I personally tested it against LLVM 13 and 14 and it works. Maybe the lower versions of LLVM/clang are causing a problem? As I have seen, most failures in the CI are because the Enzyme build has failed.

2022-07-05 17:51 UTC, parth-07 commented
> Its mentioned in the Enzyme website that Enzyme has been tested against LLVM 7,8,9,10,11,12. I personally tested it against LLVM 13 and 14 and it works. Maybe the lower versions of LLVM/clang are causing a problem? As I have seen, most failures in the CI are because the Enzyme build has failed.

Can you test enzyme integration with Clad when lower versions of LLVM are used in your local system?

2022-07-06 05:26 UTC, Nirhar commented
@parth-07 Enzyme fails during build in my System when built with llvm 6, with the same errors as thrown by the CI module, for example osx-clang-runtime6

I noticed a few other CI modules fail due to a flag used during compilation with enzyme(after build), an unrecognised flag in lower versions of llvm. I will correct this.

2022-07-15 07:36 UTC, vgvassilev commented
Can you rebase your PR, I think we have fixed the bot failures.

2022-07-16 07:43 UTC, parth-07 requested changes

2022-07-16 07:43 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (num_params == 1) {
Based on the above comment, shouldn't we add a check here to make sure that the first parameter is of array/pointer type?

2022-07-16 07:43 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        if (dyn_cast_or_null<ConstantArrayType>(t_ptr) ||
In which case can `t_ptr` be null here?
And if you do not need the cast result, then prefer to use `llvm::isa<>`.

2022-07-16 07:43 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +              VK_LValue, noLoc);
Prefer to use `VisitorBase::BuildDeclRef` here, that makes the codebase more uniform and easier to read.

2022-07-16 07:43 UTC, parth-07 commented on include/clad/Differentiator/Compatibility.h
> +#define CLAD_COMPAT_ACTIONRESULT_TO_PTRTY(Res) Res.get()
Can we use `clad_compat::GetResult<...>` instead of this?

2022-07-16 07:43 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +              m_Context.VoidTy, enz_params_type, noLoc, name_enz,
We generally use a camel case for local variable names. But we also do not have any fixed convention. @vgvassilev Should we decide and create some naming convention for the codebase?

2022-07-16 07:43 UTC, parth-07 commented on test/Enzyme/ReverseMode.C
> +double f(double* arr) { return arr[0] * arr[1]; }
Can you add more comprehensive tests? You mentioned in chat that you got enzyme to work for a wide class of function prototypes. Can you also add tests for them?

2022-07-16 07:43 UTC, parth-07 commented on test/Enzyme/ReverseMode.C
> +  f_grad.execute(v, g);
Does enzyme require size information of primal or derivative array anywhere?

2022-07-16 08:45 UTC, Nirhar commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (num_params == 1) {
yes this done in line number 482

2022-07-16 08:48 UTC, Nirhar commented on test/Enzyme/ReverseMode.C
> +double f(double* arr) { return arr[0] * arr[1]; }
This PR does not deal with that, it only deals with function prototypes which have a single arraytype or pointer as argument. My next PR will contain more examples and will deal with different types of function prototypes.

2022-07-16 08:49 UTC, Nirhar commented on test/Enzyme/ReverseMode.C
> +  f_grad.execute(v, g);
No it doesnt for this specific example. Examples where size information are required will be given in the next PR.

2022-07-16 09:54 UTC, Nirhar commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        if (dyn_cast_or_null<ConstantArrayType>(t_ptr) ||
changed it to llvm::isa<>

2022-07-16 09:55 UTC, Nirhar commented on lib/Differentiator/ReverseModeVisitor.cpp
> +              VK_LValue, noLoc);
Done

2022-07-16 09:56 UTC, Nirhar commented on include/clad/Differentiator/Compatibility.h
> +#define CLAD_COMPAT_ACTIONRESULT_TO_PTRTY(Res) Res.get()
Since I am using ```VisitorBase::BuildDeclRef```, which already contains ```clad_compat::GetResult<...>```, I have removed this code

2022-07-16 09:57 UTC, Nirhar commented on lib/Differentiator/ReverseModeVisitor.cpp
> +              m_Context.VoidTy, enz_params_type, noLoc, name_enz,
changed variable names to camel case

2022-07-16 14:34 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +              m_Context.VoidTy, enz_params_type, noLoc, name_enz,
> We generally use a camel case for local variable names. But we also do not have any fixed convention. @vgvassilev Should we decide and create some naming convention for the codebase?

We should, although what we do is consistent to clang where there is nothing strict enforced. However, I agree we should not add more coding convention styles :)

2022-07-16 14:47 UTC, parth-07 commented on test/Enzyme/ReverseMode.C
> +  f_grad.execute(v, g);
Okay! 
Can you add this information in the PR description?

2022-07-16 15:06 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      unsigned numParams = m_Function->getNumParams();
This function does a lot of things now. We should try to make the code more modular. Should we divide it into smaller sections using something like this: 

```cpp
if (!use_enzyme)
  DifferentiateUsingClad(...);
else
  DifferentiateUsingEnzyme(...);
gradientBody = endBlock();
```

@vgvassilev What do you think about this?

2022-07-16 15:06 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +          FunctionDecl* enzymeCallFD = FunctionDecl::Create(
Where are you creating and pushing scopes necessary for the `enzymeCallFD` ? For example, codes like these:
```cpp
beginScope(Scope::FunctionPrototypeScope | Scope::FunctionDeclarationScope |
               Scope::DeclScope);
m_Sema.PushFunctionScope();
m_Sema.PushDeclContext(getCurrentScope(), m_Derivative);
```

2022-07-16 15:26 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +          FunctionDecl* enzymeCallFD = FunctionDecl::Create(
Since `enzymeCallFD` represents an extern function declaration, we do not scopes here.

2022-07-16 16:51 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      unsigned numParams = m_Function->getNumParams();
That sounds reasonable to me.

2022-07-16 17:07 UTC, Nirhar commented on test/Enzyme/ReverseMode.C
> +  f_grad.execute(v, g);
Done

2022-07-16 17:09 UTC, Nirhar commented on lib/Differentiator/ForwardModeVisitor.cpp
> +    } else {
I have removed Fwd mode code from here for now, would add it later when I make a PR for forward mode

2022-07-16 17:09 UTC, Nirhar commented on lib/Differentiator/ReverseModeVisitor.cpp
> +          FunctionDecl* enzymeCallFD = FunctionDecl::Create(
enzymeCallFD is an extern function, and hence it would not need a Scope

2022-07-16 17:26 UTC, Nirhar commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      unsigned numParams = m_Function->getNumParams();
I think this is a good idea, but I would want to attempt this after a few more PRs .

2022-07-17 07:45 UTC, vgvassilev reviewed
Looks like we are making progress but we still have a few rough edges. Codecov reports quite a lot of untested branches. Can you also add the relevant tests?

2022-07-17 07:45 UTC, vgvassilev commented on .github/workflows/ci.yml
> +            no_enzyme: true
We do not need `no_enzyme`, we can write `enable_enzyme` for the platform we care about and for the rest it will be undefined. Then we can check `if enable_enzyme` and that should be enough.

2022-07-17 07:45 UTC, vgvassilev commented on .github/workflows/ci.yml
>            ${{ matrix.extra_cmake_options }}
We should use the `extra_cmake_options` to add `-DENZYME=On`. I think we should call this option `ENABLE_ENZYME_BACKEND`.

2022-07-17 07:45 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      unsigned numParams = m_Function->getNumParams();
That would bloat the history for no good reason I fear.

2022-07-17 07:45 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +            llvm::isa<PointerType>(tPtr)) {
```suggestion
        QualType OrigTy = origParams[0]->getOriginalType();
        if (OrigTy->isConstantArrayType() || OrigTy->isPointerType()) {
```

2022-07-17 07:45 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        arrayOfParams); This is straightforward to deal in enzyme - DONE
Stray comments?

2022-07-17 07:45 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +              const_cast<DeclContext*>(FD->getDeclContext()), noLoc,
We should use a local variable for the DeclContext here.

2022-07-17 12:05 UTC, Nirhar commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      unsigned numParams = m_Function->getNumParams();
Okay, I have put both those sections into 2 different functions

2022-07-17 14:02 UTC, vgvassilev commented on test/Enzyme/ReverseMode.C
> +// RUN: clang output_opt.ll -o Enzyme.out -lstdc++ -lm
We should construct enzyme in clad. That is, we should call `%cladclang ... -fenzyme-backend ...`, then clad should construct the expected optimization pipeline by enzyme, compile it and trigger enzyme.

2022-07-17 14:17 UTC, Nirhar commented on test/lit.cfg
> +config.opt = inferOpt(config.environment['PATH']).replace('\\', '/')
We need opt because, when enzyme generates code, it generates derivative code which is unoptimised. It is recommended that this code is passed through various compiler optimisations like constant folding, expression simplifications etc to increase performance. Moreover the enzyme pass is linked during an opt execution.

2022-07-17 14:21 UTC, Nirhar commented on test/lit.cfg
> +    #FIX-THIS: CMAKE_INSTALL_PREFIX is not recognised
yes enzyme is a shared library, and it is located in the build folder configured by external project add in cmake. This build folder is somewhere inside the EnzymeAD folder(which is inside the clad folder). The existence of the EnzymeAD folder will show that enzyme has been included in the project

2022-07-20 04:33 UTC, Nirhar commented on test/Enzyme/ReverseMode.C
> +// RUN: clang output_opt.ll -o Enzyme.out -lstdc++ -lm
I managed to remove dependency on opt, and have integrated the enzyme pass into clang command itself. Do I need to create this special flag called "-fenzyme-backend"? I think creation of this flag is out of the scope of clad, as clad only has a frontend plugin, but enzyme has to act in the backend right?

2022-07-27 11:05 UTC, vgvassilev commented on test/Enzyme/ForwardMode.C
>  // XFAIL:*
Why this test is expected to fail?

2022-07-27 11:27 UTC, Nirhar commented on test/Enzyme/ForwardMode.C
>  // XFAIL:*
Differentiation of functions in Forward mode AD with enzyme is not yet implemented.

2022-07-27 11:30 UTC, vgvassilev commented on test/Enzyme/ForwardMode.C
>  // XFAIL:*
Ah, ok, let's add that as a comment before the xfail.

2022-08-12 06:02 UTC, vgvassilev commented on .github/workflows/ci.yml
> -
Maybe this change here is significant. Can you undo it?

2022-08-12 06:47 UTC, Nirhar commented on tools/ClangPlugin.cpp
> +  PR->enumerateWith(&er);
I could have used `PR->getPassInfo("enzyme")` and removed the dependence on `PassRegistrationListener`, but for some reason, the `getPassInfo` function returned `nullptr` for the above code. hence I had to use the `PassRegistrationListener` to iterate through all the passes and get the enzyme pass

2022-08-12 12:48 UTC, vgvassilev commented on tools/ClangPlugin.cpp
> +  PR->enumerateWith(&er);
Can you investigate why that happens?

2022-08-12 12:50 UTC, vgvassilev commented on tools/ClangPlugin.cpp
> +#if LLVM_VERSION_MAJOR >= 9
Do we have test coverage for clang later than 9? If not we should add a new entry to the build matrix.

2022-08-12 12:50 UTC, vgvassilev commented on tools/ClangPlugin.cpp
> +static llvm::RegisterStandardPasses enzymePassLoader_LTO(
These should probably go in `ClangBackendPlugin.cpp`.

2022-08-12 12:50 UTC, vgvassilev commented on tools/ClangPlugin.h
> +    struct EnzymePassRegistrationListener : llvm::PassRegistrationListener {
Why this code is in the header file and not in the source file?

2022-08-12 12:55 UTC, vgvassilev commented on tools/CMakeLists.txt
> +endif()
```suggestion

```
We do not need that anymore.

2022-08-13 03:27 UTC, Nirhar commented on tools/ClangPlugin.cpp
> +#if LLVM_VERSION_MAJOR >= 9
currently the tests are run in clang-runtime 11, so adding a new entry into build matrix must not be needed

2022-08-13 03:28 UTC, Nirhar commented on tools/ClangPlugin.h
> +    struct EnzymePassRegistrationListener : llvm::PassRegistrationListener {
Okay I will shift it to the source file

2022-08-13 04:19 UTC, Nirhar commented on tools/ClangPlugin.cpp
> +  PR->enumerateWith(&er);
Okay, upon some debugging I found that there are two overloaded functions for getPassInfo, one of which takes a StringRef argument, which gives its name, and the other void* type argument which is supposed to give its identifier. I was giving a char* as input hoping that it would be casted as a StringRef, but it was interpreting it as a void* argument and hence the wrong function was being called. Explicitly creating a StringRef object and passing it to getPassInfo solved the problem.

2022-08-13 05:36 UTC, Nirhar commented on tools/ClangPlugin.cpp
> +    return;
The bot shows this part of the code as not covered because, this part of the code will be executed only when cmake is not configured to enable enzyme, and hence the enzyme pass is not found. In the bot where tests are enabled, this will not be covered, and hence the error. The fact that the other bots run successfully mean that this portion of code is executed when enzymePass is not found saving us from some seg faults

2022-08-13 14:41 UTC, vgvassilev commented on test/Enzyme/ForwardMode.C
> +// REQUIRES: Enzyme
Can you check if this actually runs?

2022-08-13 14:41 UTC, vgvassilev commented on tools/ClangPlugin.cpp
> +    llvm::PassManagerBuilder::EP_FullLinkTimeOptimizationEarly, loadLTOPass);
Can you move this in `ClangBackendPlugin.cpp`?

2022-08-13 17:17 UTC, vgvassilev commented on tools/ClangBackendPlugin.cpp
> +  if (!enzymePassInfo)
I do not see how that would be the case if we have linked enzyme in clad. Perhaps turn this into an assertion.

2022-08-13 17:17 UTC, vgvassilev commented on tools/ClangBackendPlugin.cpp
> +  if (!nvvmPassInfo)
Likewise.

2022-08-13 17:17 UTC, vgvassilev commented on tools/ClangBackendPlugin.cpp
> +    llvm::PassManagerBuilder::EP_FullLinkTimeOptimizationEarly, loadLTOPass);
I don't think we use clad in the context of link-time optimizations. I'd suggest to leave that our for now, including the `loadLTOPass` function.

2022-08-13 17:27 UTC, Nirhar commented on tools/ClangBackendPlugin.cpp
> +  if (!enzymePassInfo)
The linking happens only if the ENABLE_ENZYME_BACKEND flag is set during cmake configuration. This is not set in the usual case, and hence the enzyme pass will not be found in the regular use case

2022-08-13 17:31 UTC, vgvassilev commented on tools/ClangBackendPlugin.cpp
> +  if (!enzymePassInfo)
Ah... fair point, this code is still triggered. Perhaps we can adjust that as well to be conditional outside of this PR.

2022-08-13 17:45 UTC, Nirhar commented on tools/ClangBackendPlugin.cpp
> +  if (!enzymePassInfo)
Hmm.. for me codecov shows that this code is not covered by tests. Are you looking at line 40 or 41?

2022-08-13 17:52 UTC, vgvassilev commented on tools/ClangBackendPlugin.cpp
> +  if (!enzymePassInfo)
Both. I wanted to avoid that report from codecov.

2022-08-14 17:57 UTC, Nirhar commented on tools/ClangBackendPlugin.cpp
> +                          loadNVVMPass);
The osx-clang-9 bot seems to fail when the destructors of these objects are called by the runtime, during program termination. Will I have to build clang in debug mode on this bot to understand what's happening?

2022-08-14 18:09 UTC, Nirhar commented on tools/ClangBackendPlugin.cpp
> +                          loadNVVMPass);
[This](https://github.com/sampsyo/llvm-pass-skeleton/issues/7#issuecomment-461988004) seems like a reasonable explanation to what's happening

2022-08-14 18:57 UTC, Nirhar commented on tools/ClangBackendPlugin.cpp
> +                          loadNVVMPass);
Basically, this issue seems to be a standard problem in llvm-9 on Mac OS, and has been fixed in llvm-10. The only work around for this problem is [this](https://github.com/sampsyo/llvm-pass-skeleton/issues/7#issuecomment-576786718). As per the instructions in the link, I am setting the environment variable, and running clang as below:
```
export DYLD_INSERT_LIBRARIES="./obj/lib/clad.dylib"
/usr/local/opt/llvm@9/bin/clang -I ./include -x c++ -std=c++11 -fplugin=./obj/lib/clad.dylib trial.cpp -o trial -lstdc++ -lm
```

but I get the error:
```
dyld: could not load inserted library './obj/lib/clad.dylib' because no suitable image found.  Did find:
        ./obj/lib/clad.dylib: not a dylib
        ./obj/lib/clad.dylib: stat() failed with errno=1
```
@vgvassilev any leads on how this can be resolved? Clearly the .dylib object is found, but is not recognised as a .dylib object. I did try the top answer in [this](https://stackoverflow.com/questions/32730312/reason-no-suitable-image-found), but that too didnt work.

2022-08-14 20:39 UTC, vgvassilev commented on tools/ClangBackendPlugin.cpp
> +                          loadNVVMPass);
Can you provide the stacktrace for the early dlclose call?

2022-08-15 04:43 UTC, Nirhar commented on tools/ClangBackendPlugin.cpp
> +                          loadNVVMPass);
The nvvm pass is not crucial for enzyme to operate.  Currently I have commented the early nvvm pass registration, and still the error occurs

2022-08-15 19:21 UTC, vgvassilev approved these changes
LGTM! Great work @Nirhar!

The codecov coverage reports are mostly due to code using the new pass manager. Unfortunately enzyme has not yet moved to the new pass manager. It's registration happens via the old way. However, I'd like to keep the new way around and they move we will do little work to reuse the already put in place infrastructure.

2022-08-15 19:22 UTC, merged