Add support for Pullback of a Pushforward Function
vgvassilev/clad pull request #497
Opened 2022-09-07 18:17 UTC by Nirhar

requesting @parth-07 for a code review

2022-09-09 19:00 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +
Can you add an assert here that ensures that the init list expression is of `clad::PushforwardAndValue` type?

2022-09-12 13:16 UTC, Nirhar commented
requesting @vgvassilev for review

2022-09-12 13:22 UTC, vgvassilev commented
Can you remove the XFAILs introduced in this commit https://github.com/vgvassilev/clad/commit/fac880fcd5a047b9be034d963e1d306a0f5c01d6

2022-09-12 14:44 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    bool isValueAndPushforward =
We could model that similarly to `VisitorBase::isCladArrayType`?

2022-09-12 14:44 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      llvm::SmallVector<Expr*, 16> clonedExprs(ILE->getNumInits());
Can we move out this invariant code outside the if-stmt?

2022-09-15 19:35 UTC, parth-07 requested changes

2022-09-15 19:35 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (!isValueAndPushforward) {
Can we create `_return` variable even when the return type is a class type? It will keep things consistent. 
If not, then can you please add the reason why we are not creating `_return` variable when the return type is a class type?

2022-09-15 19:35 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        m_ExternalSource->ActBeforeFinalisingVisitReturnStmt(ExprDiff,
Why don't we call it outside the `if (!isValueAndPushforward)` block?

2022-09-15 19:35 UTC, parth-07 commented on test/Hessian/BuiltinDerivatives.C
> +// RUN: %cladclang %s -lm -I%S/../../include -oHessianBuiltinDerivatives.out 2>&1
Why did you remove 'FileCheck' from here?

2022-09-15 19:35 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      auto argDiff = Visit(arg, dfdx());
Can you please add a FIXME comment here explaining the limitations of constructor differentiation here?

2022-09-15 19:35 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      StmtDiff clonedValueEI = Visit(ILE->getInit(0), dValueExpr).getExpr();
Can you please add a comment here why don't we need derivative expression here of `ILE->getInit(0)`, and `ILE->getInit(1)`.

2022-09-18 14:35 UTC, Nirhar commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        m_ExternalSource->ActBeforeFinalisingVisitReturnStmt(ExprDiff,
This cannot be done because `retDeclRefExpr` sent as parameter in function call is declared in the previous line of the same block

2022-09-18 14:36 UTC, Nirhar commented on test/Hessian/BuiltinDerivatives.C
> +// RUN: %cladclang %s -lm -I%S/../../include -oHessianBuiltinDerivatives.out 2>&1
This was a temporary change. It will be added in the final version of the PR

2022-09-18 14:39 UTC, Nirhar commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (!isValueAndPushforward) {
Yes, the explanation for this has been added just before the if block begins

2022-09-18 15:34 UTC, Nirhar commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      llvm::SmallVector<Expr*, 16> clonedExprs(ILE->getNumInits());
Done

2022-09-19 18:23 UTC, vgvassilev approved these changes
LGTM but let's wait on @parth-07's review.

2022-09-19 18:23 UTC, vgvassilev commented on test/ROOT/Hessian.C
> -// XFAIL:*
Awesome!

2022-09-21 18:51 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      auto argDiff = Visit(arg, dfdx());
We can open an issue later on regarding construction differentiation limitations. We are not differentiating constructors right now at all. `Visit(arg, dfdx())` is also not correct for a general case because relationship between `dfdx()` and `arg` depends on the constructor. We should ideally create a pullback function for the constructor, and the pullback function should update argument derivatives based on the `dfdx`.

2022-09-21 18:57 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      StmtDiff clonedValueEI = Visit(ILE->getInit(0), dValueExpr).getExpr();
We most probably do not need derivative expression here.

2022-09-21 18:58 UTC, parth-07 approved these changes
Looks good.

2022-09-22 15:11 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      auto argDiff = Visit(arg, dfdx());
@Nirhar, please open an issue about that so that we do not forget.

2022-09-22 15:12 UTC, vgvassilev commented
Let's merge it - I do not understand the codecov report - probably some false positive...

2022-09-22 15:12 UTC, merged