Fix incompatible array pushes to tape.
vgvassilev/clad pull request #513
Opened 2022-12-07 16:10 UTC by grimmmyshini

Previously, if we see an array that is passed to a function, we would try to insert it into the tape. However, this is wrong because best case, we would end up only cloning the array pointer and not the array itself. This commit introduces a new tape push function that captures a snapshot (clones the array contents) when a pointer is pushed to the tape.

This method is very inefficient given that most function implicity treat arrays as read-only data structures, so we end up cloning the unchanged array several times. One possible fix is to identify if the function the array is passed to expects a const array and then do not clone the array.

This one PR, by no means, is a complete solution to the problem with arrays in loops.

2022-12-07 21:32 UTC, vgvassilev reviewed
Can you undo the trailing white space fixes unless the code was touched on purpose. Also, please add more tests at least where codecov suggested.

2022-12-08 01:11 UTC, grimmmyshini commented
done.

2022-12-13 21:36 UTC, parth-07 requested changes

2022-12-13 21:36 UTC, parth-07 commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE array(const array<T>& arr) : array(arr.m_arr, arr.m_size) {}
This will lead to a segmentation fault. clad::array owns the array memory it contains and deletes the memory when it is destroyed. With this copy constructor, multiple references of clad::array will point to the same memory, and all of them will try to delete the memory when they are being destroyed.

We should delete the copy constructor of clad::array, and make it a move-only type.

2022-12-13 21:36 UTC, parth-07 commented on include/clad/Differentiator/Array.h
> +    this = arr.m_arr;
Why do we assign `this` to a pointer of type `T*`?
Why don't we have any return value here?

2022-12-13 21:36 UTC, parth-07 commented on include/clad/Differentiator/Differentiator.h
> +    to.emplace_back(val...);
We should do perfect-forwarding here using `std::forward`

2022-12-17 21:14 UTC, vgvassilev commented
Ping on the comments. Did you resolve the cloning issue?

2022-12-18 12:09 UTC, grimmmyshini commented
Hi, Vassil! 

Yes, after uselessly debugging this, I realized the issue was quite simple: 

In the generated code, the derivative was declared before the size could be declared (as all derivatives are put into the global block by default):  

```cpp
clad::array<double> _d_arr(n);
// end of Global block
// start of forward block
int n = k;
```

I have fixed this by putting variable-sized array decls in the forward block, like so: 

```cpp
// start of forward block
int n = k;
clad::array<double> _d_arr(n);
```

However, you can tell this just won't work for variable-sized arrays declared in loops and would lead to something like this: 

```cpp
for (int i = 0; i < 3; i++) {
    _t0++;
    int n = k;
    clad::array<double> _d_arr(n);
    double arr[n];
    \\ ...
}
```

So, this is a proposed fix: 

Modify the `clad::array` class to contain a dummy memory address (or nullptr) and then actually allocate the space later. So something like this...

```cpp
// array is now decl'd in global scope with some dummy size.
clad::array<double> _d_arr(1);
for (int i = 0; i < 3; i++) {
    _t0++;
    int n = k;
   // The following function will delete the previous data and reallocate new memory depending on n. 
   // Since only we want to use this if the size of the previous was the same, we do not allocate new space.
    _d_arr.reallocateSpaceForNewSize(n);
    double arr[n];
    \\ ...
}
```

However, I am not sure if this approach is sane AD-wise. Maybe we want to save every copy of the diff array declared in the previous example, and then we would probably need something more sophisticated. Although in my opinion, this should not be necessary... 

Anyway, this is a big change and needs more discussion, so I don't know if we want to include it in this PR.

2022-12-18 12:10 UTC, grimmmyshini commented on include/clad/Differentiator/Differentiator.h
> +    to.emplace_back(val...);
yes sure

2022-12-18 12:12 UTC, grimmmyshini commented on include/clad/Differentiator/Array.h
> +    this = arr.m_arr;
First point - because I expect the overloaded operator `CUDA_HOST_DEVICE array<T>& operator=(T* arr)` to be called there. 

Second point - that is a fair point, we should return `*this`

2022-12-18 13:09 UTC, vgvassilev commented
I am not sure if ré-(allocating) in a loop is a good idea. I fail to understand why we can’t debug the original issue. This has been a repeating problem with your setup. Is there anything unique to your setup that prevents you to debug why the reference is not properly updated and more globally, what clang does in the same setup when processing textually written code.

2022-12-18 13:37 UTC, grimmmyshini commented
Um, I think you misunderstood my message above. I did debug it, but then I realized that the cloning was okay rather the size was being declared later than the actual array declaration causing a bad-alloc. More details on the previous message.

2022-12-21 07:58 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (!localDeclsDiff.empty()) {
What is the reason to have a new structure here? Why it does not work for arrays declared in loops? It is very unlikely somebody defines/allocates arrays within a loop. Is there a use case in particular? Otherwise we can just transform this into a diagnostic.

@parth-07, can we somehow support this without having to special-case it?

2022-12-21 08:05 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (auto CAT = dyn_cast<ArrayType>(Type)) {
```suggestion
    if (isa<ArrayType>(Type)) {
```

2022-12-21 08:05 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      }
```suggestion
    if (isa<ArrayType>(T) && !isa<IncompleteArrayType>(T)) {
        QualType adjointType =
            GetCladArrayOfType(QualType(T->getPointeeOrArrayElementType(),
                                        T->getIndexTypeCVRQualifiers()));
        return adjointType;
      }
```

2022-12-21 08:05 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (auto AT = dyn_cast<ArrayType>(E->getType())) {
```suggestion
    if (isa<ArrayType>(E->getType())) {
```
We will need to add an assertion in `getArraySizeExpr` if that was not an array type; and cast the type there.

2022-12-24 16:49 UTC, vgvassilev commented
@grimmmyshini ping.

2022-12-26 13:00 UTC, parth-07 commented on include/clad/Differentiator/Array.h
> +    this = arr.m_arr;
> First point - because I expect the overloaded operator CUDA_HOST_DEVICE array<T>& operator=(T* arr) to 
> be called there.

Then shouldn't the code be:
```cpp
*this = arr.m_arr;
```

2022-12-26 14:38 UTC, parth-07 commented
Hi @vgvassilev, Hi @grimmmyshini 

Thank you Garima for the detailed problem description and an initial solution to move forward with.

```cpp
// start of forward block
int n = k;
clad::array<double> _d_arr(n);
```

We perhaps should not rely on this technique even outside the loops because `k` here can be an arbitrarily complex expression and may also depend on runtime conditions. It may be infeasible to compute all of those before the forward block starts.

I do like the proposed fix involving `clad::array::reallocateSpaceForNewSize`. 

> Maybe we want to save every copy of the diff array declared in the previous example, and then we would probably 
> need something more sophisticated. Although in my opinion, this should not be necessary...

Yes, that should not be necessary. 

One drawback of this approach is that the derivative programs will consume more than required memory. If we can create local derivative variables in the derivative loops then that can solve this issue.

2022-12-26 14:50 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (auto CAT = dyn_cast<ConstantArrayType>(AT))
Can you please refactor this into a utility function `getArrayInit`?

2022-12-26 14:52 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (auto CAT = dyn_cast<ConstantArrayType>(AT))
Can you use, `getArraySizeExpr` function here?

2022-12-26 14:55 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +
Can you please add a comment here detailing that `VDDerivedInit` now serves two purposes -- as the initial derivative value or the size of the derivative array -- depending on the primal type.

2022-12-26 14:58 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (!localDeclsDiff.empty()) {
Hi @vgvassilev
I am not sure at the moment. I am trying to see how we can improve the existing design to handle the missing cases.

2022-12-26 15:00 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      addToCurrentBlock(
Why do we add derivative arrays in the current block? Can it cause issues in codes such as below:

```cpp
{
  int n = /*some random expression*/;
  double arr[n] = {....};
  res += arr[0] + arr[1];
}
```

2023-01-02 06:44 UTC, vgvassilev commented
@grimmmyshini ping!

2023-01-02 13:04 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (auto AT = dyn_cast<ArrayType>(Type)) {
This is not a valid suggestion on its own, we need the array type for the `getSizeExpr` function.

2023-01-02 13:08 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (auto CAT = dyn_cast<ArrayType>(Type)) {
This is not a valid suggestion on its own. We need the array type to get the underlying element type of the array.

2023-01-02 13:17 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      }
I can use the ```!isa<IncompleteArrayType>(T)``` instead of ```dyn_cast``` but I don't see how I can call ```ArrayType``` size expression functions through just an ```expr*``` without ever casting it.

2023-01-02 13:20 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (auto AT = dyn_cast<ArrayType>(E->getType())) {
Why? It adds two unnecessary checks instead of just one. Secondly, even if I do what you suggest I see no scenario in which ```getArraySizeExpr``` will see a non ```ArrayType```.

2023-01-02 13:21 UTC, grimmmyshini commented on include/clad/Differentiator/Array.h
> +    this = arr.m_arr;
true!

2023-01-02 13:33 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      addToCurrentBlock(
If the `{}` signify a different scope, then yes. I know this is a problem, but I don't know how to solve this because even currently, we have problems with variables declared in a different scope (having the lifetime of that scope) but are still used in the reverse pass. 

Maybe treat is the same as you would a loop? With something like ```isInsideDifferentScope```.

2023-01-02 13:35 UTC, grimmmyshini commented
> Hi @vgvassilev, Hi @grimmmyshini
> 
> Thank you Garima for the detailed problem description and an initial solution to move forward with.
> 
> ```c++
> // start of forward block
> int n = k;
> clad::array<double> _d_arr(n);
> ```
> 
> We perhaps should not rely on this technique even outside the loops because `k` here can be an arbitrarily complex expression and may also depend on runtime conditions. It may be infeasible to compute all of those before the forward block starts.

yeah sure you could have something weird like 

```
int k = 10;
double arr[++k];
```
but in my experience, these special conditions are super rare and not deterministic of the usual case where ```k``` would be a fairly constant variable. We could make a case to support these "weird" cases but I see absolutely no point in doing that when we don't have any use cases for that.

Secondly, coupling the size declaration and array derivative declaration was the most "natural" coupling I found. Maybe in the future, we want to exactly inline all derivative decls with actual decls but even then you will not be covered in weird cases (like the one above) :smiley:  

Any better ideas for implementing this are welcomed though. 

> I do like the proposed fix involving `clad::array::reallocateSpaceForNewSize`.
> 
> > Maybe we want to save every copy of the diff array declared in the previous example, and then we would probably
> > need something more sophisticated. Although in my opinion, this should not be necessary...
> 
> Yes, that should not be necessary.
> 
> One drawback of this approach is that the derivative programs will consume more than the required memory. If we can create local derivative variables in the derivative loops then that will reduce memory consumption.

True but then we need to remove these derivatives' usage in the reverse mode i.e. outside the scope of the original loop. Maybe it is worth considering this in a separate independent issue.

2023-01-02 13:39 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (auto CAT = dyn_cast<ConstantArrayType>(AT))
Yep, I missed converting this somehow.

2023-01-02 13:41 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +
okay

2023-01-02 13:46 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (auto AT = dyn_cast<ArrayType>(E->getType())) {
This way we reduce the cyclomatic code complexity and as for the size you can see the suggestion in https://github.com/vgvassilev/clad/pull/513/files#r1057265867

2023-01-02 13:46 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (auto CAT = dyn_cast<ArrayType>(Type)) {
`getPointeeOrArrayElementType` exists on clang::Type as well according to the documentation of clang. Is that not sufficient?

2023-01-02 13:46 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (auto AT = dyn_cast<ArrayType>(Type)) {
Fair enough, I thought the code might read better if `getArraySizeExpr` takes a type and asserts if it were not an array type. I don't have a strong opinion though.

2023-01-02 13:46 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      }
Both functions seem available in `clang::Type`.

2023-01-02 13:54 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (auto CAT = dyn_cast<ArrayType>(Type)) {
Ah, I did not realize that, sorry. Okay, I can make this change.

2023-01-02 13:56 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      }
Yes, okay.

2023-01-02 14:14 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (auto AT = dyn_cast<ArrayType>(E->getType())) {
Where are these two checks? If you mean that we will have a check outside of the function and then inside the function implementation then sure. However, the way I'd read this code is "hey we have a special case for arrays" and it's being taken care of in this utility function. Leaking a variable also makes the reader track what goes on in the utility function and outside - that's not to worry today but will have to worry tomorrow.

2023-01-02 14:16 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      }
um, could you point me to ```Type::getIndexTypeCVRQualifiers```, I don't think it is covered by ```Type```.

2023-01-02 14:26 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      }
Ah, yes, sorry, you are right. I will be happy if we use `!isa<IncompleteArrayType>(T)` at that point.

2023-01-02 14:35 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (auto AT = dyn_cast<ArrayType>(E->getType())) {
I disagree here. I think the dynamic cast provides a clear-er message and avoids redundant checks. However, we can move the cast inside if you like.

2023-01-02 14:37 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (auto AT = dyn_cast<ArrayType>(E->getType())) {
If that's an unambiguous code readability improvement for you then let's keep it as it is.

2023-01-02 14:41 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (auto AT = dyn_cast<ArrayType>(E->getType())) {
Okay, thanks!

2023-01-02 14:53 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      }
hmm, what do you suggest? Unfortunately, I do not remember the reason for using this exactly.

2023-01-02 14:55 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      }
I am not sure if the goal was to add back the qualifiers or something else. Let's hope this is covered by tests - I'd suggest to remove this and add `0` see if we have a failing test and take it from there. I suspect we might be able to use `ASTContext::getBaseElementType` to bring back the qualifiers.

2023-01-02 15:23 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      }
```ASTContext::getBaseElementType``` works well. I have added this and other changes.

2023-01-02 15:49 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      }
Maybe change the rest of the occurrences if any.

2023-01-02 19:12 UTC, grimmmyshini commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      }
Yes, I did that. I also squashed the changes from the round of reviews into one commit.

2023-01-03 19:36 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      addToCurrentBlock(
Yes, I meant when `{ }` signify a different scope. This is a considerable restriction. Variable-sized arrays can basically only be used in function global scope.

> even currently, we have problems with variables declared in a different scope (having the lifetime of that scope) but are still used in the reverse pass.

Yes, but these cases are rare within clad. We should ideally try to remove all such cases.

Can you please open an issue to track that variable-sized array cannot be used within a local scope?

2023-01-03 19:38 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        if (dyn_cast<VariableArrayType>(VD->getType()))
```suggestion
        if (isa<VariableArrayType>(VD->getType()))
```

2023-01-03 19:56 UTC, parth-07 commented
> but in my experience, these special conditions are super rare and not deterministic of the usual case where k would be a fairly constant variable. We could make a case to support these "weird" cases but I see absolutely no point in doing that when we don't have any use cases for that.

Yeah, makes sense. I misunderstood a few things before, and the approach seemed a lot more restrictive to me than it actually was.

> Secondly, coupling the size declaration and array derivative declaration was the most "natural" coupling I found.

Yes, it is definitely the most "natural" coupling. But there was a reason why we always declared derivative variables in the function's global scope. For instance, having size declaration and array derivative declaration in the same scope restricts the usage of variable-sized arrays to a function's global scope.

> Maybe in the future, we want to exactly inline all derivative decls with actual decls but even then you will not be covered in weird cases (like the one above) 😃

I am not sure if that's a good idea. I believe the example you showed can be easily made to work by using temporaries if the array size expression contains side effects. This would not be a big change. But yes, I don't think it's required right now.

> Any better ideas for implementing this are welcomed though.

I liked your idea of `clad::Array::reallocateSpaceForNewSize`. This solution is robust and can be uniformly used for functions' global and local scopes. It also does not have flaws present in the current solution. I do understand that
`clad::Array::reallocateSpaceForNewSize` solution might be more time-consuming, but we should definitely keep it in mind if we cannot find a better solution in the future.

> True but then we need to remove these derivatives' usage in the reverse mode i.e. outside the scope of the original loop.

In the reverse-pass, the derivative will only be used in the corresponding adjoint code in which it can ideally be declared to reduce memory consumption. Thus, we should be able to limit the scope in the reverse-pass.
One problem here is that we may need to access derivatives in the forward-pass, in some obscure cases such as when which variable a value is assigned to is only known at runtime. For example:

```cpp
fn(i, j, k) = val;
```

`fn(i, j, k)` can return any of `i`, `j` or `k`.

> Maybe it is worth considering this in a separate independent issue.

Yes, definitely.

2023-01-03 19:58 UTC, parth-07 approved these changes
Looks good.

2023-01-04 18:11 UTC, vgvassilev commented
@grimmmyshini, can you incorporate the last part of the suggestions? I think we are ready to go.

2023-01-05 08:14 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      addToCurrentBlock(
Do we have opened an issue for this?

2023-01-05 08:15 UTC, vgvassilev approved these changes
LGTM! Modulo the comment I left.

2023-01-05 08:21 UTC, grimmmyshini commented
> LGTM! Modulo the comment I left.

which one? I addressed the last one in the new commit.

2023-01-05 08:22 UTC, vgvassilev commented
> > LGTM! Modulo the comment I left.
> 
> which one? I addressed the last one in the new commit.

https://github.com/vgvassilev/clad/pull/513/files#r1062206538

2023-01-05 09:07 UTC, merged