Add API reference documentation
vgvassilev/clad pull request #528
Opened 2023-02-04 19:16 UTC by arora-vidushi

Add Clad API function examples.

2023-02-05 04:41 UTC, vgvassilev reviewed
Thanks @arora-vidushi for this PR, it mostly looks good to me (see comments).

2023-02-05 04:41 UTC, vgvassilev commented on docs/userDocs/source/user/reference.rst
> +                  CladFunction differentiate(Fn fn, const char* args)
Was this indentation change done on purpose?

2023-02-05 04:41 UTC, vgvassilev commented on docs/userDocs/source/user/reference.rst
> +         auto fn_dx = clad::differentiate(func, 0);
```suggestion
         auto fn_dx = clad::differentiate(func, "x");
```

2023-02-05 04:41 UTC, vgvassilev commented on docs/userDocs/source/user/reference.rst
> +         // Using CladFunction::execute method when (x, y)=(5,3)
```suggestion
         // Using CladFunction::execute method when (x, y) = (5, 3)
```

2023-02-05 04:41 UTC, vgvassilev commented on docs/userDocs/source/user/reference.rst
> +         int func1stOrderDerivative = fn_dx.execute(5,3);
Why `int` here?

2023-02-05 04:41 UTC, vgvassilev commented on docs/userDocs/source/user/reference.rst
> +         double d_i=0, d_j=0;
```suggestion
         double d_i = 0, d_j = 0;
```

2023-02-05 10:51 UTC, arora-vidushi commented on docs/userDocs/source/user/reference.rst
> +                  CladFunction differentiate(Fn fn, const char* args)
yes, It was looking better this way

2023-02-05 11:31 UTC, arora-vidushi commented on docs/userDocs/source/user/reference.rst
> +         int func1stOrderDerivative = fn_dx.execute(5,3);
Changed it to `double`

2023-02-05 14:11 UTC, parth-07 requested changes

2023-02-05 14:11 UTC, parth-07 commented on docs/userDocs/source/user/reference.rst
> +        double res[2] = {0};
This can result in undefined behaviour. The function `func` expects the `result` array to be of size 3.

2023-02-05 14:11 UTC, parth-07 commented on docs/userDocs/source/user/reference.rst
> +        double matrix_ref[6] = {0};
Since we are just passing an array here, and not `clad::array_ref`, can we just name it `matrix`?
We generally use `ref` suffix in examples when `clad::array_ref` is being used.

2023-02-05 14:11 UTC, parth-07 commented on docs/userDocs/source/user/reference.rst
>     the arguments specified in ``args``.
Can you please add information for the derivative behaviour when no `args` is specified?

2023-02-07 01:44 UTC, arora-vidushi commented on docs/userDocs/source/user/reference.rst
> +        double res[2] = {0};
Thanks for review. I have updated it.

2023-02-07 01:45 UTC, arora-vidushi commented on docs/userDocs/source/user/reference.rst
> +        double matrix_ref[6] = {0};
Done!

2023-02-07 21:22 UTC, arora-vidushi commented on docs/userDocs/source/user/reference.rst
>     the arguments specified in ``args``.
Done, please review

2023-02-07 21:31 UTC, parth-07 approved these changes

2023-02-08 00:22 UTC, merged