Remove dependency on LastKnowGood*.txt
vgvassilev/clad pull request #534
Opened 2023-02-24 19:54 UTC by Ris-Bali

This PR aims to remove dependency on LastKnowGoodClang/LLVM.txt files.

closes #523

2023-02-24 21:58 UTC, vgvassilev reviewed
Thanks for working on this! We should probably get rid of all `getClangCompatRevision` and friends as this becomes unused.

Could you update the commit message to include "Fixes #534" which would automatically close the relevant issue.

2023-02-25 18:26 UTC, parth-07 requested changes

2023-02-25 18:26 UTC, parth-07 commented on include/clad/Differentiator/Version.h
> -  std::string getCladRevision();
We still need to keep getCladRevision.

2023-02-25 18:37 UTC, Ris-Bali commented on include/clad/Differentiator/Version.h
> -  std::string getCladRevision();
Noted I will revert this

2023-02-26 06:00 UTC, parth-07 commented on tools/ClangPlugin.h
> -            if (!IsRunningOnExpectedClangVersion())
@vgvassilev Instead of removing this function call altogether, should we instead check if the supported Clang version is being used? I think Clad supports Clang 5 to Clang 15.

2023-02-26 06:43 UTC, vgvassilev commented on tools/ClangPlugin.h
> -            if (!IsRunningOnExpectedClangVersion())
Sure, but what happens if you compile from git? This has been a problem before but nowadays we can handle this indeed. So maybe we can check against the clang major version if it is between 5 and 15… 

Although these types of things have caused major troubles throughout years.

2023-02-26 14:36 UTC, parth-07 commented on tools/ClangPlugin.h
> -            if (!IsRunningOnExpectedClangVersion())
> Although these types of things have caused major troubles throughout years.

Yes, but I think now we have a good infrastructure to handle this. And also, this is only used if `-fvalidate-clang-version` is specified.

@Ris-Bali Can you please make this change? Max and minimum clang version supported values can be taken 
from the cmake variables `CLANG_MIN_SUPPORTED` and `CLANG_VERSION_UPPER_BOUND`. We will need to make them available to cpp files. Please let us know if you have any questions.

2023-02-28 08:02 UTC, Ris-Bali commented on tools/ClangPlugin.h
> -            if (!IsRunningOnExpectedClangVersion())
Apologies for the late reply,I have made both the variables available to the cpp files from where can I get the clang_version being used ? I couldn't find a variable for that . Thanks

2023-02-28 23:07 UTC, parth-07 commented on tools/ClangPlugin.h
> -            if (!IsRunningOnExpectedClangVersion())
Hi @Ris-Bali, you can use the macros `__clang__`, `__clang_major__` and `__clang__minor__` to determine
the clang version being used at runtime. These macros are documented here: [https://clang.llvm.org/docs/LanguageExtensions.html#feature_check](https://clang.llvm.org/docs/LanguageExtensions.html#feature_check)

2023-03-02 19:13 UTC, Ris-Bali commented
I have made the changes. Pls review them

2023-03-04 05:17 UTC, parth-07 requested changes

2023-03-04 05:17 UTC, parth-07 commented on tools/ClangPlugin.h
> +      __clang_minor__ <= CLANG_UPPER_MINOR))
Versions starting from `CLANG_VERSION_UPPER_BOUND` are not supported.
As per your conditions, a clang version matching the `CLANG_VERSION_UPPER_BOUND` is supported, when it's actually not supported.

2023-03-04 10:27 UTC, vgvassilev commented on tools/ClangPlugin.h
>            } else if (args[i] == "-fvalidate-clang-version") {
Now that we have a good check we should probably make this a default behavior that could be disabled with say `fno-validate-clang-version`?

2023-03-07 05:43 UTC, Ris-Bali commented on tools/ClangPlugin.h
>            } else if (args[i] == "-fvalidate-clang-version") {
Will work on this

2023-03-08 15:44 UTC, Ris-Bali commented
I have made the changes. Pls Review

2023-03-08 19:06 UTC, vgvassilev commented on tools/CMakeLists.txt
> +add_definitions( -DCLANG_MINIMUM_MINOR=${CLANG_MINIMUM_MINOR} )
Aren't these defined in `clang/Basic/Version.h`?

2023-03-08 19:31 UTC, Ris-Bali commented on tools/CMakeLists.txt
> +add_definitions( -DCLANG_MINIMUM_MINOR=${CLANG_MINIMUM_MINOR} )
Doesn't clang/Basic/Version.h give the CLANG_VERSION_MAJOR etc of the clang being used for the project ? The variables I have defined here are taken from CLANG_VERSION_UPPER_BOUND and CLANG_MIN variables in clad's CmakeLists.txt.

2023-03-08 21:14 UTC, parth-07 commented on tools/ClangPlugin.h
> +#if defined(__clang__)
Hi @Ris-Bali, 
Thank you very much for working on this.

It needs some modifications. I think we were wrong about a few things before.
@vgvassilev Please correct me if I am wrong somewhere.

The built `clad.so` does not support the complete `CLANG_MINIMUM_MAJOR` to `CLANG_UPPER_MAJOR`
range. This is because Clad contains many codes that are Clang version-specific. You can see the clang version-specific codes in `include/clad/Differentiator/Compatibility.h`. To fix this, validate clang version should check if the
currently running clang version is the same as the clang version that was used for building `clad.so`.

Another issue is how to get the clang version of the currently running clang? I know I previously suggested using `__clang__*` macros. I was wrong. These macros are evaluated to the version of the Clang that is used to build Clad.
We need to determine the version of Clang at runtime. The following functions may help to determine the value of the
runtime clang version being used to run Clad:
- `clang::getClangRevision`
- `clang::getClangFullVersion`
- `clang::getClangFullCPPVersion`.

@Ris-Bali Can you please verify that these functions indeed give the runtime Clang version, and not the clang used
to build Clad?

2023-03-18 18:27 UTC, Ris-Bali commented on tools/ClangPlugin.h
> +#if defined(__clang__)
Yes the getclangFullCPPVersion() and getClangFullVersion() give similar outputs and give the runtime version of clang , getclangRev

![image](https://user-images.githubusercontent.com/81592570/226126437-f3e0770c-131b-4904-b74f-a9401ba5f08a.png)

So next should I compare them with __clang__version_ macro ? It is a combination of clang_major, clang_minor and clang_patchlevel_ macros and should give the version with which clad was built?

2023-03-19 12:19 UTC, Ris-Bali commented on tools/ClangPlugin.h
> +#if defined(__clang__)
I have made the changes. Pls review. I think the tests are failing because of using a different version runtime ?

2023-04-04 18:44 UTC, Ris-Bali commented
I have reverted the version check so that it is not default behavior anymore; If I make it default behavior half the tests (with different clang version at runtime) fail. So should I keep it default or is this fine ?

2023-04-05 08:38 UTC, vgvassilev commented
Can you squash the commits into one? We should open a new issue which suggests enabling `-fvalidate-clang-version` by default. I am not sure I understand why the builders are failing if we do it.

2023-04-05 11:20 UTC, Ris-Bali commented
> Can you squash the commits into one? We should open a new issue which suggests enabling `-fvalidate-clang-version` by default. I am not sure I understand why the builders are failing if we do it.

Sure I'll squash the commits.

2023-04-05 11:25 UTC, Ris-Bali commented
Correct me if I am wrong; I think the builders are failing when we keep this as default behavior because we use different clang version for building clad and different clang version at runtime. (eg : clang8-runtime 10 ) will fail as the clang version used to build clad and the clang version at runtime are different. Meanwhile builders which use the same version are not failing (eg clang 9-runtime 9)

2023-04-05 11:54 UTC, vgvassilev commented
Yes, you are right. In that case, however, the clad version macros should capture not which compiler has built the binary but what was the target runtime. That is, what is the version of clang used as a library for clad to link against. We have these values in cmake already.

2023-04-06 22:21 UTC, parth-07 approved these changes
Thank you @Ris-Bali for working on this. LGTM.

2023-04-07 04:43 UTC, vgvassilev commented
> Yes, you are right. In that case, however, the clad version macros should capture not which compiler has built the binary but what was the target runtime. That is, what is the version of clang used as a library for clad to link against. We have these values in cmake already.

I think this is what we want. We should get the version of the runtime clad was build for and not who built it. For example we build with gcc, what would we do there if we pursue this approach?

2023-04-07 22:10 UTC, Ris-Bali commented
> > Yes, you are right. In that case, however, the clad version macros should capture not which compiler has built the binary but what was the target runtime. That is, what is the version of clang used as a library for clad to link against. We have these values in cmake already.
> 
> I think this is what we want. We should get the version of the runtime clad was build for and not who built it. For example we build with gcc, what would we do there if we pursue this approach?

Understood I'll use the variables defined in cmake

2023-04-08 15:11 UTC, vgvassilev commented on tools/CMakeLists.txt
> +add_definitions( -DCLANG_FULL_VERSION="${CLANG_VERSION_MAJOR}.${CLANG_VERSION_MINOR}.${CLANG_VERSION_PATCH}" )
We should define this only for the cpp file and move the check into a routine that’s defined there.

2023-04-09 10:16 UTC, Ris-Bali commented on tools/CMakeLists.txt
> +add_definitions( -DCLANG_FULL_VERSION="${CLANG_VERSION_MAJOR}.${CLANG_VERSION_MINOR}.${CLANG_VERSION_PATCH}" )
I've made the changes now CLANG_FULL_VERSION can only be accessed by clangplugin.h. Could you please clarify what do you mean by moving the check into a routine. I couldn't understand that part of your request

2023-04-09 10:49 UTC, vgvassilev commented on tools/CMakeLists.txt
> +add_definitions( -DCLANG_FULL_VERSION="${CLANG_VERSION_MAJOR}.${CLANG_VERSION_MINOR}.${CLANG_VERSION_PATCH}" )
I meant something like `set_source_files_properties(ClangPlugin.cpp PROPERTIES COMPILE_DEFINITIONS "CLANG_FULL_VERSION=\"${CLANG_FULL_VERSION}\"")`

2023-04-09 12:25 UTC, Ris-Bali commented on tools/CMakeLists.txt
> +add_definitions( -DCLANG_FULL_VERSION="${CLANG_VERSION_MAJOR}.${CLANG_VERSION_MINOR}.${CLANG_VERSION_PATCH}" )
Thanks for the reply. I think there is no other way other than creating a separate header file through configure_file() if we need to access a cmake variable in a header file (here ClangPlugin.h) As mentioned [here](https://discourse.cmake.org/t/how-to-get-access-cmake-variable-in-a-header-file/7125) .  I have tested this personally too and got an error.

2023-04-09 12:30 UTC, vgvassilev commented on tools/ClangPlugin.h
> +            return false;
I'd propose to move this code in a routine called `CheckCladVersion` or similar in ClangPlugin.cpp and call it from here. There you need to add in the CMakeLists.txt `set_source_files_properties(ClangPlugin.cpp PROPERTIES COMPILE_DEFINITIONS "CLANG_VERSION_MAJOR=\"${CLANG_VERSION_MAJOR}\"")` to expose the necessary macro.

2023-04-09 12:32 UTC, Ris-Bali commented on tools/ClangPlugin.h
> +            return false;
Okay thanks understood.

2023-04-10 09:59 UTC, Ris-Bali commented
I've made the requested changes and squashed the commit. Pls review.

2023-04-10 16:42 UTC, vgvassilev commented on tools/CMakeLists.txt
> +set_source_files_properties(ClangPlugin.cpp PROPERTIES COMPILE_DEFINITIONS CLANG_MAJOR_VERSION="${CLANG_VERSION_MAJOR}.")
```suggestion
set_source_files_properties(ClangPlugin.cpp PROPERTIES COMPILE_DEFINITIONS CLANG_MAJOR_VERSION="${CLANG_VERSION_MAJOR}")
```

2023-04-10 16:42 UTC, vgvassilev commented on tools/ClangPlugin.h
> +        if(checkClangVersion() == 0)
```suggestion
        if (!checkClangVersion()) 
```

2023-04-10 20:11 UTC, vgvassilev approved these changes
LGTM! Please run git-clang-format on this patch and I can merge it in.

2023-04-11 02:09 UTC, merged