Add initial basic support for vectorized forward mode AD
vgvassilev/clad pull request #565
Opened 2023-05-29 09:49 UTC by vaithak

This PR adds support for vectorized forward mode for arithmetic functions. 

Minimal working example: 
```cpp
double f(double x, double y) {
  return x*y;
}

int main() {
  auto f_dx = clad::differentiate<clad::opts::vector_fwd_mode>(f);
  double dx = 0, dy = 0;
  f_dx.execute(/*x=*/3, /*y=*/4, &dx, &dy);
  std::cout << "dx: " << dx << ' ' << "dy: " << dy << std::endl;
  
  // Dump the generated derivative code to standard output.
  f_dx.dump();
}
``` 

Corresponding output:
```bash
dx: 4 dy: 3
The code is: 
void f_d_all_args(double x, double y, clad::array_ref<double> _d_x, clad::array_ref<double> _d_y) {
    clad::array<double> _d_vector_x = {1, 0};
    clad::array<double> _d_vector_y = {0, 1};
    {
        clad::array<double> _d_vector_return = _d_vector_x * y + x * _d_vector_y;
        * _d_x = _d_vector_return[0];
        * _d_y = _d_vector_return[1];
    }
}
```

2023-05-29 19:15 UTC, vaithak commented
Hi, I need some help with the falling test cases; the test is failing for Clang 15 because it is generating extra pragmas related to floating point arithmetic with the code:
```cpp
void f1_d_all_args(double x, double y, clad::array_ref<double> _d_x, clad::array_ref<double> _d_y) { 
   clad::array<double> _d_vector_x = {1, 0}; 
   clad::array<double> _d_vector_y = {0, 1}; 
   { 
        #pragma clang fp exceptions() 
        #pragma STDC FENV_ROUND FE_DYNAMIC 
        clad::array<double> _d_vector_return = _d_vector_x * y + x * _d_vector_y; 
        * _d_x = _d_vector_return[0]; 
        * _d_y = _d_vector_return[1]; 
    } 
} 
```
Do you have any ideas or suggestions as to what I am missing here and how this can be fixed?

2023-05-29 19:49 UTC, vgvassilev commented
I remember we needed some adjustments in the recent clang versions for floating point arithmetic in our compatibility layer. Could you build llvm in debug and set a breakpoint at the time the pragma is produced. 

Cc: @alexander-penev

2023-05-31 07:08 UTC, vaithak commented
Thanks for the help, @vgvassilev, using [the custom defined function](https://github.com/vgvassilev/clad/blob/master/include/clad/Differentiator/Compatibility.h#L64) fixed the tests 👍🏼

2023-06-04 07:14 UTC, parth-07 requested changes
Initial review.

2023-06-04 07:14 UTC, parth-07 commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE array<T> operator*(T n) {
Can it be a `const` member function?

2023-06-04 07:14 UTC, parth-07 commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE friend array<T> operator*(T n, array<T>& arr) {
Can we pass `arr` as a const reference instead? If yes, then please make changes in all such operator overloads.

2023-06-04 07:14 UTC, parth-07 commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE friend array<T> operator+(array<T>& arr1, array<T>&& arr2) {
Why do you have overloads that differ in the parameters `array<T> &arr2` and `array<T> &&arr2`?

2023-06-04 07:14 UTC, parth-07 commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE friend array<T> operator+(array<T>&& arr1, array<T>&& arr2) {
Can you please explain why overloads for rvalue references are beneficial here? You are not moving any value
within the function body.

2023-06-04 07:14 UTC, parth-07 commented on include/clad/Differentiator/Differentiator.h
> +      annotate("D")))
`annotate("D")` is used to recognize the differentiation mode. We should have different differentiation mode for ordinary forward and vector forward mode.

2023-06-04 07:16 UTC, parth-07 commented
@vaithak How can a user request for 4th order differentiation using vector forward mode? It seems that
`clad::opts::vector_fwd_mode` and differentiation order shares the same template parameter.

2023-06-04 09:58 UTC, vaithak commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE array<T> operator*(T n) {
fixed 👍🏼

2023-06-04 09:59 UTC, vaithak commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE friend array<T> operator*(T n, array<T>& arr) {
changed in all such operator overloads 👍🏼

2023-06-04 10:07 UTC, vaithak commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE friend array<T> operator+(array<T>&& arr1, array<T>&& arr2) {
Yeah, my bad. I have fixed this by making changes in the rvalue reference itself.

2023-06-04 10:09 UTC, vaithak commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE friend array<T> operator+(array<T>& arr1, array<T>&& arr2) {
This is mainly used for cascaded operations. For ex. `clad::array<double> d = a+b+c`, where `a, b, c` are also clad arrays.

2023-06-04 10:36 UTC, vaithak commented
Hi @parth-07, vector forward mode will calculate derivative w.r.t all parameters. Ideally, this should mean calculating the Hessian matrix for n=2 and similarly for other higher-order derivatives. So, I think N>1 won't make much sense for vector fwd mode.

2023-06-04 10:36 UTC, vaithak commented on include/clad/Differentiator/Differentiator.h
> +      annotate("D")))
commented below about the reasoning for this.

2023-06-04 13:23 UTC, parth-07 requested changes

2023-06-04 13:23 UTC, parth-07 commented on lib/Differentiator/ForwardModeVisitor.cpp
> +      ValueType.removeLocalConst();
What if the original type is a reference type?

2023-06-04 13:23 UTC, parth-07 commented on lib/Differentiator/ForwardModeVisitor.cpp
> +        auto it = m_VectorVariables.find(VD);
Is there any use of `m_Variables` in vector forward mode?

2023-06-04 13:41 UTC, parth-07 commented
> Hi @parth-07, vector forward mode will calculate derivative w.r.t all parameters. This should mean calculating the Hessian matrix for n=2 and similarly for other higher-order derivatives. So, I think N>1 won't make much sense for vector fwd mode. 

Hi @vaithak
Yes, vector forward mode will compute derivatives w.r.t all the parameters. For a second-order differentiation, wouldn't this mean computing the diagonal of the Hessian matrix instead of the matrix itself? We already have a requirement for such a case: issue #509. 

We shouldn't use the same function template parameter for entirely different use cases, even if we do not wish to support higher-order differentials for vector forward mode. We can use a different function altogether for vector forward mode, `clad::VectorForwardDifferentiation`. @vgvassilev @vaithak  What do you think about this?

2023-06-04 16:04 UTC, vgvassilev commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE friend array<T> operator*(T n, array<T>&& arr) {
Yes, please run `git-clang-format` to this patch.

2023-06-05 09:12 UTC, vaithak commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE friend array<T> operator+(array<T>& arr1, array<T>&& arr2) {
removed all rvalue reference functions for now to keep this simple, will add them later if required.

2023-06-05 09:12 UTC, vaithak commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE friend array<T> operator+(array<T>&& arr1, array<T>&& arr2) {
removed rvalue reference function 👍🏼

2023-06-05 09:13 UTC, vaithak commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE friend array<T> operator*(T n, array<T>&& arr) {
ran `git-clang-format` and added spaces between functions 👍🏼

2023-06-05 09:13 UTC, vaithak commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE friend array<T> operator+(T n, array<T>&& arr) {
removed 👍🏼

2023-06-05 09:14 UTC, vaithak commented on include/clad/Differentiator/ForwardModeVisitor.h
> +    /// Get an expression used to initialize the one-hot vector for the
explained in comments 👍🏼

2023-06-05 09:14 UTC, vaithak commented on lib/Differentiator/ForwardModeVisitor.cpp
> +                                       m_Function->getLocation());
passed `noLoc` 👍🏼

2023-06-05 09:14 UTC, vaithak commented on lib/Differentiator/ForwardModeVisitor.cpp
> +      ValueType.removeLocalConst();
wouldn't `utils::GetValueType` take care of that?

2023-06-05 09:15 UTC, vaithak commented on lib/Differentiator/ForwardModeVisitor.cpp
> +        auto it = m_VectorVariables.find(VD);
yup, `m_Variables` is for storing the mapping from original function parameters to new parameters for derivatives.

2023-06-05 09:18 UTC, vaithak commented
> > Hi @parth-07, vector forward mode will calculate derivative w.r.t all parameters. This should mean calculating the Hessian matrix for n=2 and similarly for other higher-order derivatives. So, I think N>1 won't make much sense for vector fwd mode.
> 
> Hi @vaithak Yes, vector forward mode will compute derivatives w.r.t all the parameters. For a second-order differentiation, wouldn't this mean computing the diagonal of the Hessian matrix instead of the matrix itself? We already have a requirement for such a case: issue #509.
> 
> We shouldn't use the same function template parameter for entirely different use cases, even if we do not wish to support higher-order differentials for vector forward mode. We can use a different function altogether for vector forward mode, `clad::VectorForwardDifferentiation`. @vgvassilev @vaithak What do you think about this?

I think this makes sense, will think more about this and let you know if I find some edge cases otherwise will add the new method for vector mode as you suggested.

2023-06-07 09:40 UTC, vaithak commented
@parth-07 I have created a new function for `clad::vector_forward_differentiate` instead of having an `opts` 👍🏼

2023-06-07 14:05 UTC, vaithak commented on lib/Differentiator/ForwardModeVisitor.cpp
> +              "Vector mode supports differentiating w.r.t. all parameters only.");
created an issue: https://github.com/vgvassilev/clad/issues/566

2023-06-07 19:52 UTC, parth-07 commented on lib/Differentiator/ForwardModeVisitor.cpp
> +      ValueType.removeLocalConst();
Oh, yes, It would.

2023-06-07 20:56 UTC, parth-07 requested changes

2023-06-07 20:56 UTC, parth-07 commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE friend array<T> operator+(const array<T>& arr1,
Why does it need to be a friend function? It does not seem to be accessing any private/protected members.
Also, what do you think about moving the operators outside the class?

2023-06-07 20:56 UTC, parth-07 commented on include/clad/Differentiator/FunctionTraits.h
> +    using type = typename std::add_pointer<R>::type;
Will it be correct if the return type is a `const` type?

2023-06-08 08:59 UTC, vaithak commented on include/clad/Differentiator/Array.h
> +      : m_arr(new T[arr.size()]{static_cast<T>(T())}), m_size(arr.size()) {
I followed the convention as it is done for other constructors of this class.

2023-06-08 10:32 UTC, vaithak commented on include/clad/Differentiator/Array.h
> +  CUDA_HOST_DEVICE friend array<T> operator+(const array<T>& arr1,
shifted most of the overloaded operators outside the class.

2023-06-08 10:32 UTC, vaithak commented on include/clad/Differentiator/FunctionTraits.h
> +    using type = typename std::add_pointer<R>::type;
yup, it works even if return type is `const double` for example

2023-06-10 10:51 UTC, vgvassilev commented on test/ForwardMode/VectorMode.C
> +void f1_d_all_args(double x, double y, double *_d_x, double *_d_y);
Could we extend the test cases? We should probably add a demo (in the demos folder). We should also document the new feature and interface in the documentation under `docs`.

2023-06-10 10:52 UTC, vgvassilev commented on test/ForwardMode/VectorMode.C
> +void f1_d_all_args(double x, double y, double *_d_x, double *_d_y);
Could we extend the test cases? We should probably add a demo (in the demos folder). We should also document the new feature and interface in the documentation under `docs`.

2023-06-10 11:51 UTC, vaithak commented on test/ForwardMode/VectorMode.C
> +void f1_d_all_args(double x, double y, double *_d_x, double *_d_y);
Sure, I will add it in follow-up PRs when the implementation is a little stable for some decently complex programs.

2023-06-10 12:01 UTC, vgvassilev commented on test/ForwardMode/VectorMode.C
> +void f1_d_all_args(double x, double y, double *_d_x, double *_d_y);
According to codecov this PR needs more tests to reach 100% coverage. I don’t think we need complex examples but examples good enough to test all new code that we have.

2023-06-11 12:28 UTC, vaithak commented on test/ForwardMode/VectorMode.C
> +void f1_d_all_args(double x, double y, double *_d_x, double *_d_y);
added more test cases 👍🏼

2023-06-12 06:43 UTC, vgvassilev commented on include/clad/Differentiator/Array.h
> +  array<T> arr2(arr);
Do we need an extra allocation here? Can we use `array_ref`?

2023-06-12 06:43 UTC, vgvassilev commented on include/clad/Differentiator/Array.h
> +  array<T> arr2(arr);
Likewise.

2023-06-12 09:12 UTC, vaithak commented on include/clad/Differentiator/Array.h
> +  array<T> arr2(arr);
The objective of this function is to return a new array (with multiplied entries),  if we use array_ref, won't `arr`'s underlying array also get modified? 
Also, if a new array is needed to be returned, won't it anyway require allocating a new array?

2023-06-12 23:32 UTC, parth-07 approved these changes
Overall looks good. Can you please squash all the commits into one?

2023-06-13 09:38 UTC, vaithak commented
created a single commit 👍🏼

2023-06-13 12:42 UTC, vaithak commented on include/clad/Differentiator/Array.h
> +  array<T> arr2(arr);
This overloaded operator is outside the class definition, so we can't use `m_arr` here.

2023-06-15 05:53 UTC, vaithak commented on include/clad/Differentiator/Array.h
> +  array<T> arr2(arr);
@vgvassilev, can we mark this as resolved?

2023-06-15 11:27 UTC, vgvassilev commented on include/clad/Differentiator/Array.h
> +  array<T> arr2(arr);
Yep, thanks for clarifying!

2023-06-15 11:28 UTC, merged