Add instructions for building docs
vgvassilev/clad pull request #567
Opened 2023-06-10 15:56 UTC by Ris-Bali

2023-06-10 15:57 UTC, Ris-Bali commented
Should I add a section to install sphinx i.e. link to sphinx's installation instructions website ?

2023-06-14 09:06 UTC, vgvassilev commented
Could you squash all commits into one?

2023-06-15 20:20 UTC, parth-07 requested changes

2023-06-15 20:20 UTC, parth-07 commented on docs/userDocs/source/user/DevelopersDocumentation.rst
> +The following cmake command should be used to build clad along with its
```suggestion
The following CMake command should be used to build clad along with its 
```

2023-06-15 20:20 UTC, parth-07 commented on docs/userDocs/source/user/DevelopersDocumentation.rst
> +Make sure you have installed `sphinx` before building clad with documentation.
This does not answer which sphinx version the user needs. What about other Python dependencies? Can we add
a requirements.txt file in the repository for managing python dependencies?

2023-06-16 13:39 UTC, Ris-Bali commented on docs/userDocs/source/user/DevelopersDocumentation.rst
> +Make sure you have installed `sphinx` before building clad with documentation.
1) Worked with the latest sphinx version for me should I add the minimum sphinx version required to build the docs ? will need to figure how to find that out

2) I tried adding a requirements.txt file by using the `pipreqs  /path/to/project` command but the file was empty  will try to create the file manually

2023-06-16 20:01 UTC, parth-07 commented on docs/userDocs/source/user/DevelopersDocumentation.rst
> +Make sure you have installed `sphinx` before building clad with documentation.
> The latest sphinx version worked for me

The latest version will change over time :).

> should I add the minimum sphinx version required to build the docs ? will need to figure how to find that out

requirements.txt in the repository should be enough. You can mention in the docs that all the dependencies can be installed as `pip install -r requirements.txt`

> I tried adding a requirements.txt file by using the pipreqs  /path/to/project command but the file was empty will try to create the file manually

Do not create this file manually. The typical way of creating this is as follows:
- Create a virtual environment and source it.
- Install required dependencies.
- Create requirements file using `pip freeze > requirements.txt`

2023-06-19 15:15 UTC, Ris-Bali commented
I have added the requirements.txt for sphinx and also I have added installation instructions to install doxygen to build internal docs. Please review

2023-06-19 21:27 UTC, parth-07 commented on docs/userDocs/source/user/DevelopersDocumentation.rst
> +Make sure you have installed `doxygen` to build the internal documentation :
```suggestion
Make sure `doxygen` is installed if you want to build the internal documentation: 
```

2023-06-19 21:27 UTC, parth-07 commented on docs/userDocs/source/user/DevelopersDocumentation.rst
> +The following CMake command should be used to build clad along with its
```suggestion
To build clad and its documentation, use the following CMake command:
```

2023-06-19 21:27 UTC, parth-07 commented on docs/userDocs/source/user/DevelopersDocumentation.rst
> +  make sphinx-clad
Can you add where users can find the build documentation?

Also, can they build just doxygen documentation or just sphinx documentation?
Does the `sphinx-clad` target by default builds both the documentation?

2023-06-19 21:31 UTC, parth-07 commented on docs/userDocs/source/user/DevelopersDocumentation.rst
> +The following command should be used to get all the dependencies to build documentation using `sphinx` :
```suggestion
Please use the project's `requirements.txt` file to install Python dependencies. This will also install the correct
version of sphinx.
```

2023-06-25 04:26 UTC, Ris-Bali commented
I have made the changes. Pls review

2023-06-25 05:47 UTC, vgvassilev approved these changes

2023-06-25 05:47 UTC, vgvassilev commented
LGTM but let’s wait for @parth-07

2023-06-29 20:39 UTC, vgvassilev commented
@parth-07, ping.

2023-07-01 21:45 UTC, parth-07 approved these changes
Looks good to me.

2023-07-01 22:20 UTC, merged