Add support for non_differentiable attribute
vgvassilev/clad pull request #568
Opened 2023-06-13 23:25 UTC by PhrygianGates

This PR add support for non_differentiable attribute.

2023-06-15 20:28 UTC, parth-07 requested changes
Initial review.

2023-06-15 20:28 UTC, parth-07 commented on .gitignore
> +/workspace
Can you please add these files to your local .gitignore? If you think these git ignores are useful
for many other people as well, then can you please open a separate pull request to add these to .gitignore?

2023-06-15 20:28 UTC, parth-07 commented on lib/Differentiator/DerivativeBuilder.cpp
> +    if (Attr && Attr->getAnnotation() == "non_differentiable") {
We should not just skip this. We should report an error, if a user has explicitly requested to differentiate a non-differentiable marked function.

2023-06-15 20:28 UTC, parth-07 commented on lib/Differentiator/ForwardModeVisitor.cpp
> +        if (auto* typeDecl = VD->getType()->getAsCXXRecordDecl()) {
Wouldn't all the variables in a declaration statement be of the same type? If so, can this be moved outside the loop?

2023-06-15 20:28 UTC, parth-07 commented on lib/Differentiator/ForwardModeVisitor.cpp
> +            decls.push_back(VD);
Where is these decls values used?

2023-06-20 10:56 UTC, PhrygianGates commented on .gitignore
> +/workspace
okay I'll do that

2023-06-20 10:58 UTC, PhrygianGates commented on lib/Differentiator/DerivativeBuilder.cpp
> +    if (Attr && Attr->getAnnotation() == "non_differentiable") {
ok

2023-06-20 10:59 UTC, PhrygianGates commented on lib/Differentiator/ForwardModeVisitor.cpp
> +        if (auto* typeDecl = VD->getType()->getAsCXXRecordDecl()) {
I think so, this can be moved outside.

2023-06-20 11:08 UTC, PhrygianGates commented on lib/Differentiator/ForwardModeVisitor.cpp
> +            decls.push_back(VD);
I think they are used later in line 1666.

2023-06-20 21:32 UTC, PhrygianGates commented on lib/Differentiator/ForwardModeVisitor.cpp
> +    if (const CXXMethodDecl* MD = dyn_cast<CXXMethodDecl>(m_Function)) {
We have reviewed all free functions in the `DerivativeBuilder::Derive` method. Upon reflection, I believe it may be more efficient to transfer the code from `ForwardModeVisitor::Derive` to `DerivativeBuilder::Derive`.

Checking for 'differentiable' in the `visit` function call methods seems impractical, given that an `CallExpr` won't frequently appear in the AST. We would only use the `VisitCallExpr` function when another function is invoked within this function. Consider the following example:

```cpp
double mem_fn_3(double i, double j)  { 
  SimpleFunctions obj(2, 3);
  return obj.mem_fn(i, j) + i*j; 
}
```

In this case, the `VisitCallExpr` function is used because `obj.mem_fn(i, j)` is a function call within `mem_fn_3`.

2023-06-22 21:40 UTC, parth-07 requested changes
Overall looks good.

2023-06-22 21:40 UTC, parth-07 commented on lib/Differentiator/ForwardModeVisitor.cpp
> +    // If the function is non_differentiable, return zero derivative.
Please refactor this whole code to be more modular. For example:
```cpp
if (HasNonDifferentiableAttribute(fn))
  return {Clone(CE), utils::getZero(...)};
```

2023-06-22 21:40 UTC, parth-07 commented on test/ForwardMode/NonDifferentiable.C
> +#define TEST_CLASS(classname, name, i, j)                                      \
Instead of creating new macros, can you please see if testing utility macros in `test/TestUtils.h` can be reused here?

2023-06-22 21:40 UTC, parth-07 commented on test/ForwardMode/NonDifferentiable.C
> +  non_differentiable double mem_fn_2(double i, double j) { return i * j; }
Can you please add a test where a non-differentiable function is being multiplied by another function and a variable?

2023-06-22 21:40 UTC, parth-07 commented on lib/Differentiator/DerivativeBuilder.cpp
> +    if (const CXXMethodDecl* MD = dyn_cast<CXXMethodDecl>(FD)) {
What do you think about adding a general function, `hasNonDifferentiableAttribute`, that can be used on any kind of declaration?

2023-06-26 23:52 UTC, PhrygianGates commented on lib/Differentiator/ForwardModeVisitor.cpp
> +        if (auto* typeDecl = VD->getType()->getAsCXXRecordDecl()) {
Understood. Given that all variables within a single declaration statement can only have the same attribute, I have optimized the code to check only the first element in each declaration statement.

2023-06-26 23:55 UTC, PhrygianGates commented on test/ForwardMode/NonDifferentiable.C
> +#define TEST_CLASS(classname, name, i, j)                                      \
After reviewing the code in test/TestUtils.h, I guess the macros there cannot be reused in this context. Those macros are specifically designed for free functions, whereas our requirement is to use class methods.

2023-06-26 23:56 UTC, PhrygianGates commented on test/ForwardMode/NonDifferentiable.C
> +  non_differentiable double mem_fn_2(double i, double j) { return i * j; }
yeah, already done

2023-06-26 23:56 UTC, PhrygianGates commented on lib/Differentiator/DerivativeBuilder.cpp
> +    if (const CXXMethodDecl* MD = dyn_cast<CXXMethodDecl>(FD)) {
already done

2023-06-29 18:09 UTC, parth-07 commented on lib/Differentiator/ForwardModeVisitor.cpp
> +        if (auto* typeDecl = VD->getType()->getAsCXXRecordDecl()) {
Great!

2023-06-29 18:29 UTC, parth-07 commented on test/ForwardMode/NonDifferentiable.C
> +#define TEST_CLASS(classname, name, i, j)                                      \
Okay, got it.

2023-06-29 18:30 UTC, parth-07 commented on test/ForwardMode/NonDifferentiable.C
> +  non_differentiable double mem_fn_2(double i, double j) { return i * j; }
Can you please tell me which function in the test file adds this test case?

2023-06-29 18:31 UTC, vgvassilev reviewed
We should try to add tests for the cases codecov reports.

2023-06-29 18:34 UTC, parth-07 requested changes

2023-06-29 18:34 UTC, parth-07 commented on lib/Differentiator/DerivativeBuilder.cpp
> +    if (const CXXMethodDecl* MD = dyn_cast<CXXMethodDecl>(FD)) {
Okay, then why are we not using such a function here and other places?

2023-06-29 18:34 UTC, parth-07 commented on lib/Differentiator/DerivativeBuilder.cpp
> +    if (Attr && Attr->getAnnotation() == "non_differentiable") {
Can you please add a test case in which a user tries to request a derivative of a function (using `clad::differentiate`) that is explicitly marked as `non_differentiable`?

2023-06-29 18:34 UTC, parth-07 commented on lib/Differentiator/ForwardModeVisitor.cpp
> +      auto* Attr = ME->getMemberDecl()->getAttr<clang::AnnotateAttr>();
Can we replace this whole code with something much more modular and readable such as:

```cpp
if (hasNonDifferentiableAttr(ME))
  return {clonedME, zero};
```

2023-06-29 18:40 UTC, parth-07 commented on lib/Differentiator/DerivativeBuilder.cpp
> +             "attempted differentiation of method '%0' in class '%1', which is "
Just to make sure, this would only produce an error if a user has explicitly requested derivative of a non-differentiable function, right? In particular, it should not produce an error if a non-differentiable function is being used in an another differentiable function.

For example:

```cpp
non_differentiable double nondiff_fn() { ... }
double diff_fn() { ...; nondiff_fn(); ...}

int main() {
  auto nondiff_fn_diff = clad::differentiate(nondiff_fn, ...); // This should produce an error.
  auto diff_fn_diff = clad::differentiate(diff_fn, ..); // This should not produce any error
}
```

2023-06-29 18:42 UTC, parth-07 commented on lib/Differentiator/ForwardModeVisitor.cpp
> +      if (clad::utils::hasNonDifferentiableAttribute(ME->getMemberDecl())) {
Can we check non differentiable attribute in both the member and the class in one function call, `clad::utils::hasNonDifferentiableAttribute(ME)`?

2023-06-29 18:46 UTC, parth-07 commented on lib/Differentiator/ForwardModeVisitor.cpp
> +    if (const auto* ME = dyn_cast<CXXMemberCallExpr>(CE)) {
The if condition for `clad::utils::hasNonDifferentiableAttribute(FD)` and `clad::utils::hasNonDifferentiableAttribute(classType)` seems pretty much same. Can we reuse the code?

Also, if a class has a non_differentiable attribute, then should the `clad::utils::hasNonDifferentiableAttribute(FD)` function return true for the corresponding member functions of the class?

2023-06-29 18:47 UTC, parth-07 commented on lib/Differentiator/ForwardModeVisitor.cpp
> +      auto* Attr = ME->getMemberDecl()->getAttr<clang::AnnotateAttr>();
This has already been fixed it seems.

2023-07-01 21:40 UTC, PhrygianGates commented on lib/Differentiator/DerivativeBuilder.cpp
> +             "attempted differentiation of method '%0' in class '%1', which is "
Yes! that complies with what I have implemented, and is included in the existing tests. 
In NonDifferentiable.C, we have the following code:

```C++
class SimpleFunctions1 {
public:
  SimpleFunctions1() noexcept : x(0), y(0) {}
  SimpleFunctions1(double p_x, double p_y) noexcept : x(p_x), y(p_y) {}
  double x;
  non_differentiable double y;
  double mem_fn_1(double i, double j) { return (x + y) * i + i * j * j; }
  non_differentiable double mem_fn_2(double i, double j) { return i * j; }
  double mem_fn_3(double i, double j) { return mem_fn_1(i, j) + i * j; }
  double mem_fn_4(double i, double j) { return mem_fn_2(i, j) + i * j; }
  double mem_fn_5(double i, double j) { return mem_fn_2(i, j) * mem_fn_1(i, j) * i; }
  SimpleFunctions1 operator+(const SimpleFunctions1& other) const {
    return SimpleFunctions1(x + other.x, y + other.y);
  }
};
```

The function `mem_fn_5` calls `mem_fn_2` and can be differentiated.

2023-07-01 21:46 UTC, parth-07 commented on lib/Differentiator/DerivativeBuilder.cpp
> +             "attempted differentiation of method '%0' in class '%1', which is "
Okay, thank you for the information.

2023-07-03 23:17 UTC, PhrygianGates commented
Hi! I've added tests for error cases, but it appears that others have also modified the ForwardModeVisitor.cpp file. I am currently working on updating my code to fit the new code structure.

2023-07-04 10:52 UTC, PhrygianGates commented on lib/Differentiator/ForwardModeVisitor.cpp
> +    if (const auto* ME = dyn_cast<CXXMemberCallExpr>(CE)) {
Yes, I have already added another non-differentiable attribute for both CallExpr and MemberExpr. Currently, we will return true for the corresponding member functions of a NonDifferentiable class.

2023-07-04 10:53 UTC, PhrygianGates commented on lib/Differentiator/ForwardModeVisitor.cpp
> +      if (clad::utils::hasNonDifferentiableAttribute(ME->getMemberDecl())) {
already done

2023-07-04 21:24 UTC, parth-07 requested changes

2023-07-04 21:24 UTC, parth-07 commented on lib/Differentiator/CladUtils.cpp
> +      return Attr && Attr->getAnnotation() == "non_differentiable";
This will give incorrect results if a declaration has multiple attributes and `non_differentiable` is not the 
first attribute of the declaration. A declaration can have multiple attributes. 
`Decl::getAttr<clang::AnnotateAttr` will only return the first attribute of a declaration.

Can you please fix this and add a test for the same?

2023-07-04 21:24 UTC, parth-07 commented on lib/Differentiator/CladUtils.cpp
> +          if(Attr && Attr->getAnnotation() == "non_differentiable") {
Same as before. It will give incorrect results if there are multiple attributes and `non_differentiable` is not the first
attribute of the declaration.

2023-07-04 21:24 UTC, parth-07 commented on lib/Differentiator/CladUtils.cpp
> +            auto* Attr = classType->getAttr<clang::AnnotateAttr>();
Same as before. It will give incorrect results if there are multiple attributes and `non_differentiable` is not the first
attribute of the class.

2023-07-04 21:24 UTC, parth-07 commented on lib/Differentiator/CladUtils.cpp
> +          auto* Attr = FD->getAttr<clang::AnnotateAttr>();
Same as before. It will give incorrect results if there are multiple attributes and `non_differentiable` is not the first
attribute of the function.

2023-07-04 21:24 UTC, parth-07 commented on lib/Differentiator/CladUtils.cpp
> +              auto* Attr = classType->getAttr<clang::AnnotateAttr>();
Same as before. It will give incorrect results if there are multiple attributes and `non_differentiable` is not the first
attribute of the function.

2023-07-04 21:24 UTC, parth-07 commented on lib/Differentiator/DerivativeBuilder.cpp
> +        diag(DiagnosticsEngine::Error,
Why do we only print the error if verbose diagnostics is true?

2023-07-04 21:24 UTC, parth-07 commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    auto* typeDecl = VD->getType()->getAsCXXRecordDecl();
Will this work correctly for the below declaration statement?

```cpp
NonDifferentiableClass *d1, d2, d3;
```

Here the first declaration is a pointer.

2023-07-04 22:56 UTC, PhrygianGates commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +        ConstantFolder::synthesizeLiteral(m_Context.IntTy, m_Context, 0);
Regarding functionality, the use of IntTy 0 is acceptable because it behaves identically to DoubleTy 0 in both multiplication and addition contexts. Furthermore, upon reviewing the original code, I found that m_Context.IntTy is used consistently, whereas m_Context.DoubleTy isn't utilized.

2023-07-04 22:59 UTC, PhrygianGates commented on lib/Differentiator/CladUtils.cpp
> +      return Attr && Attr->getAnnotation() == "non_differentiable";
Thank you; I was unaware of it. I will promptly fix the issue.

2023-07-04 23:00 UTC, PhrygianGates commented on lib/Differentiator/DerivativeBuilder.cpp
> +        diag(DiagnosticsEngine::Error,
I'll remove the if verbose check.

2023-07-05 21:22 UTC, PhrygianGates commented on test/ForwardMode/NonDifferentiable.C
> +#define TEST_CLASS(classname, name, i, j)                                      \
> Okay, got it. Do you think if the TestUtils framework can be extended to work with class methods as well?

Apologies for overlooking this review earlier. If necessary, I can integrate the macro into the TestUtils framework.

2023-07-05 21:38 UTC, PhrygianGates commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    auto* typeDecl = VD->getType()->getAsCXXRecordDecl();
It can't work correctly for the given declaration statement.

The type checking in this code is checking the CXXRecordDecl of the VarDecl type, and since pointers in C++ are fundamentally different from non-pointer types, typeDecl will be null for d1 because the getAsCXXRecordDecl() method will not return a record declaration for a pointer type. Therefore, this code would not correctly recognize d1 as a variable of a non-differentiable type, even though it's a pointer to such a type.

For d2 and d3, since the checking only happens on the first declaration (which is d1), these declarations won't be processed under the current implementation.

I'll fix this issue.

2023-07-05 22:16 UTC, PhrygianGates commented on lib/Differentiator/CladUtils.cpp
> +          if(Attr && Attr->getAnnotation() == "non_differentiable") {
already done

2023-07-09 16:10 UTC, parth-07 commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +        ConstantFolder::synthesizeLiteral(m_Context.IntTy, m_Context, 0);
Okay, can you please open an issue to make the usage of zero type consistent throughout the codebase?

2023-07-09 16:10 UTC, parth-07 approved these changes
Looks good.

2023-07-09 16:17 UTC, vgvassilev commented
@PhrygianGates can you squash all commits into one and rebase?

2023-07-10 19:00 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +  if (declsBegin != declsEnd && isa<VarDecl>(*declsBegin)) {
Can we write this conditional as:
`if (VarDecl *VD = dyn_cast<VarDecl>(DS->decls().begin())`

That is would this work correctly if begin() == end()?

2023-07-10 19:00 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +        }
```suggestion
        if (auto VD = dyn_cast<VarDecl>(D))
          decls.push_back(VD);
        else
          diag(DiagnosticsEngine::Warning, D->getEndLoc(),
               "Unsupported declaration");
```

2023-07-12 13:33 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    QualType QT = VD->getType();
@PhrygianGates, please do not address these comments. @vaithak is looking how to suppress them.

2023-07-12 13:34 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    if (typeDecl && clad::utils::hasNonDifferentiableAttribute(typeDecl)) {
@vaithak we should probably ignore such suggestions too.

2023-07-12 13:36 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +        if (auto VD = dyn_cast<VarDecl>(D))
We should ignore that too.

2023-07-12 13:51 UTC, PhrygianGates commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    QualType QT = VD->getType();
ok

2023-07-14 10:00 UTC, vgvassilev commented
Can you rebase on top of master?

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    }
```suggestion
    if (clad::utils::hasNonDifferentiableAttribute(ME))
      return {clonedME, zero};
```

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    }
```suggestion
    for (unsigned i = 0, e = CE->getNumArgs(); i < e; ++i)
      ClonedArgs.push_back(Clone(CE->getArg(i)));
```

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    auto zero =
I think that suggestion is good and we should take it.

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +  auto declsBegin = DS->decls().begin();
Likewise.

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +  auto declsEnd = DS->decls().end();
That too.

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +  if (declsBegin != declsEnd && isa<VarDecl>(*declsBegin)) {
Fair enough.

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    auto VD = dyn_cast<VarDecl>(*declsBegin);
+1

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      QT = QT->getPointeeType();
Can you exclude `readability-braces-around-statements` from the clang-tidy checks in the `.clang-tidy` file?

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    if (typeDecl && clad::utils::hasNonDifferentiableAttribute(typeDecl)) {
We might tweak this check by adding `AllowPointerConditions=true`.

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      for (auto D : DS->decls()) {
+1

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +        if (auto VD = dyn_cast<VarDecl>(D))
+1

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/CladUtils.cpp
> +      }
Ping.

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/CladUtils.cpp
> +        if (auto memberDecl = ME->getMemberDecl()) {
+1

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/CladUtils.cpp
> +            return true;
-1

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/CladUtils.cpp
> +        if (auto classType = ME->getBase()->getType()->getAsCXXRecordDecl()) {
+1

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/CladUtils.cpp
> +            return true;
-1

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/CladUtils.cpp
> +            return true;
-1

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/CladUtils.cpp
> +          if (auto classType = ME->getImplicitObjectArgument()
+1

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/CladUtils.cpp
> +              return true;
-1

2023-07-14 13:17 UTC, vgvassilev commented on lib/Differentiator/DerivativeBuilder.cpp
> +           request.CallContext ? request.CallContext->getBeginLoc() : noLoc,
-1

2023-07-18 06:55 UTC, vgvassilev approved these changes
LGTM! Please update the commit message to match the PR description and I can merge this.

2023-07-18 06:56 UTC, vgvassilev commented
> LGTM! Please update the commit message to match the PR description and I can merge this.

And please apply clang-format to the PR.

2023-07-18 08:23 UTC, PhrygianGates commented
> > LGTM! Please update the commit message to match the PR description and I can merge this.
> 
> And please apply clang-format to the PR.

ok

2023-07-18 11:02 UTC, vgvassilev commented
This looks good, however, when we are not rebased on top of the master the git-clang-format picks up other issues and reports them. @vaithak we should either automatically rebase the PR which is hard, or pick up the changes done by the author only. I've done that [here](https://github.com/root-project/root/blob/063e1b1a8fd2d32479e98969b3bac258b6909c7d/.ci/format_script.sh#L5-L7) long time ago and I think the approach still works. Can you adapt this to fit out CI?

2023-07-18 11:02 UTC, merged

2023-07-18 11:13 UTC, vaithak commented
> This looks good, however, when we are not rebased on top of the master the git-clang-format picks up other issues and reports them. @vaithak we should either automatically rebase the PR which is hard, or pick up the changes done by the author only. I've done that [here](https://github.com/root-project/root/blob/063e1b1a8fd2d32479e98969b3bac258b6909c7d/.ci/format_script.sh#L5-L7) long time ago and I think the approach still works. Can you adapt this to fit out CI?

I experienced this too in the last PR, will look into this :+1: