Split ForwardMode into separate classes
vgvassilev/clad pull request #572
Opened 2023-06-16 16:38 UTC by vaithak

2023-06-16 17:12 UTC, vaithak commented
will add more test cases to make codecov happy, but some of these will require changes in this PR: https://github.com/vgvassilev/clad/pull/571

2023-06-20 14:19 UTC, vgvassilev commented
@vaithak do you think you can write some tests for the missed branches that codecov reports. They are not due to this PR but we can right a historical wrong :)

2023-06-20 20:56 UTC, parth-07 reviewed
@vaithak This looks great!

I will need a bit more time to review this pull request.

2023-06-21 05:04 UTC, vaithak commented
> @vaithak do you think you can write some tests for the missed branches that codecov reports. They are not due to this PR but we can right a historical wrong :)

Sure, I am working on this, that's why I was able to find issues with comma expressions and the ternary operator case 😅 , these didn't had tests till now for forward mode AD.

2023-06-24 16:33 UTC, parth-07 requested changes
It looks great overall.

2023-06-24 16:33 UTC, parth-07 commented on lib/Differentiator/CMakeLists.txt
> +  VectorForwardModeVisitor.cpp
Minor: Please sort the filenames here.

2023-06-25 08:16 UTC, vaithak commented on lib/Differentiator/VectorForwardModeVisitor.cpp
> +VarDeclDiff VectorForwardModeVisitor::DifferentiateVarDecl(const VarDecl* VD) {
the difference was in prefix assigned tot he derived variable, so created an extra overloaded function for this which takes a prefix as a parameter.

2023-06-25 08:16 UTC, vaithak commented on lib/Differentiator/CMakeLists.txt
> +  VectorForwardModeVisitor.cpp
done 👍🏼

2023-06-25 08:52 UTC, vaithak commented on lib/Differentiator/VectorForwardModeVisitor.cpp
> +VarDeclDiff VectorForwardModeVisitor::DifferentiateVarDecl(const VarDecl* VD) {
Please ignore the previous comment, currently the difference is in just prefix and type of derived variable, but it will be more visible in [this PR](https://github.com/vgvassilev/clad/pull/570), where the initialisation style will also change for vector mode.
So, I think it is better to override this.

2023-06-25 13:22 UTC, vaithak commented
added test for most of the uncovered cases to increase coverage (ignoring some failure edge cases)

2023-06-25 21:18 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    incResult = incDiff.getExpr();
Don't we want to write a test for this branch?

2023-06-25 21:18 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    return nullptr;
That should be easy to test with having a `void f(double d) { return; }`?

2023-06-25 21:18 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      return {clonedME, zero};
@parth-07 do you have an idea how to test this case?

2023-06-25 21:18 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      return {cloned, zero};
@parth-07 and here?

2023-06-25 21:18 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      return StmtDiff(cloned, zero);
@parth-07 and probably here?

2023-06-25 21:18 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      DC = originalFnDC;
@grimmmyshini do you have an idea how to test this branch?

2023-06-25 21:18 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +        return {op, derivedE};
@parth-07 and here?

2023-06-25 21:18 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    assert(0 && "Unsupported switch case statement");
Is that reachable at all?

2023-06-25 21:18 UTC, vgvassilev commented
@vaithak did you run clang-format on this patch?

2023-06-26 20:15 UTC, parth-07 commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      return StmtDiff(cloned, zero);
This example reaches this code:

```cpp
#include "clad/Differentiator/Differentiator.h"

struct Array {
    double data[5];
};

Array array;

double fn(double i, double j) {
    return array.data[0] * i + array.data[1] * j;
}

int main() {
    auto d_fn = clad::differentiate(fn, "i");
}
```

2023-06-26 20:15 UTC, parth-07 commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +        return {op, derivedE};
It seems that this `if` block can be safely removed. We later added proper support for dereference operator, which made this special case redundant.

2023-06-26 20:15 UTC, parth-07 commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    assert(0 && "Unsupported switch case statement");
It's an assert. Hopefully, it's not reachable :).

2023-06-26 20:23 UTC, parth-07 commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      return StmtDiff(cloned, zero);
I cannot think of a case for this right now. But it might be possible in some obscure cases.

2023-06-28 12:33 UTC, vaithak commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    incResult = incDiff.getExpr();
I couldn't find any expression such that the original expression is not null, but it's derivative expression is null.
Can this branch be removed ? cc: @parth-07

2023-06-28 12:34 UTC, vaithak commented
> @vaithak did you run clang-format on this patch?

yup 👍🏼

2023-06-28 12:37 UTC, vaithak commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      return {clonedME, zero};
Thanks for the example, added this as a test.

2023-06-28 12:38 UTC, vaithak commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +        return {op, derivedE};
removed this condition

2023-06-29 18:23 UTC, parth-07 approved these changes
Looks good overall. Please add the remaining test cases if any and squash the commits into one.

2023-06-29 18:23 UTC, parth-07 commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    incResult = incDiff.getExpr();
No, this cannot be removed. This example reaches this branch:

```cpp
#include "clad/Differentiator/Differentiator.h"

void increment(int &i) {
    ++i;
}

double fn(double i, double j) {
    double res = 0;
    for (int i=0; i < 5; increment(i))
        res += i*j;
    return res;
}

int main() {
    auto d_fn = clad::differentiate(fn, "i");
}
```

2023-06-29 18:23 UTC, parth-07 commented on lib/Differentiator/VectorForwardModeVisitor.cpp
> +VarDeclDiff VectorForwardModeVisitor::DifferentiateVarDecl(const VarDecl* VD) {
Okay, got it.

2023-06-29 18:30 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    assert(0 && "Unsupported switch case statement");
Perhaps also issue an unsupported diagnostics?

2023-06-29 19:31 UTC, vaithak commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    incResult = incDiff.getExpr();
Oh, nice! I wrongly tried using return directly as it has a derivative expression as null.
Thanks for this 👍🏼 , added.

2023-06-29 19:32 UTC, vaithak commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    assert(0 && "Unsupported switch case statement");
This is inside a static function, so `diag` can't be used here.

2023-06-29 19:35 UTC, parth-07 approved these changes
Thank you for the great work. LGTM.

2023-06-29 20:37 UTC, vgvassilev approved these changes
Great work!

2023-06-29 20:37 UTC, merged