Rev ref returns
vgvassilev/clad pull request #601
Opened 2023-07-20 17:56 UTC by PhrygianGates

This PR rebase the https://github.com/vgvassilev/clad/pull/425 pull-request on top of master. There still remain some bugs.

2023-07-30 11:42 UTC, parth-07 commented
@PhrygianGates Can you please debug and fix the failing debug checks?

2023-07-30 11:43 UTC, parth-07 commented
Is the pull request ready for review?

2023-08-01 19:56 UTC, PhrygianGates commented
> @PhrygianGates Can you please debug and fix the failing debug checks?

I'm not sure as it seems to go wrong when installing something. I'll push again to see what happens.

2023-08-01 20:00 UTC, vgvassilev commented
> > @PhrygianGates Can you please debug and fix the failing debug checks?
> 
> I'm not sure as it seems to go wrong when installing something. I'll push again to see what happens.

This fails elsewhere due to some server outage it seems. We can ignore this for now.

2023-08-02 05:53 UTC, vgvassilev commented on include/clad/Differentiator/ReverseModeForwPassVisitor.h
> +  llvm::SmallVector<clang::QualType, 8>
We should be able to suppress these by adding `IgnorePowersOf2IntegerValues=true` in the clang-tidy config: https://clang.llvm.org/extra/clang-tidy/checks/readability/magic-numbers.html

2023-08-04 22:25 UTC, parth-07 requested changes

2023-08-04 22:25 UTC, parth-07 commented on lib/Differentiator/DerivativeBuilder.cpp
> +
This new-line can be removed.

2023-08-04 22:25 UTC, parth-07 commented on lib/Differentiator/ReverseModeForwPassVisitor.cpp
> +  // llvm::errs() << "Derive: dumping fnBody:\n";
Remove `llvm::errs()` comments from here and other places.

2023-08-04 22:25 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      // bug here?
Remove this.

2023-08-04 22:25 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      /// Add base derivative expression in the derived call output args list if
Can this comment be removed?

2023-08-13 18:28 UTC, parth-07 requested changes

2023-08-13 18:28 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      return StmtDiff(resValue, resAdjoint, resAdjoint);
```suggestion
      return StmtDiff(resValue, nullptr, resAdjoint);
```
Call expressions do not have a corresponding derivative that can be used explicitly in the reverse-sweep, 
as we insert the derivative call expression implicitly.

2023-08-13 18:28 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      return StmtDiff(resValue, resAdjoint, resAdjoint);
You will also need to change, `ReverseModeVisitor::DifferentiateVarDecl`:

```cpp
if (isDerivativeOfRefType) {
        initDiff = Visit(VD->getInit());
        if (!initDiff.getExpr_dx()) {
          VDDerivedType =
              ComputeAdjointType(VD->getType().getNonReferenceType());
          isDerivativeOfRefType = false;
        }
        VDDerivedInit = getZeroInit(VDDerivedType);
      }
```
to:

```cpp
if (isDerivativeOfRefType) {
        initDiff = Visit(VD->getInit());
        if (!initDiff.getForwSweepExpr_dx()) { // This line changed!!
          VDDerivedType =
              ComputeAdjointType(VD->getType().getNonReferenceType());
          isDerivativeOfRefType = false;
        }
        VDDerivedInit = getZeroInit(VDDerivedType);
      }
```

2023-08-16 15:38 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    }
Can we incorporate that suggestion?

2023-08-16 15:40 UTC, vgvassilev reviewed
Most of the clang-tidy suggestions make sense. Could you incorporate them in the PR?

2023-08-19 07:41 UTC, parth-07 commented on demos/ComputerGraphics/smallpt/SmallPT.cpp
> -// ../../../../../obj/Debug+Asserts/bin/clang++ -O3 -Xclang -add-plugin -Xclang clad \
Can you please revert back the changes to the demos?

2023-08-19 09:00 UTC, vgvassilev commented on lib/Differentiator/ReverseModeForwPassVisitor.cpp
> +  m_Sema.CurContext = const_cast<DeclContext*>(m_Function->getDeclContext());
```suggestion
  m_Sema.CurContext = const_cast<DeclContext*>(m_Function->getDeclContext()); NOLINT(cppcoreguidelines-pro-type-const-cast)
```

2023-08-28 15:46 UTC, vgvassilev approved these changes
LGTM. Thank you!

2023-08-28 15:47 UTC, merged