Operator overload in reverse mode
vgvassilev/clad pull request #619
Opened 2023-08-20 19:10 UTC by PhrygianGates

Add support for operator overload in reverse mode

2023-08-30 18:27 UTC, parth-07 requested changes
We need more tests. 
1) Member operator overloads -- operator overloads that are defined inside the class.
2) Operator overload that does not return a reference type.
3) Unary operator overload.

2023-08-30 18:27 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +          m_Mode == DiffMode::reverse_mode_forward_pass) {
Why do we have reverse mode forward pass specific code in ReverseModeVisitor? This defeats the whole purpose of having a separate class for ReverseModeVisitor.

2023-09-01 08:26 UTC, PhrygianGates commented
> We need more tests.
> 
> 1. Member operator overloads -- operator overloads that are defined inside the class.
> 2. Operator overload that does not return a reference type.
> 3. Unary operator overload.

For 1, our tests already cover the case.
For 2, because we have this prior restriction in the existing code we can not support the case
```cpp
      if (!FD->getReturnType()->isVoidType()) {
        assert((pullback && !FD->getReturnType()->isVoidType()) &&
               "Call to function returning non-void type with no dfdx() is not "
               "supported!");
      }
```
 For 3, I have added tests for unary op.

2023-09-03 08:32 UTC, parth-07 commented
> For 2, because we have this prior restriction in the existing code base, we can not support the case yet.

Why does the restriction that you mentioned prevent non-reference return types? Also, why do you think it only affects non-reference return type operator overloads, but not non-reference return type ordinary member functions?

2023-09-03 08:33 UTC, parth-07 commented on benchmark/VectorModeComparison.cpp
> +static void BM_ForwardModeWeightedSum(benchmark::State& state) {
These benchmarks shouldn't be part of this pull request. Can you please rebase the pull request properly?

2023-10-15 22:05 UTC, vgvassilev approved these changes
LGTM!

2023-10-15 22:05 UTC, merged