Floating Point Error Estimation RST added
vgvassilev/clad pull request #648
Opened 2023-10-26 14:23 UTC by QuillPusher

- Floating Point Error Estimation Info and links consolidated in this article

- Added link to Side Navigation in Index file (shortened the name to "FP" due to limited space in side menu)

2023-10-26 14:49 UTC, vgvassilev commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +Who is this article for?
Perhaps we can remove this section?

2023-10-26 14:54 UTC, QuillPusher commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +Who is this article for?
section removed and commit squashed to existing commit

2023-10-28 00:08 UTC, parth-07 requested changes

2023-10-28 00:08 UTC, parth-07 commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +the context of FP error estimation, this research uses:
Can you please clarify what do you mean by 'this research uses'?

2023-10-28 00:08 UTC, parth-07 commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +The main logic for Floating Point Error Estimation resides in the following
We should not add implementation details in the user documentation. For user documentation, we should perhaps focus on these things:

- What is error estimation? 
- Why use AD in error estimation as opposed to other differentiation techniques in error estimation?
- What will happen if AD fails?
- Tutorials/Examples that show how to use Clad's error estimation functionality effectively.

@vgvassilev and @grimmmyshini can comment better on the documentation structure.

2023-10-28 00:08 UTC, parth-07 commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +errors against that variable). Next, the Error Estimation Calcualtion Formula
```suggestion
errors against that variable). Next, the Error Estimation Calculation Formula
```

2023-10-28 00:08 UTC, parth-07 commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +variable,it needs to be registered into the system (to accumulate relevant
What is system here?

2023-10-28 00:08 UTC, parth-07 commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +This model will return a formula that is represented using a Clang
Users perhaps do not care at all if the error is a clang expression. We should write this documentation in a way that is useful for the users.

2023-10-29 16:05 UTC, vgvassilev commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +variable,it needs to be registered into the system (to accumulate relevant
```suggestion
variable, it needs to be tracked (to accumulate relevant
```

2023-10-30 11:48 UTC, QuillPusher commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +the context of FP error estimation, this research uses:
Thanks, I just realized that the phrasing is a bit off... Rephrasing as suggested by Vassil below:

AD helps evaluate the exact derivative of a function. AD applies the
**differential calculus chain rule** throughout the semantics of the original
program. In the context of FP error estimation, **~this research~ the implementation relies on:**:

2023-10-30 11:50 UTC, QuillPusher commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +The main logic for Floating Point Error Estimation resides in the following
I have linked the Doxygen and ReadMe docs in the comment below

2023-10-30 11:51 UTC, QuillPusher commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +variable,it needs to be registered into the system (to accumulate relevant
Rephrased as suggested by Vassil:

While parsing the code using Clad, if it encounters a floating point variable,
it needs to be **tracked**

2023-10-30 11:52 UTC, QuillPusher commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +This model will return a formula that is represented using a Clang
This is as described by Garima. As I understand, the idea was that familiarity with Clang expressions is required, since we're targeting a dev audience, including new comers... Please let me know if you have an alternate text suggestion

2023-10-30 11:54 UTC, QuillPusher commented
Thanks @parth-07  and @vgvassilev for the review, requested changes incorporated

2023-11-01 08:19 UTC, vgvassilev commented
@parth-07, can you take a look again?

@davidlange6, could you take a look and proofread?

2023-11-01 09:04 UTC, davidlange6 commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +FP Error Estimation
Don't abbreviate the title.. Write out Floating Point

2023-11-01 09:11 UTC, davidlange6 commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +.. _Fast and Automatic Floating Point Error Analysis: https://arxiv.org/pdf/2304.06441.pdf
use complete title

2023-11-01 09:12 UTC, davidlange6 commented on docs/userDocs/source/user/FloatingPointErrorEstimation.rst
> +FP Error Estimation
Branding - this tool is called CHEF-FP. We should refer to it that way (repeatedly)

2023-11-05 12:58 UTC, QuillPusher commented
Incorporated David's review changes:
- Mentioned Chef-FP in relevant places
- Explained Chef-FP in the beginning, linked to paper
- changed FPEE to full form in all places (except in code elements)
- squashed commits for a cleaner look

2023-11-15 19:29 UTC, parth-07 approved these changes

2023-11-18 10:02 UTC, merged