[WIP][Docs] Clad Tutorial
vgvassilev/clad pull request #657
Opened 2023-11-22 15:37 UTC by Ris-Bali

Initial Draft for Clad tutorial

2023-12-20 21:36 UTC, Ris-Bali commented
The error is now fixed

2023-12-21 14:27 UTC, parth-07 requested changes

2023-12-21 14:27 UTC, parth-07 commented on docs/userDocs/source/user/UsingClad.rst
> +  auto fn_hessian = clad::hessian(fn, "x, arr[0:1]");
Please format this code.

2023-12-21 14:27 UTC, parth-07 commented on docs/userDocs/source/user/tutorials.rst
> +   /*Calling clad::differentiate to get the forward mode derivative of
Can you please format the code everywhere using clang-format?

2023-12-21 14:27 UTC, parth-07 commented on docs/userDocs/source/user/tutorials.rst
> +Here we are differentiating a function `func` which takes an input x and
`x` should be in code-formatting here.

2023-12-21 14:27 UTC, parth-07 commented on docs/userDocs/source/user/tutorials.rst
> +This API call is more or less similar to the reverse mode API call and differs
Hessian mode is not more or less similar to the reverse mode API call.

2023-12-24 11:50 UTC, parth-07 approved these changes
Please squash the commits into one commit and improve the commit message.

2024-01-02 09:49 UTC, merged