Add declarations for variables reused in the reverse pass
vgvassilev/clad pull request #688
Opened 2023-12-22 15:43 UTC by PetroZarytskyi

The problem this PR attempts to fix is described in #659. This is still a draft. Since scopes for forward and reverse passes were separated, ``ReferencesUpdater`` is not able to find declarations to update ``DeclRefExpr``'s. After this is fixed, we need to update the tests.

2023-12-30 13:07 UTC, parth-07 commented
@PetroZarytskyi Can you please describe the solution in the commit message / pull request description?

2024-01-12 18:43 UTC, vgvassilev reviewed
Here is some partial review. Could you go over your FIXME notes and try to address them as it seems most of them need to be addressed within this PR.

2024-01-12 18:43 UTC, vgvassilev commented on include/clad/Differentiator/ReverseModeVisitor.h
> +        m_Locals.pop_back();
We should move the pop operation in `EmitRevSweepDecls`.

2024-01-12 18:43 UTC, vgvassilev commented on include/clad/Differentiator/ReverseModeVisitor.h
> +    /// Add more comments.
We should address this comment.

2024-01-12 18:43 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      /// FIXME: Explain this.
Maybe we should address that fixme.

2024-01-12 18:43 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        VD->setInit(nullptr);
Why do we remove the initializer here?

2024-01-12 18:43 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (!isPointerOp && valueForRevPass==nullptr)
```suggestion
    if (!isPointerOp && !valueForRevPass)
```

2024-01-13 02:12 UTC, parth-07 requested changes

2024-01-14 21:21 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    StmtDiff initResult = nullptr;
I agree. Probably did this by mistake.

2024-01-14 22:03 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    bool old_isInsideLoop = isInsideLoop;
Because ``EmitRevSweepDecls`` decides on whether to create a tape based on ``isInsideLoop``. We want the original ``isInsideLoop`` value when emitting reverse sweep decls from the loop init (which happens when ending the forward block).

2024-01-14 22:19 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    /// FIXME: Why do we need to differentiate DeclRefExpr twice?
From what I get, ``inc`` is supposed to be the original increment (it's always differentiated later). Why is it differentiated specifically when it is a DeclRefExpr?

2024-01-14 22:27 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> -      clonedIndices[i] = Clone(IdxDiff.getExpr());
Well, it's necessary to replace ``getExpr`` with ``getRevSweepAsExpr`` for ``reverseIndices``. I could move ``Clone`` to where they were previously if that matters.

2024-01-14 22:46 UTC, PetroZarytskyi commented on test/Gradient/Loops.C
> +//CHECK-NEXT:           int i;
The issue here is that we want to store the last value of the loop init. So we need to access ``i`` once right after the last condition. But we can't do that outside the loop since the variable is not declared there. My solution doesn't too look nice though so if you have a better idea feel free to share it.

2024-01-14 22:51 UTC, PetroZarytskyi commented on include/clad/Differentiator/ReverseModeVisitor.h
> +        m_Locals.pop_back();
Sometimes we want to emit reverse sweep decls before ending the block (when handling return/break/continue statements). There is an option to add an argument to ``EmitRevSweepDecls`` to decide whether it should do the pop operation.

2024-01-14 22:58 UTC, PetroZarytskyi commented on lib/Differentiator/CladUtils.cpp
> -             "initial should be of type `clang::CompoundStmt`");
I changed it to be consistent with ``PrependAndCreateCompoundStmt``. The difference is that when we pass an individual stmt as ``initial``, we wrap it in a compound stmt with ``S`` instead of considering this an error. I needed this at some point but not anymore. I can revert this but I think this change makes sense at least for consistency.

2024-01-14 23:07 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        VD->setInit(nullptr);
Because I replaced the declaration inside the loop init with an assignment to move the declaration outside. Parth asked about why this is done. Alternatively, I could move the whole declaration outside and leave the loop init empty.

2024-01-14 23:28 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (!isPointerOp && valueForRevPass==nullptr)
The only reason I used ``==nullptr`` was because I think clang-tidy argues about implicit conversion from pointers to bool.

2024-01-15 14:19 UTC, vgvassilev commented on include/clad/Differentiator/ReverseModeVisitor.h
> +        m_Locals.pop_back();
I had a comment that probably went away to move the pop_back operation in the call to Emit.

2024-01-15 14:36 UTC, PetroZarytskyi commented on include/clad/Differentiator/ReverseModeVisitor.h
> +        return const_cast<clang::Expr*>(E);
Because to track that as a placeholder, we want the original expression. If it's cloned, we will not be able to replace it and it will remain in the AST.

2024-01-15 16:53 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    isInsideLoop = old_isInsideLoop;
```suggestion
    isInsideLoop = SaveIsInsideLoop.get();
```

2024-01-15 17:19 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +          argDiffStore = {newArgE, nullptr, nullptr, argDiffLocalE};
Maybe add the argument kinds as comments.

2024-01-15 17:19 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (isPointerOp || isToBeRecorded(E->getBeginLoc())) {
We should sink `isPointerOp` in `isToBeRecorded`.

Add a fixme note pointing out that we can remove this once we support pointers in TBR.

2024-01-15 17:19 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      Restore = Ref;
Can we add a test here?

2024-01-15 17:19 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (Placeholder!=nullptr) {
```suggestion
    if (!Placeholder) {
```

2024-01-15 17:19 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        addToCurrentBlock(bodyDiff.getStmt(), direction::forward);
Can we add a test here?

2024-01-15 17:19 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +          addToCurrentBlock(bodyDiff.getStmt_dx(), direction::reverse);
And here?

2024-01-15 17:19 UTC, vgvassilev commented on include/clad/Differentiator/ReverseModeVisitor.h
> +        m_Locals.pop_back();
Yes, let's add an argument whose default value is to pop.

2024-01-16 21:54 UTC, parth-07 requested changes

2024-01-16 21:54 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    // FIXME: Is there a better way to determine non-function-global scope
Yes, there must be a better way for this. Have you tried `VD->getDeclContext() != m_Function`?
Ideally, function global scope variables should have the primal `FunctionDecl` as their `DeclContext`

2024-01-16 21:54 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        init = Clone(VD->getInit());
This seems incorrect. What if the expression returned by `VD-getInit()` cannot be used in the reverse sweep? For example:

```cpp
{ 
  double u = 7;
  const double v = u;
}
```
If I understand things correctly, when redeclaring `const double v` in the reverse sweep, `init` is pointing towards `double u` of the forward sweep instead of the reverse sweep.

2024-01-18 14:20 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (isPointerOp || isToBeRecorded(E->getBeginLoc())) {
Done.

2024-01-18 14:46 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    // FIXME: Is there a better way to determine non-function-global scope
I'm not sure how ``DeclContext`` works exactly but ``getDeclContext`` seems to return ``m_Function`` for variables declared inside loops etc.

2024-01-18 14:56 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        init = Clone(VD->getInit());
The reason for that init is mainly that creating a const / reference-type declaration without an init produces a warning (even if the init is set later).

2024-01-18 15:08 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +          argDiffStore = {newArgE, nullptr, nullptr, argDiffLocalE};
I added such comments here and in two more places but maybe we'll need more of them.

2024-01-18 15:19 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      Restore = Ref;
I didn't manage to come up with such a test. I think the check is excessive. I removed it.

2024-01-18 15:20 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        addToCurrentBlock(bodyDiff.getStmt(), direction::forward);
I didn't manage to come up with such a test. I think the check is excessive. I removed it.

2024-01-18 15:20 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +          addToCurrentBlock(bodyDiff.getStmt_dx(), direction::reverse);
Same thing here.

2024-01-18 15:22 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      for (Stmt* S : cast<CompoundStmt>(bodyDiff.getStmt())->body())
These changes will break this valid c++ code:
```cpp
int f(int x) 
  try { return x; }
  catch(...) { return 0; }
```

2024-01-18 15:22 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      for (Stmt* S : cast<CompoundStmt>(bodyDiff.getStmt())->body())
Maybe we can add this as a test case.

2024-01-20 13:23 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (auto* initDeclStmt = dyn_cast<DeclStmt>(initResult.getStmt())) {
Oh, okay. Got it. Thanks for the explanation.

2024-01-20 13:24 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        init = Clone(VD->getInit());
Oh, okay. Can you please document in the code that this `init` is only a placeholder and the actual value for `init` is updated later?

2024-01-20 13:41 UTC, parth-07 commented
The produced gradient of the below code has compile-time error in the local variable redeclaration part.

```cpp
double fn(double u, double v) {
    double r;
    {
        double res;
        double v_copy = v;
        double &v_ref = v_copy;
        res = v_ref;
        r = res;
    }
    return r;
}
```

The local variable redeclaration in the reverse sweep is as follows:

```cpp
double &v_ref = v_copy;
double v_copy = _t3;
double res = _t2;
```

`v_ref` should be declared after `v_copy`.

2024-01-20 15:26 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        VD->setInit(nullptr);
I changed this bit so the discussion is probably not relevant anymore.

2024-01-20 16:51 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      for (Stmt* S : cast<CompoundStmt>(bodyDiff.getStmt())->body())
Earlier in the code, we check if the body is a compound statement. What we could ask is whether it's possible to have the forward sweep of the result not being a compound statement (when the original body is a compound statement). From what I get, this is not possible.

2024-01-20 16:54 UTC, vgvassilev commented on include/clad/Differentiator/ReverseModeVisitor.h
> +        return const_cast<clang::Expr*>(E);
Can we add a comment here explaining that?

2024-01-22 11:39 UTC, vgvassilev commented on include/clad/Differentiator/ReverseModeVisitor.h
> +        EmitReverseSweepDeclarations();
Can we add a test case covering this branch?

2024-01-22 11:48 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        init = Clone(VD->getInit());
Done.

2024-01-22 12:29 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      Restore = Ref;
Done.

2024-01-22 12:37 UTC, vgvassilev commented on include/clad/Differentiator/ReverseModeVisitor.h
> +        EmitReverseSweepDeclarations();
Is that dead code then?

2024-02-08 11:02 UTC, vgvassilev commented
@PetroZarytskyi, is that PR superseded by #738? Can we close it?

2024-02-12 21:46 UTC, PetroZarytskyi commented
> @PetroZarytskyi, is that PR superseded by #738? Can we close it?

I think the solution implemented in #738 is better. We should probably close this PR.

2024-02-12 21:46 UTC, closed without merging