Delay the differentiation process until the end of TU.
vgvassilev/clad pull request #766
Opened 2024-02-15 20:01 UTC by vgvassilev

Before this patch clad attaches itself as a first consumer and applies AD before code generation. However, that is limited since clang sends every top-level declaration to codegen which limits the amount of flexibility clad has. For example, we have to instantiate all pending templates at every HandleTopLevelDecl calls; we cannot really differentiate virtual functions whose classes have sent their key function to CodeGen; and in general we perform actions which are semantically useful for the end of the translation unit.

This patch makes clad a single consumer of clang which dispatches to the others. That's done by delaying all calls to the consumers until the end of the TU where clad can replay the exact sequence of calls to the other consumers as if they were directly connected to the frontend.

Fixes https://github.com/vgvassilev/clad/issues/248

2024-02-16 09:21 UTC, vgvassilev commented on tools/ClangPlugin.cpp
> +      m_Multiplexer.reset(new MultiplexConsumer(std::move(StolenConsumers)));
We still want to support C++11.

2024-02-16 09:21 UTC, vgvassilev commented on tools/ClangPlugin.cpp
> +      m_Multiplexer.reset(new MultiplexConsumer(std::move(StolenConsumers)));
We still want to support C++11.

2024-02-16 09:31 UTC, vgvassilev commented on tools/ClangPlugin.cpp
> +      auto& MultiplexC = static_cast<MultiplexConsumer&>(m_CI.getASTConsumer());
We compile with -fno-rtti (so is llvm). Our best bet is `static_cast` but we know what this thing is anyway so we are safe.

2024-03-10 10:48 UTC, vgvassilev commented on demos/Arrays.cpp
> +  // auto hessian_arr = clad::hessian(weighted_avg, "arr[0:2]");
I am not particularly happy with this commit, however, this is the only way to make progress here. I believe the demo fails  due to the fact we schedule the hessians recursively. This seems hard to debug because it happens on clang release builds and clad for runtime11, runtime10, and in some cases runtime9.

More information: https://github.com/vgvassilev/clad/actions/runs/8216311966

Perhaps once we fix the way we order diff plans the issue will go away.

2024-03-12 12:01 UTC, parth-07 requested changes

2024-03-12 12:01 UTC, parth-07 commented on tools/ClangPlugin.cpp
>      // We cannot use HandleTranslationUnit because codegen already emits code on
I think we can (finally) remove this comment now :)

2024-03-12 15:39 UTC, vaithak commented
Should we add a detailed description explaining these changes. It would be a helpful reference for us and even new contributors to understand the request flow.
We can have the following sections in that explanation: how did it work earlier and what cases went wrong. How does this solution improve and fix those and some details to walkthrough this implementation.

2024-03-12 17:32 UTC, vgvassilev commented on tools/ClangPlugin.cpp
> +      assert(RobbedCs.back().get() == this && "Clad is not the last consumer");
I want to make sure that clang does not have some weird action that puts a consumer after the plugin consumer is attached.

2024-03-12 19:29 UTC, vgvassilev commented on tools/ClangPlugin.cpp
> +      for (auto& RC : RobbedCs)
Nice!

2024-03-12 19:29 UTC, vgvassilev commented on tools/ClangPlugin.h
> +            if (!(*first1 == *first2))
Good catch.

2024-03-12 19:30 UTC, vgvassilev commented
> Should we add a detailed description explaining these changes. It would be a helpful reference for us and even new contributors to understand the request flow. We can have the following sections in that explanation: how did it work earlier and what cases went wrong. How does this solution improve and fix those and some details to walkthrough this implementation.

Do you mean in the commit message or the clad documentation?

2024-03-12 19:51 UTC, vaithak commented
> Do you mean in the commit message or the clad documentation?

In the commit message should be sufficient for now, once we have the diff plans also finalized, we can add them in the documentation too if required.

2024-03-12 20:27 UTC, vgvassilev commented
> > Do you mean in the commit message or the clad documentation?
> 
> In the commit message should be sufficient for now, once we have the diff plans also finalized, we can add them in the documentation too if required.

I thought I capture that in the very first commit message:

```
[Delay the differentiation process until the end of TU.](https://github.com/vgvassilev/clad/pull/766/commits/f0c71c987f0005f1c5435ea4e4e95ef57b6aa41e)

Before this patch clad attaches itself as a first consumer and applies AD before
code generation. However, that is limited since clang sends every top-level
declaration to codegen which limits the amount of flexibility clad has. For
example, we have to instantiate all pending templates at every
HandleTopLevelDecl calls; we cannot really differentiate virtual functions
whose classes have sent their key function to CodeGen; and in general we perform
actions which are semantically useful for the end of the translation unit.

This patch makes clad a single consumer of clang which dispatches to the others.
That's done by delaying all calls to the consumers until the end of the TU where
clad can replay the exact sequence of calls to the other consumers as if they
were directly connected to the frontend.
```

What else is missing?

2024-03-12 23:39 UTC, vaithak commented
My bad, didn't notice it was in the commit message itself. This should be fine.

2024-03-14 13:10 UTC, parth-07 approved these changes
Looks good.

2024-03-14 15:22 UTC, vgvassilev commented on tools/ClangPlugin.cpp
> +      constexpr bool Enabled = true;
Because I need to add in the call site `/*Enabled=*/true` and it will overflow on the next line making the code look uglier ;)

2024-03-14 16:11 UTC, parth-07 commented on test/Gradient/Gradients.C
> +void f_if1_grad(double x, double y, clad::array_ref<double> _d_x, clad::array_ref<double> _d_y);
Oh, okay.

2024-03-14 16:12 UTC, parth-07 commented on tools/ClangPlugin.h
> +          return ND->getName().contains("_darg");
> I thought about the same but I hesitate because this way we can do cross translation unit derivative communication because that's what the language does for everything else.

Oh, yes, these function declarations can be very helpful for cross-translation derivative communication. We should definitely document about this in the documentation and how users can depend upon and use this functionality.

2024-03-14 16:13 UTC, parth-07 commented on tools/ClangPlugin.h
> +          return ND->getName().contains("_darg");
It would be helpful to add an interface which users can easily use for determining the derivative type of a given function. Typing the derivative function type by hand can be error-prone and cumbersome

2024-03-14 16:15 UTC, parth-07 commented on tools/ClangPlugin.cpp
> +      assert(RobbedCs.back().get() == this && "Clad is not the last consumer");
Oh, okay. Thank you for the explanation.

2024-03-14 16:16 UTC, parth-07 commented on tools/ClangPlugin.cpp
> +      constexpr bool Enabled = true;
Ah, okay.

2024-03-14 16:17 UTC, merged

2024-03-14 17:10 UTC, vgvassilev commented on tools/ClangPlugin.h
> +          return ND->getName().contains("_darg");
Yes, I am not sure how. If you have an idea maybe we should open an issue?