Simplify pullback calls in the reverse mode
vgvassilev/clad pull request #802
Opened 2024-03-05 22:46 UTC by PetroZarytskyi

This PR simplifies both the code of ``RMV::VisitCallExpr`` and the code generated by it.
Fixes #801.

2024-03-06 06:01 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      auto* it = std::begin(block) + insertionPoint;
We should spell out the types here.

2024-03-06 10:24 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      (arg->IgnoreImplicit()->isLValue() && utils::isTriviallyCastableArg(arg))) {
Can you write the code in C++ that this function is supposed to detect and based on that make a cast? That is, which types won't be trivially castable?

2024-03-06 14:35 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      (arg->IgnoreImplicit()->isLValue() && utils::isTriviallyCastableArg(arg))) {
For instance, ``float`` is not trivially castable to ``double``. The thing that is important here is that we cannot cast ``float*`` to ``double*`` (at least not in the sense of preserving the underlying value). Therefore, we cannot pass the derivative of the argument to the pullback. We need a helper variable for this (in this case, of type ``double``).

2024-03-06 14:38 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      (arg->IgnoreImplicit()->isLValue() && utils::isTriviallyCastableArg(arg))) {
I guess you are talking about the cases where we have an out parameter (something passed by reference). Otherwise we can just do a c-style cast.

2024-03-07 12:05 UTC, parth-07 commented
The work in this pull request seems good. Thank you for proactively trying to improve one of the most complicated components in the codebase. However, I think we may need to look at the issue and the solution more closely.

Please correct me if I am wrong anywhere. My autodiff skills are a bit rusty now.

Given a function:

```cpp
double do_something(double p_u, double p_v) { ... }
```

Considering the primal code is `r = do_something(u, v)`, then previously, we used to differentiate a call to `do_something` as follows:

```cpp
double _r_d0 = _d_res;
double _grad0 = 0;
double _grad1 = 0;
do_something_pullback(u, v, _r_d0, _grad0, _grad1);
double _r0 = _grad0;
double _r1 = _grad1;
*_d_u += _r0;
*_d_v += _r1
```

With your patch, the same call will be differentiated as:

```cpp
double _r_d0 = _d_res;
do_something_pullback(u, v, _r_d0, &*_d_u, &*_d_v);
```

The above two differentiated codes look similar and it appears that they should bring the same result mathematically. However, that's not the case. This is because of two reasons: 
 - a function call hides assignment operations: assigning values of arguments to parameters
 - Argument and parameters are different mathematical variables and therefore they should not share adjoint variables.

Let's look at what happens in a function call more closely.

**Primal code**

```cpp
r = do_something(u, v); // u and v are passed by value
```

This call can be made more clear by expanding it as follows:

```cpp
double p_u = u;
double p_v = v;

do_something(p_u, p_v); // p_u, and p_v are passed by reference
```

In the original case, `u` and `v` are passed by value and assignments to `p_u` and `p_v` happens implicitly. We cannot see it but it's very much there. Now, why does this matter? In the second case, can we use the adjoint variables `_d_u` and `_d_v` for representing the adjoints of `p_u` and `p_v`? No, of course not. We need different adjoint variables for `p_u` and `p_v` because `p_u` is not the same variable as `u` and `p_v` is not the same variable as `v`. Using the same logic, we cannot use the adjoints of `u` and `v` when passing grad variables to `do_something_pullback`. 

A practical example where this distinction matters:

```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>
#define show(x) std::cout << #x << ": " << x <<"\n";

double reset(double u) {
    u = 0;
    return u;
}

double fn(double u, double v) {
    double res = u + v;
    res += reset(u);
    res += u;
    return res;
}

int main() {
    auto fn_grad = clad::gradient(fn);
    double u = 3, v = 5, du = 0, dv = 0;
    fn_grad.execute(u, v, &du, &dv);
    show(du);
    show(dv);
}
```

With this patch, the above code (incorrectly) outputs:

```
du: 1
dv: 1
```

The correct output is:

```
du: 2
dv: 1
```

2024-03-07 12:37 UTC, parth-07 requested changes
Please see the above comment for details.

2024-03-08 14:20 UTC, PetroZarytskyi commented
@parth-07 
Hi Parth. Thank you for your comment. I agree with your reasoning, I got confused. I still think this PR can be fixed to actually simplify things without breaking anything. Even though the changes will not be that drastic. But it needs more work.

2024-03-12 20:34 UTC, parth-07 commented
> I still think this PR can be fixed to actually simplify things without breaking anything.

That's great! It's important to simplify the call differentiation component. It has grown really complex over the years.

2024-03-12 21:58 UTC, PetroZarytskyi commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      auto* it = std::begin(block) + insertionPoint;
Done.

2024-03-14 15:18 UTC, parth-07 commented
Hi @PetroZarytskyi 

Can you please add more details in the pull-request description / commit-message regarding how the pullback calls are being simplified?

2024-03-14 15:59 UTC, PetroZarytskyi commented
Hi @parth-07, I updated the PR message as well as the #801 issue.

2024-03-16 09:15 UTC, parth-07 approved these changes
Looks good apart from the few minor comments.

2024-03-16 09:15 UTC, parth-07 commented on include/clad/Differentiator/VisitorBase.h
>      clang::Expr* GetMultiArgCentralDiffCall(
Unrelated to the changes in this PR: We should probably move this function to ReverseModeVisitor.

2024-03-16 11:30 UTC, parth-07 commented on include/clad/Differentiator/CladUtils.h
> +    bool IsReferenceOrPointerArg(const clang::Expr* arg);
Oh, the function suffix has been changed from `Type` to `Arg`.

2024-03-16 12:47 UTC, PetroZarytskyi commented on lib/Differentiator/CladUtils.cpp
> +      bool isRefType = arg->isLValue() && !isa<MaterializeTemporaryExpr>(arg);
``arg`` is supposed to be the argument expression passed to the function. If the function expects a ref-type argument, then ``arg`` is an l-value (usually a ``DeclRefExpr``). But when it expects a non-ref type argument, it is implicitly converted to an r-value. The AST of ``arg`` will look somewhat like this:
```
ImplicitCastExpr <l-value to r-value>
-DeclRefExpr
```
So arg will be an r-value. At least this is my understanding.

2024-03-18 08:03 UTC, PetroZarytskyi commented on include/clad/Differentiator/VisitorBase.h
>      clang::Expr* GetMultiArgCentralDiffCall(
I fixed this.

2024-03-18 21:49 UTC, merged