Differentiate for loop condition
vgvassilev/clad pull request #818
Opened 2024-03-12 01:02 UTC by rohanjulka19

Fixes #746 - Incorrect differentiation of loop conditions in reverse mode

2024-03-12 05:37 UTC, vgvassilev commented
Can you add tests?

2024-03-12 20:41 UTC, parth-07 requested changes
The solution needs to be corrected. The for-loop `condition` should be differentiated in each iteration. 
The solution in this pull-request generates incorrect derivative for the example show below:

```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>
#define show(x) std::cout << #x << ": " << x << "\n";

double fn(double i, double j) {
    double res = 0;
    for (int c = 0; (res += i * j); ++c) {
        if (c == 2)
            break;
    }
    return res;
}

int main() {
    auto fn_grad = clad::gradient(fn);
    double u = 3, v = 5;
    double du = 0, dv = 0;
    fn_grad.execute(u, v, &du, &dv);
    show(du);
    show(dv);
}
```

**Output**
du: 5
dv: 3

**Expected Output**
du: 10
dv: 6

2024-03-13 08:40 UTC, rohanjulka19 commented
Oh right ok, will fix this

2024-03-13 10:24 UTC, rohanjulka19 commented
hi @parth-07  for c == 2 condition du and dv will be 15 and 9 right ? cause the loop will run 3 times.

2024-03-13 12:17 UTC, parth-07 commented
>  hi @parth-07 for c == 2 condition du and dv will be 15 and 9 right ? cause the loop will run 3 times.

Oh, yes. You are right.

2024-03-14 12:07 UTC, rohanjulka19 commented
hi @parth-07, I have added the differentiation of condition inside the loop body and also at the end of the loop. This is done because for the value where condition is false, the condition is exeucted but the loop body is not executed. So we need to add a extra differentiation step after loop body. This does not seem to be working for when we break at 1st or 2nd iteration and I am not able to understand why exactly. Can you just help me out here ?
```
void fn_grad(double i, double j, clad::array_ref<double> _d_i, clad::array_ref<double> _d_j) {
    double _d_res = 0;
    unsigned long _t0;
    int _d_c = 0;
    int c = 0;
    clad::tape<double> _t1 = {};
    clad::tape<bool> _t3 = {};
    clad::tape<unsigned long> _t4 = {};
    double res = 0;
    _t0 = 0;
    for (c = 0; clad::push(_t1, res) , ((res = i * j) , c < 5); ++c) {
        _t0++;
        bool _t2 = c == 0;
        {
            if (_t2) {
                {
                    clad::push(_t4, 1UL);
                    break;
                }
            }
            clad::push(_t3, _t2);
        }
        clad::push(_t4, 2UL);
    }
    goto _label0;
  _label0:
    _d_res += 1;
    {
        for (; _t0; _t0--)
            switch (clad::pop(_t4)) {
              case 2UL:
                ;
                {
                    _d_res += 0;
                    res = clad::pop(_t1);
                    double _r_d0 = _d_res;
                    _d_res -= _r_d0;
                    * _d_i += _r_d0 * j;
                    * _d_j += i * _r_d0;
                }
                --c;
                if (clad::pop(_t3)) {
                  case 1UL:
                    ;
                }
            }
        {
            _d_res += 0;
            res = clad::pop(_t1);
            double _r_d0 = _d_res;
            _d_res -= _r_d0;
            * _d_i += _r_d0 * j;
            * _d_j += i * _r_d0;
        }
    }
}
```
**Output:**
du: 0
dv:0

**Expected:**
du: 5
dv:3

2024-03-15 13:34 UTC, rohanjulka19 commented
1. I differentiated cond twice adding one inside the loop and one outside the loop
2. Now RHS of comma operator is differentiated and added to block first this is needed because if there are multiple condition expression the last one should decide the value to be differentiated.

2024-03-16 09:35 UTC, parth-07 requested changes
> I differentiated cond twice adding one inside the loop and one outside the loop

This is correct.

The below example is still give wrong result:

```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>
#define show(x) std::cout << #x << ": " << x << "\n";

double fn(double i, double j) {
    double res = 0;
    for (int c = 0; true && (res += i * j); ++c) {
        if (c == 0)
            break;
    }
    return res;
}

int main() {
    auto fn_grad = clad::gradient(fn);
    double u = 3, v = 5;
    double du = 0, dv = 0;
    fn_grad.execute(u, v, &du, &dv);
    show(du);
    show(dv);
}
```

2024-03-20 15:48 UTC, vgvassilev commented
@rohanjulka19, can you take a look at the comment and possibly make progress here?

2024-03-20 16:22 UTC, rohanjulka19 commented
Hi @vgvassilev , yeah sorry should have acknowledged here, I had seen the comment. I am currently working on adding && operator support in the VisitBinaryOperator function it's just that I am facing a issue that I haven't figured out how to solve. Basically for expression a && b && c it needs to have concentric if conditions i.e if(a) { df/da if(b) {df/db} } but since we start parsing from rightmost expression I am unable to add the right hand side expression's differentiation inside the IF block of the left expression as I am not sure how to pass it to the left hand side expression when visiting the LHS expression. So was just figuring that out plus I had university work so wasn't able to give it much time, I will try to push it today by end of day (GMT+1).

2024-03-20 16:25 UTC, vgvassilev commented
Is that work in the context of gsoc and if so, can you send me an email?

2024-03-23 14:03 UTC, rohanjulka19 commented
@parth-07
 Have added && support in expressions  but right now it doesn't work with other binary operators correctly.
Also added one cleanup - now we are checking whether if condtion has body and only then adding the if stmt.
Is this code fine ? If yes I will add the support for OR also in a similar fashion and fix the issue of using && with other binary operators

2024-03-23 15:01 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        bodyDiff.updateStmtDx(unwrapIfSingleStmt(condDiff->getStmt_dx()));
This branch seems not tested. Can you add a test case?

2024-03-23 15:01 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        bodyDiff.updateStmt(unwrapIfSingleStmt(condDiff->getStmt()));
Likewise.

2024-03-23 15:41 UTC, rohanjulka19 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        bodyDiff.updateStmt(unwrapIfSingleStmt(condDiff->getStmt()));
have added test case to check both

2024-03-23 15:57 UTC, rohanjulka19 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        bodyDiff.updateStmt(unwrapIfSingleStmt(condDiff->getStmt()));
ok found a small bug will fix it in sometimes

2024-03-23 16:22 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        bodyDiff.updateStmt(unwrapIfSingleStmt(condDiff->getStmt()));
According to codecov, no test takes this branch.

2024-03-23 16:34 UTC, rohanjulka19 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        bodyDiff.updateStmt(unwrapIfSingleStmt(condDiff->getStmt()));
ok is there a way to know locally to know if a line is covered or not ? should I just add asserts to know if it reached there ?

2024-03-23 16:55 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        bodyDiff.updateStmt(unwrapIfSingleStmt(condDiff->getStmt()));
Maybe adding an printf or assert locally is one of the best options.

2024-03-23 20:43 UTC, parth-07 requested changes
Thank you for persistently working on this. It was very nice to see the exhaustive set of tests that you have added.

The pull request still needs some changes. Some modifications relate to the differentiation of `if` statements. Are those changes required to fix this issue? If not, then we should remove them.

Additionally, the behaviour of the derived loop does not seem completely correct for the `continue` statement. Loop-condition and iterator-expression derivatives are skipped in the reverse-pass when the `continue` statement is hit in the forward-pass. Loop condition and iterator-expression should only be skipped when `break` statement is hit in the forward-pass. An example where this results in incorrect derivative:

```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>

#define show(x) std::cout << #x << ": " << x << "\n";

double fn(double u, double v) {
    double res = 0;
    for (int i = 0; res += u; i++) {
        if (i == 0)
            continue;
        if (i == 1)
            break;
    }
    return res;
}

int main() {
    auto d_fn = clad::gradient(fn);
    double u = 3, v = 5;
    double du, dv;
    du = dv = 0;
    d_fn.execute(u, v, &du, &dv);
    show(du);
    show(dv);
}
```

**Output:**
du: 1
dv: 0

**Expected Output**
du: 2
dv: 0

2024-03-24 11:07 UTC, rohanjulka19 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    StmtDiff condExpr;
The current approach I am using for implementing the && operator is by creating it's equivalent if condition and then visiting the if conidition hence forwarding all the responsibility of generating the forward and reverse pass code of the expression on the VisitIfStmt code. So these changes are required for correct differentiation of && expression.

2024-03-24 11:07 UTC, rohanjulka19 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      std::tie(condDiff, condExprDiff) = DifferentiateSingleExpr(FS->getCond());
Yeah I guess that can be used will change this

2024-03-24 11:08 UTC, rohanjulka19 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    } else if (opCode == BO_LAnd) {
yeah will do that will move the if stmt related changes also to that PR then ?

2024-03-24 11:49 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    } else if (opCode == BO_LAnd) {
Yes, sounds good.

2024-05-19 07:31 UTC, vgvassilev commented
@rohanjulka19, @parth-07 what is the fate of this PR?

2024-05-19 09:00 UTC, rohanjulka19 commented
hi @vgvassilev , I have some other important work that I had anticipated to be finished by now but is still under progress. So I guess I will be able to work on this and move this to completion in June only.

2024-06-04 15:07 UTC, rohanjulka19 commented
Hi,
I am trying to get different conditions fixed but facing a issue here for this code 

```
double fn(double i, double j) {
  double res = 0;
  for (int c =0; (res  += i * j), c<3; ++c) {
    if (c == 1) {
      res = i * j ;
      continue;
    }
  }
  return res;
}
```

The output for 
u: 3    v: 5

should be 
 du :15  dv:9 
 
 whereas the it is returning 10 and 6 
 
 the generated code is this 
 
```
void fn_grad(double i, double j, double *_d_i, double *_d_j) {
    double _d_res = 0;
    double _d_x = 0;
    unsigned long _t0;
    int _d_c = 0;
    int c = 0;
    clad::tape<double> _t1 = {};
    clad::tape<double> _t2 = {};
    clad::tape<bool> _cond0 = {};
    clad::tape<double> _t3 = {};
    clad::tape<unsigned long> _t4 = {};
    double res = 0;
    double x = 0;
    _t0 = 0UL;
    clad::push(_t2, res);
    for (c = 0; (res += i * j) , c < 3; ++c) {
        clad::push(_t1, res);
        _t0++;
        {
            clad::push(_cond0, c == 1);
            if (clad::back(_cond0)) {
                clad::push(_t3, res);
                res = i * j;
                {
                    clad::push(_t4, 1UL);
                    continue;
                }
            }
        }
        clad::push(_t4, 2UL);
    }
    goto _label0;
  _label0:
    _d_res += 1;
    {
        for (; _t0; _t0--) {
            switch (clad::pop(_t4)) {
              case 2UL:
                ;
                --c;
                {
                    if (clad::back(_cond0)) {
                      case 1UL:
                        ;
                        {
                            res = clad::pop(_t3);
                            double _r_d2 = _d_res;
                            _d_res -= _r_d2;
                            *_d_i += _r_d2 * j;
                            *_d_j += i * _r_d2;
                        }
                    }
                    clad::pop(_cond0);
                }
            }
            {
                _d_res += 0;
                res = clad::pop(_t1);
                double _r_d0 = _d_res;
                *_d_i += _r_d0 * j;
                *_d_j += i * _r_d0;
            }
        }
        {
            _d_res += 0;
            res = clad::pop(_t2);
            double _r_d1 = _d_res;
            *_d_i += _r_d1 * j;
            *_d_j += i * _r_d1;
        }
    }
}

```

Now in the code of continue block in the swtich stmt 

```
  {
      res = clad::pop(_t3);
      double _r_d2 = _d_res;
      _d_res -= _r_d2;
      *_d_i += _r_d2 * j;
      *_d_j += i * _r_d2;
  }
```

we are removing the old value of _d_res which I am not able to understand why we are doing exactly (other than for case like res = res as mentioned in the comment in the code [here](https://github.com/vgvassilev/clad/blob/master/lib/Differentiator/ReverseModeVisitor.cpp#L2268)) . Additionaly, this might sound stupid but shouldn't  _d_i and _d_j be resetted also, as if we write something like :- res = i * j then doesn't this mean that res's value now only depends on the current equation i.e i * j and partial derivative of i or j should be calculated just based on that only.

2024-06-04 17:43 UTC, vgvassilev commented
Can you rebase the pull request first?

@parth-07, what is your take?

2024-06-06 18:24 UTC, rohanjulka19 commented
ok turns out just the order in which they are executed had to be changed now it seems to be working. 

Separated the related to IF stmt changes and && support to another PR - https://github.com/vgvassilev/clad/pull/923

> Can we use `DifferentiateSingleStmt` instead of `DifferentiateSingleExpr` here? `DifferentiateSingleExpr` is more complicated, and I prefer to use it only when it is strictly required.
 
 We actually need to use DifferentiateSingleStmt here because we need the expression diff as well as the stmts added to the reverse and forward block 

For handling break stmt - Added a variable in break stmt which is set to 1 in forward pass and in reverse pass loop condition code is executed one less time.

2024-07-08 04:23 UTC, parth-07 reviewed
Thank you for the pull-request. Overall, the changes seem good. I will need some more time to review the pull-request in detail.

2024-07-11 14:50 UTC, parth-07 requested changes

2024-07-11 14:50 UTC, parth-07 commented on include/clad/Differentiator/ReverseModeVisitor.h
> +    clang::Expr* m_CurrentBreakFlagExpr;
Please add documentation here regarding the use of `m_CurrentBreakFlagExpr`.

2024-07-11 14:50 UTC, parth-07 commented on include/clad/Differentiator/ReverseModeVisitor.h
> -      /// Builds and returns a literal expression of type `std::size_t` with
Did you remove this documentation for the below function by mistake? If so, can you please add it back?

2024-07-11 14:50 UTC, parth-07 commented on include/clad/Differentiator/ReverseModeVisitor.h
> +      clang::Expr* CreateCFTapeBackExprForCurrentCase();
Please add function documentation comments.

2024-07-11 14:50 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      Ldiff = Visit(L, zero);
Does the order of differentiation of `Ldiff` and `Rdiff` matter for this functionality added by this pull-request?

2024-07-13 15:43 UTC, rohanjulka19 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      Ldiff = Visit(L, zero);
Hi yeah there is a case where it was causing issue which is

```
 for (int c = 0; (res = i * j), (res=2*i*j), c < 3; ++c) {}
```

In this loop condition the right one should get executed first, in reverse pass otherwise it will return di - 5, dj-3 but it should return di-10, dj-6.

2024-07-14 19:36 UTC, parth-07 reviewed
The changes looks good. Can you please update the 'test/CUDA/GradientCuda.cu' test?

2024-07-14 21:02 UTC, rohanjulka19 commented
> The changes looks good. Can you please update the 'test/CUDA/GradientCuda.cu' test?

I have updated the Cuda test now it is passing. Can't seem to figure out why a test case is not working on x86.

2024-07-15 09:43 UTC, vgvassilev commented
@MihailMihov, this failure seems to be similar to what you've been hunting down?

2024-07-15 13:01 UTC, MihailMihov commented
> @MihailMihov, this failure seems to be similar to what you've been hunting down?

Seems like it's the same thing, in fact I'm not sure if one of the numbers isn't the exact same that I got somewhere. I'll see whether it happens on my machine too, like the other issue.

2024-07-15 22:15 UTC, MihailMihov commented
Well I checked out your branch, but it seems like the issue is different. I had a really stupid error (uninitialized variable in my test). I ran your test with LLVM's MemorySanitizer and there is an uninitialized value here too, but it seems to be coming from one of the tapes.
```
==1626607==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55a8d77c8230 in main /home/mihail/dev/clad/test/Gradient/Loops.C:2666:3
    #1 0x7f3ac4a5f2df  (/usr/lib64/libc.so.6+0x262df)
    #2 0x7f3ac4a5f398 in __libc_start_main (/usr/lib64/libc.so.6+0x26398)
    #3 0x55a8d772b374 in _start (/home/mihail/dev/clad/build/ReverseLoops.out+0x32374)

  Uninitialized value was stored to memory at
    #0 0x55a8d780e329 in fn30_grad(double, double, double*, double*) /home/mihail/dev/clad/test/Gradient/../../include/clad/Differentiator/Tape.h
    #1 0x55a8d77c7c8f in fn30_grad(double, double, void*, void*) /home/mihail/dev/clad/test/Gradient/Loops.C:1:1
    #2 0x55a8d77c7c8f in _ZN4clad25execute_with_default_argsILb1EJEPFvddPvS1_EJiiRA5_dPdEJddS1_S1_ETnNSt9enable_ifIXT_EbE4typeELb1EEENS_15function_traitsIT1_E11return_typeENS_4listIJDpT0_EEESB_NSE_IJDpT3_EEEDpOT2_ /home/mihail/dev/clad/test/Gradient/../../include/clad/Differentiator/Differentiator.h:123:12
    #3 0x55a8d77c7c8f in void clad::CladFunction<void (*)(double, double, void*, void*), clad::NoObject, true>::execute_helper<void (*)(double, double, void*, void*), int, int, double (&) [5], double*>(void (*)(double, double, void*, void*), int&&, int&&, double (&) [5], double*&&) /home/mihail/dev/clad/test/Gradient/../../include/clad/Differentiator/Differentiator.h:267:14
    #4 0x55a8d77c7c8f in std::enable_if<!std::is_same<void (*)(double, double, void*, void*), clad::NoFunction*>::value, void>::type clad::CladFunction<void (*)(double, double, void*, void*), clad::NoObject, true>::execute<int, int, double (&) [5], double*, void (*)(double, double, void*, void*)>(int&&, int&&, double (&) [5], double*&&) /home/mihail/dev/clad/test/Gradient/../../include/clad/Differentiator/Differentiator.h:218:14
    #5 0x55a8d77c7c8f in main /home/mihail/dev/clad/test/Gradient/Loops.C:2666:3
    #6 0x7f3ac4a5f2df  (/usr/lib64/libc.so.6+0x262df)

  Uninitialized value was created
    <empty stack>

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/mihail/dev/clad/test/Gradient/Loops.C:2666:3 in main
Exiting
```
In order to see a more detailed stack trace I'd need to compile clad instrumented with MSan, but I couldn't figure it out today, I'll try to get you a better stack trace tomorrow.

2024-07-16 02:19 UTC, rohanjulka19 commented
ok thanks to @MihailMihov, turns out there was a variable which wasn't initialised and was causing the test to fail. Now that it is initialised to zero, the test is passing. The variable is _d_cond which is added to ensure that while differentiating expression containing && operator, the expression which is then assigned to the cond variable gets differentiated.
```
cond = (c==0) && (res += i *j)
``` 

@MihailMihov Not sure if this is related to the warning you caught.

2024-07-17 20:42 UTC, parth-07 approved these changes

2024-07-18 05:37 UTC, merged