[WIP] Add clang 18 support
vgvassilev/clad pull request #824
Opened 2024-03-15 19:47 UTC by mcbarton

This PR will add support for clang 18
Fixes https://github.com/vgvassilev/clad/issues/805

2024-03-20 14:03 UTC, vgvassilev commented on lib/Differentiator/CladUtils.cpp
> +          StrTy = clad_compat::getConstantArrayType(C, CharTyConst,
We should probably make this change in `clad_compat::getConstantArrayType`.

2024-03-20 14:03 UTC, vgvassilev commented on lib/Differentiator/HessianModeVisitor.cpp
> +          clad_compat::getConstantArrayType(C, CharTyConst,
If we address the previous comment, this change is not going to be needed.

2024-03-20 14:03 UTC, vgvassilev commented on tools/ClangPlugin.cpp
> +          if (llvm::sys::path::stem(P).endswith("clad")) {
Instead of making this a macro-based code, can we replace the implementation with std::string. Eg.
std::string PEnd = llvm::sys::path::stem(P);
...

2024-03-20 14:55 UTC, mcbarton commented on CMakeLists.txt
> +  set(CLANG_MAX_SUPPORTED "19.0.0")
I didn't know what it would be for CLANG_MAX_SUPPORTED using 18 . Would it be 18.x.x ?

2024-03-20 15:01 UTC, mcbarton commented on lib/Differentiator/StmtClone.cpp
> +#endif
@vgvassilev any suggestions on what the solution the issue with CXXThisExpr might be? I thought that an extra argument had been added in clang-18, after it complained about having no CXXThisExpr with 3 arguments.  When I tried this solution though, the CI point out that the CXXThisExpr I had chosen was implicitly declared private.

2024-03-21 16:19 UTC, vgvassilev commented on lib/Differentiator/StmtClone.cpp
> +#endif
It probably got a `CXXThisExpr::Create` method. We should probably use `DEFINE_CREATE_EXPR` for it when the clang version is greater than 17?

2024-03-23 16:58 UTC, vgvassilev commented on lib/Differentiator/StmtClone.cpp
> +   DEFINE_CLONE_EXPR(CXXThisExpr, (Node->getSourceRange().getBegin(), Node->getType(), Node->isImplicit(),Node->getValueKind()))
```suggestion
   DEFINE_CREATE_EXPR(CXXThisExpr, (Node->getSourceRange().getBegin(), Node->getType(), Node->isImplicit(),Node->getValueKind()))
```

2024-03-23 21:25 UTC, vgvassilev commented on lib/Differentiator/StmtClone.cpp
> +   DEFINE_CREATE_EXPR(CXXThisExpr, (Node->getSourceRange().getBegin(), Node->getType(), Node->isImplicit(),Node->getValueKind()))
```suggestion
   DEFINE_CREATE_EXPR(CXXThisExpr, (Ctx, Node->getSourceRange().getBegin(), Node->getType(), Node->isImplicit()))
```

2024-03-24 18:57 UTC, mcbarton commented
@vgvassilev It is now building clad with clang-18 but it doesn't pass all the tests. It says that it is expected that 2 will fail, but 5 tests fail. Which 2 are expected to fail?

2024-03-26 12:02 UTC, alexander-penev commented on include/clad/Differentiator/Compatibility.h
>  #define CLAD_COMPAT_CLANG7_UnaryOperator_ExtraParams , Node->canOverflow()
Because this substitution is already unconditional, i.e. for all supported versions, not just post 7, it is good to find and replace this in all files where it is used.
We must find "CLAD_COMPAT_CLANG7_UnaryOperator_ExtraParams" everywhere in the Clad files and replace it with ", Node->canOverflow()".

2024-03-26 12:06 UTC, alexander-penev commented on include/clad/Differentiator/Compatibility.h
> +
This is also now unconditional and the change can be carried over from Compatibility.h into the other Clad files.

2024-03-26 12:11 UTC, alexander-penev commented on include/clad/Differentiator/Compatibility.h
> -
Is this ported over to the Clad code?
i.e.
Has "Node->getIdentType()" been changed in the other Clad's files to "Node->getIdentKind()"?

2024-03-26 12:17 UTC, alexander-penev commented on include/clad/Differentiator/Compatibility.h
> +
Another already unconditional moment. Good readability of the code will be achieved if clad_comapt::CXXOperatorCallExpr_Create calls are replaced accordingly in the other files and removed from Compatibility.h

2024-03-26 12:18 UTC, alexander-penev commented on include/clad/Differentiator/Compatibility.h
> +
Another already unconditional moment. Good readability of the code will be achieved if clad_comapt::CaseStmt_Create calls are replaced accordingly in the other files and removed from Compatibility.h

2024-03-26 12:19 UTC, alexander-penev commented on include/clad/Differentiator/Compatibility.h
> +#define CLAD_COMPAT_CLANG8_Ctx_ExtraParams Ctx,
Another already unconditional moment. It just needs to be replaced in all other files.
CLAD_COMPAT_CLANG8_Ctx_ExtraParams -> Ctx,

2024-03-26 12:24 UTC, alexander-penev commented on include/clad/Differentiator/Compatibility.h
>  }
Another already unconditional moment.
clad_compat::CXXMethodDecl_getThisType(ref,method) -> method->getThisType()

2024-03-26 12:35 UTC, alexander-penev commented on include/clad/Differentiator/StmtClone.h
>      DECLARE_CLONE_FN(ValueStmt)
The idea of Compatibility.h is to isolate all version-related parts of the code in one place. Thus, there are dozens of places where such a conditional compilation is not to be found.

This code should be properly ported to Compatilbility.h. each this is a bit more difficult than a simple "#ifdef", but it pays off.

2024-03-26 12:35 UTC, alexander-penev commented on include/clad/Differentiator/VisitorBase.h
> +      #endif // CLANG_VERSION_MAJOR > 17
The idea of Compatibility.h is to isolate all version-related parts of the code in one place. Thus, there are dozens of places where such a conditional compilation is not to be found.

This code should be properly ported to Compatilbility.h. each this is a bit more difficult than a simple "#ifdef", but it pays off.

2024-03-26 12:35 UTC, alexander-penev commented on lib/Differentiator/CladUtils.cpp
> +          #endif
The idea of Compatibility.h is to isolate all version-related parts of the code in one place. Thus, there are dozens of places where such a conditional compilation is not to be found.

This code should be properly ported to Compatilbility.h. each this is a bit more difficult than a simple "#ifdef", but it pays off.

2024-03-26 12:36 UTC, alexander-penev commented on lib/Differentiator/CladUtils.cpp
> +      #endif
The idea of Compatibility.h is to isolate all version-related parts of the code in one place. Thus, there are dozens of places where such a conditional compilation is not to be found.

This code should be properly ported to Compatilbility.h. each this is a bit more difficult than a simple "#ifdef", but it pays off.

2024-03-26 12:36 UTC, alexander-penev commented on lib/Differentiator/StmtClone.cpp
> +
The idea of Compatibility.h is to isolate all version-related parts of the code in one place. Thus, there are dozens of places where such a conditional compilation is not to be found.

This code should be properly ported to Compatilbility.h. each this is a bit more difficult than a simple "#ifdef", but it pays off.

2024-03-26 12:42 UTC, alexander-penev commented on lib/Differentiator/StmtClone.cpp
> +  #if CLANG_VERSION_MAJOR < 18
The idea of Compatibility.h is to isolate all version-related parts of the code in one place. Thus, there are dozens of places where such a conditional compilation is not to be found.

This code should be properly ported to Compatilbility.h. each this is a bit more difficult than a simple "#ifdef", but it pays off.

2024-03-26 12:42 UTC, alexander-penev commented on lib/Differentiator/VisitorBase.cpp
> +    #endif
The idea of Compatibility.h is to isolate all version-related parts of the code in one place. Thus, there are dozens of places where such a conditional compilation is not to be found.

This code should be properly ported to Compatilbility.h. each this is a bit more difficult than a simple "#ifdef", but it pays off.

2024-03-26 12:44 UTC, alexander-penev requested changes
I made some comments about Compatibility.h. It is good that some changes are made before we accept this PR.

2024-03-26 13:05 UTC, mcbarton commented
> I made some comments about Compatibility.h. It is good that some changes are made before we accept this PR.

@alexander-penev thanks for the feedback. I'll try to get the majority addressed by sometime tomorrow. I'll link the individual commits with your messages, so that you can see what I am trying to address in each, in case its not obvious from the commit message.

2024-03-26 15:36 UTC, mcbarton commented on include/clad/Differentiator/StmtClone.h
>      DECLARE_CLONE_FN(ValueStmt)
I believe this comment was a mistake. It doesn't appear to be pointing to something that needs changing.

2024-03-26 16:33 UTC, alexander-penev commented on include/clad/Differentiator/StmtClone.h
>      DECLARE_CLONE_FN(ValueStmt)
#if CLANG_VERSION_MAJOR > 8
has no place outside of Compatibility.h

Of course, it has nothing to do with version 18 or the changes made in this PR, but it is something that needs to be fixed anyway, because it is related to the similar changes in this PR. If it is not done here it will have to be done in a separate PR.

2024-03-26 16:37 UTC, mcbarton commented on include/clad/Differentiator/StmtClone.h
>      DECLARE_CLONE_FN(ValueStmt)
@alexander-penev Ok, I'll investigate this after I have resolved the other issues raised.

2024-03-26 17:54 UTC, mcbarton commented on include/clad/Differentiator/VisitorBase.h
> +      #endif // CLANG_VERSION_MAJOR > 17
@alexander-penev Could you make a suggestion on how to move this to Compatibility.h ? I made an attempt to move it, but even if it had worked I don't think it was the right way to do it.

2024-03-26 18:24 UTC, mcbarton commented on lib/Differentiator/StmtClone.cpp
> +
Does this need to be moved? It seems similar to what has already been implemented in StmtClone.cpp here https://github.com/mcbarton/clad/blob/7741c3c5580b06a593bdafd485a955b7a31d7573/lib/Differentiator/StmtClone.cpp#L244C1-L257C7 for SubstNonTypeTemplateParmExpr .

2024-03-26 19:32 UTC, mcbarton commented on CMakeLists.txt
> +  set(CLANG_MAX_SUPPORTED "19.0.0")
18.x.x didn't work, so I have reverted back to 19.0.0 . I will leave it like this unless you have another idea of what to try for CLANG_MAX_SUPPORTED, etc.

2024-03-27 01:06 UTC, alexander-penev commented on include/clad/Differentiator/VisitorBase.h
> +      #endif // CLANG_VERSION_MAJOR > 17
We could add a clad_compat::ActOnLambdaExpr(S, loc, body, scope) function, but this may lead to unnecessary additional calculation of the last parameter in cases of clang>17. I recommend another approach:
```suggestion
        clang::Expr* lambda = S.ActOnLambdaExpr(noLoc, body/*,*/
          CLAD_COMPAT_CLANG17_ActOnLambdaExpr_getCurrentScope_ExtraParam(V)).get();
```
In Compatibility.h must add this:
```
      #if CLANG_VERSION_MAJOR > 17
        #define CLAD_COMPAT_CLANG17_ActOnLambdaExpr_getCurrentScope_ExtraParam(V) /**/
      #else
        #define CLAD_COMPAT_CLANG17_ActOnLambdaExpr_getCurrentScope_ExtraParam(V) ,(V).getCurrentScope()
      #endif // CLANG_VERSION_MAJOR > 17
```

2024-03-27 01:07 UTC, alexander-penev commented on include/clad/Differentiator/VisitorBase.h
> +      #endif // CLANG_VERSION_MAJOR > 17
We could add a clad_compat::ActOnLambdaExpr(S, loc, body, scope) function, but this may lead to unnecessary additional calculation of the last parameter in cases of clang>17. I recommend another approach:
```suggestion
        clang::Expr* lambda = S.ActOnLambdaExpr(noLoc, body/*,*/
          CLAD_COMPAT_CLANG17_ActOnLambdaExpr_getCurrentScope_ExtraParam(V)).get();
```
In Compatibility.h must add this:
```
      #if CLANG_VERSION_MAJOR > 17
        #define CLAD_COMPAT_CLANG17_ActOnLambdaExpr_getCurrentScope_ExtraParam(V) /**/
      #else
        #define CLAD_COMPAT_CLANG17_ActOnLambdaExpr_getCurrentScope_ExtraParam(V) ,(V).getCurrentScope()
      #endif // CLANG_VERSION_MAJOR > 17
```

2024-03-27 01:24 UTC, alexander-penev commented on lib/Differentiator/StmtClone.cpp
> +
Yes, the problem here is the same as in 1-2 other places. When in the past we "let go" of some not very good change, then an avalanche of similar changes occurs.

If we don't fix it here and now (not just for version 18) we'll need another PR to fix what was not done very well before.

2024-03-27 11:22 UTC, mcbarton commented on include/clad/Differentiator/Compatibility.h
> +
@alexander-penev @vgvassilev can you make a suggestion? This is the last thing I need to change, before I can remove this code, but I have made multiple attempts to do without success. After this change has been made and the code mentioned in this issue removed, the PR is ready for another review.

2024-03-27 11:23 UTC, mcbarton commented
> @vgvassilev It is now building clad with clang-18 but it doesn't pass all the tests. It says that it is expected that 2 will fail, but 5 tests fail. Which 2 are expected to fail?

@alexander-penev which are the 2 tests which are expected to fail?

2024-03-27 13:20 UTC, mcbarton commented on include/clad/Differentiator/Compatibility.h
> +
I have now found a solution.

2024-03-27 20:54 UTC, alexander-penev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +                                , TOE->isListInitialization())
```suggestion
                                TOE->isListInitialization())
```

2024-03-27 20:54 UTC, alexander-penev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
>                               utils::GetValidSLoc(m_Sema)
```suggestion
                             utils::GetValidSLoc(m_Sema),
```

2024-03-27 20:54 UTC, alexander-penev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +                                 ,TOE->isListInitialization())
```suggestion
                                 TOE->isListInitialization())
```

2024-03-27 20:59 UTC, alexander-penev commented on lib/Differentiator/StmtClone.cpp
> +     Node->getOperatorLoc() , Node->canOverflow()
```suggestion
     Node->getOperatorLoc(), Node->canOverflow()
```

2024-03-28 00:58 UTC, alexander-penev commented
> > @vgvassilev It is now building clad with clang-18 but it doesn't pass all the tests. It says that it is expected that 2 will fail, but 5 tests fail. Which 2 are expected to fail?
> 
> @alexander-penev which are the 2 tests which are expected to fail?

@mcbarton @vgvassilev The two tests that are expected to fall don't matter because they are not part of the 5 that are currently falling.
As far as I've noticed the falling tests are mainly falling because of some change in function info printing in the new version 18 (I don't know if this can be set or if the check needs to be made more complicated). For example:
```
//CHECK: int f_darg0(int x) __attribute__((always_inline)) {
```

but the printed for the generated result is

```
__attribute__((always_inline)) int f_darg0(int x) {
```


One of the other tests seems to fail because (perhaps a new warning):
> ArrayInputsReverseMode.C:228:14: warning: variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]

or

> ArrayInputsReverseMode.C:228:14: note: read of non-const variable 'n' is not allowed in a constant expression

2024-03-30 14:13 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      newActiveSC = CaseStmt::Create(const_cast<ASTContext&>(m_Sema.getASTContext()), lhsClone, rhsClone, noLoc, noLoc, noLoc);
```suggestion
      newActiveSC = CaseStmt::Create(Ctx, lhsClone, rhsClone, noLoc, noLoc, noLoc);
```

2024-03-30 14:13 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    auto* newSC = CaseStmt::Create(const_cast<ASTContext&>(m_Sema.getASTContext()), lhsClone, rhsClone, noLoc, noLoc, noLoc);
```suggestion
    auto* newSC = CaseStmt::Create(Ctx, lhsClone, rhsClone, noLoc, noLoc, noLoc);
```

2024-03-30 14:15 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    CaseStmt* CS = CaseStmt::Create(const_cast<ASTContext&>(m_RMV.m_Context), counterLiteral, nullptr, noLoc, noLoc, noLoc);
```suggestion
    CaseStmt* CS = CaseStmt::Create(Ctx, counterLiteral, nullptr, noLoc, noLoc, noLoc);
```

2024-03-30 14:15 UTC, vgvassilev commented on lib/Differentiator/StmtClone.cpp
> +  CaseStmt* result = CaseStmt::Create(const_cast<ASTContext&>(Ctx), Clone(Node->getLHS()), Clone(Node->getRHS()), Node->getCaseLoc(), Node->getEllipsisLoc(), Node->getColonLoc());
```suggestion
  CaseStmt* result = CaseStmt::Create(Ctx, Clone(Node->getLHS()), Clone(Node->getRHS()), Node->getCaseLoc(), Node->getEllipsisLoc(), Node->getColonLoc());
```

2024-03-30 14:15 UTC, vgvassilev commented on tools/ClangPlugin.cpp
> +          }
Looks like we got some wrong indent here...

2024-03-31 04:31 UTC, alexander-penev approved these changes

2024-03-31 05:13 UTC, alexander-penev commented on CMakeLists.txt
> +  set(CLANG_MAX_SUPPORTED "19.0.0")
https://discourse.llvm.org/t/rfc-name-the-first-release-from-a-branch-n-1-0-instead-of-n-0-0/75384

In my opinion, following the new LLVM release scheme and what we've done so far we should do the following:
```suggestion
  set(CLANG_MIN_SUPPORTED 8.0)
  set(CLANG_MAX_SUPPORTED "18.1.x")
  set(CLANG_VERSION_UPPER_BOUND 18.2.0)
  set(LLVM_MIN_SUPPORTED 8.0)
  set(LLVM_MAX_SUPPORTED "18.1.x")
  set(LLVM_VERSION_UPPER_BOUND 18.2.0)
```

If a new version of LLVM appears i.e. version 18.2.x, then that means we have an LLVM ABI break and we need to upgrade (with or without Clad changes) our last supported version. If of course LLVM 19 comes out, then we should also upgrade our last supported version to 19.1.x, making the necessary changes and compatibility tests (as well as upgrade the minimally supported version to 9.0).

2024-03-31 05:22 UTC, alexander-penev commented on README.md
> +At the moment, LLVM/Clang 8.0.x - 18.x.x are supported.
```suggestion
At the moment, LLVM/Clang 8.0.x - 18.1.x are supported.
```

2024-03-31 05:46 UTC, alexander-penev commented on include/clad/Differentiator/Compatibility.h
>     const auto StringKind_Ordinary = clang::StringLiteral::StringKind::Ascii;
When there are changes we try to stick to the names in the latest version, for greater proximity to the new versions (easier help search, easier and clearer names, etc.).

```suggestion
   const auto StringLiteralKind_Ordinary = clang::StringLiteral::StringKind::Ascii;
```

2024-03-31 05:47 UTC, alexander-penev commented on include/clad/Differentiator/Compatibility.h
> +      const auto StringKind_Ordinary = clang::StringLiteral::StringKind::Ordinary;
```suggestion
      const auto StringLiteralKind_Ordinary = clang::StringLiteral::StringKind::Ordinary;
```

2024-03-31 05:47 UTC, alexander-penev commented on include/clad/Differentiator/Compatibility.h
> +      const auto StringKind_Ordinary = clang::StringLiteralKind::Ordinary;
```suggestion
      const auto StringLiteralKind_Ordinary = clang::StringLiteral::StringKind::Ordinary;
```

2024-03-31 06:02 UTC, alexander-penev commented on include/clad/Differentiator/Compatibility.h
> +#endif
```suggestion
//Clang 18 ArrayType::Normal -> ArraySizeModifier::Normal

#if LLVM_VERSION_MAJOR < 18
const auto ArraySizeModifier_Normal = ArrayType::Normal
#else
const auto ArraySizeModifier_Normal ArraySizeModifier::Normal
#endif
```
It's a good idea to avoid `#define` as much as possible.
I think it's easy here. In addition, in the code we will use `clad_compat::ArraySizeModifier_Normal`, which, apart from being closer to the current version as a name, shows that it is a matter of compatibility.

2024-03-31 06:07 UTC, alexander-penev commented on include/clad/Differentiator/Compatibility.h
> +#endif
```suggestion
#if LLVM_VERSION_MAJOR < 18
const auto ElaboratedTypeKeyword_None ETK_None
#else
const auto ElaboratedTypeKeyword_None ElaboratedTypeKeyword::None
#endif
```
We use where necessary as `clad_compat::ElaboratedTypeKeyword_None`.

2024-03-31 06:46 UTC, alexander-penev commented on tools/ClangPlugin.cpp
> +          }
```suggestion
        if (llvm::sys::path::stem(P).ends_with("clad")) {
          CladSoPath = P;
          break;
        }
```

2024-03-31 19:47 UTC, mcbarton commented
@vgvassilev @alexander-penev I have addressed your feedback. This PR is ready further review

2024-04-01 10:37 UTC, vgvassilev commented
Thank you @mcbarton and @alexander-penev!

2024-04-01 10:38 UTC, vgvassilev commented
The codecov and clang-format complaints are bogus.

2024-04-01 10:38 UTC, merged