Fix issue #865 and allow conditions in if statements to affect the derivatives
vgvassilev/clad pull request #891
Opened 2024-05-14 17:18 UTC by gojakuch

The purpose of this PR is to fix the issue #865, but additionally I addressed the FIXME-comment in the VisitIfStmt method and now it's possible for conditions in if statements to affect the derivatives.

2024-05-14 17:19 UTC, gojakuch commented
Do we need special tests to be added for these features? I can do this in this PR as well

2024-05-15 16:55 UTC, vgvassilev commented
How about "Handle variable declarations in conditions of if-statements", then explain what this patch does and finish with fixes:...

We will need to update the PR description and title accordingly.

2024-05-16 06:19 UTC, vgvassilev commented
You need to update the commit message accordingly, too.

2024-05-16 10:24 UTC, parth-07 requested changes
Can you please add a test where if-condition has a side-effect that affects differentiation result?

2024-05-16 14:23 UTC, gojakuch commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      // way: forward: _t = cond; if (_t) { ... } clad::push(..., _t); reverse:
it has been changed automatically by my clang format for some reason

2024-05-16 14:31 UTC, vaithak commented on lib/Differentiator/ReverseModeVisitor.cpp
> -    // Sema::ActOnIfStmt, therefore we directly use the IfStmt constructor.
Do we need to delete this comment?

2024-05-16 14:36 UTC, gojakuch commented on lib/Differentiator/ReverseModeVisitor.cpp
> -    // Sema::ActOnIfStmt, therefore we directly use the IfStmt constructor.
condVarDecl is always set to nullptr here now, because it doesn't change anything, so I'm not sure if this is relevant. we generally don't need condVarDecl in the generated statement, only cond

2024-05-16 14:43 UTC, vaithak commented on lib/Differentiator/ReverseModeVisitor.cpp
> -    // Sema::ActOnIfStmt, therefore we directly use the IfStmt constructor.
So, would it make sense to use `ActOnIfStmt` now?

2024-05-16 14:54 UTC, vaithak commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      // way: forward: _t = cond; if (_t) { ... } clad::push(..., _t); reverse:
maybe changing it into a multiline comment style (/*  ... */) should fix it.

2024-05-16 15:39 UTC, vaithak approved these changes
Other than some clang formatting issues, this looks good to me.

2024-05-16 16:16 UTC, gojakuch commented on lib/Differentiator/ReverseModeVisitor.cpp
> -    // Sema::ActOnIfStmt, therefore we directly use the IfStmt constructor.
I think it's possible, but I'm not sure what benefit that would have.

2024-05-16 16:51 UTC, vgvassilev commented
Can we test the c++20 syntax:
```cpp
if (int a = 12; a < 0) {
}
```

2024-05-17 05:33 UTC, parth-07 approved these changes
Looks good to me.

This patch does not handle if-condition side-effects for all cases. The below example gives incorrect derivative:

```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>

#define show(x) std::cout << #x <<": " << x << "\n";

double fn(double u, double v) {
    double res = 0;
    double foo = v;
    res = foo;
    res += foo;
    if ((foo = u) > 10) {
        res += foo * v;
    }
    return res + foo;
}

int main() {
    auto fn_grad = clad::gradient(fn);
    double u, v;
    u = 3, v = 5;
    double du, dv;
    du = dv = 0;
    fn_grad.execute(u, v, &du, &dv);
    show(du);
    show(dv);
}
```
Output:
du: 0
dv: 3

Expected Output:
du: 1
dv: 2

This case can be handled separately in a different pull-request. Can you please create an issue for this example?

2024-05-17 05:33 UTC, parth-07 commented on test/Gradient/Gradients.C
> +  dx = 0;
You don't need to explicitly reset the value to 0. `TEST_GRADIENT` takes care of that.

2024-05-17 08:23 UTC, gojakuch commented on test/Gradient/Gradients.C
> +  dx = 0;
oh, I didn't know this, thanks

2024-05-17 09:09 UTC, gojakuch commented
> This patch does not handle if-condition side-effects for all cases
yeah I was afraid that it would be the case but the simple things I tested worked out. I'll open up an issue about it. at least some of them work now.

2024-05-17 09:17 UTC, gojakuch commented
> Can we test the c++20 syntax:
> 
> ```c++
> if (int a = 12; a < 0) {
> }
> ```

this doesn't work out well unfortunately. but it seems fixable.

2024-05-17 10:32 UTC, gojakuch commented
> > ```c++
> > if (int a = 12; a < 0) {
> > }
> > ```

fixed it

2024-05-17 11:41 UTC, vgvassilev commented
> > > ```c++
> > > if (int a = 12; a < 0) {
> > > }
> > > ```
> 
> fixed it

I do not see a test case.

2024-05-17 13:21 UTC, gojakuch commented
> I do not see a test case.

already added

2024-05-17 17:03 UTC, merged