Add support for condition declarations and assignments in for loops
vgvassilev/clad pull request #905
Opened 2024-05-23 18:07 UTC by gojakuch

These changes fix the differentiation of variable declarations in the for loops that used to result into wrong derivatives. The commit also tackles the problem of having an assignment operator that affects the derivative in the for loop condition.

Fixes: #273

2024-05-23 19:44 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +              .getExpr()) { // this adds support for assignments in conditions
Can you move the comments on a separate line before the statement that we are commenting on? That will help clang-format avoid the weird indentations...

2024-05-23 19:44 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +            cond)); // if it's an assignment operator we wrap it back into
Likewise.

2024-05-23 20:23 UTC, parth-07 commented
The fix does not work for all cases. In the case when the for-loop condition fails, we should run the derivative statement for the for-loop condition, but we do not. This leads to incorrect derivative in some cases. 

Reproducible example:

```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>
#define show(x) std::cout << #x << ": " << x << "\n";

double fn(double u, double v) {
    double res = 0;
    for (; (res = u * v) && false ;) {}
    return res;
}

int main() {
    auto fn_diff = clad::differentiate(fn, "u");
    show(fn_diff.execute(3, 5));
}
```
Output:
fn_diff.execute(3, 5): 0

Expected Output:
fn_diff.execute(3, 5): 5

2024-05-23 20:24 UTC, parth-07 requested changes
Please see my earlier comment for the case which produces wrong output with this solution.

2024-05-24 06:00 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +  // declaration in the condition (if any) needs to be differentiated
```suggestion
  // Declaration in the condition (if any) needs to be differentiated.
```

Our comments are full sentences starting with a capital letter and ending with punctuation. Can you fix the rest of the comments, too?

2024-05-24 12:40 UTC, gojakuch commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +  // declaration in the condition (if any) needs to be differentiated
okay, I will fix this together with what Parth asked for.

2024-05-24 13:17 UTC, parth-07 commented
It seems that we do not support logical operators in a for-loop conditions. Hence, support for conditions such as this `(res = u * v) && false` can be added in a separate pull-request. However, the below example should work with this pull request:

```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>
#define show(x) std::cout << #x << ": " << x << "\n";

double fn(double u, double v) {
    double res = u * v;
    for (; (res = 0) ;) {}
    return res;
}

int main() {
    auto fn_diff = clad::differentiate(fn, "u");
    show(fn_diff.execute(3, 5));
}
```

**Output:** 
fn_diff.execute(3, 5): 5

**Expected output:** 
fn_diff.execute(3, 5): 0

2024-05-24 14:54 UTC, gojakuch commented
> It seems that we do not support logical operators in a for-loop conditions.

I have already started working on this because of your initial suggestion. Adding this as a separate PR would require rewriting the changes made in this PR once again. I can just change the commit and PR messages to also include this once I'm done.

2024-05-25 10:43 UTC, parth-07 requested changes
It seems that currently for-loop condition is only differentiated if it's a binary operator. This additional check seems unnecessary and is incorrect. You should try to directly call `Visit(...)` function on the condition expression.

The below code gives an incorrect derivative due to the condition expression only being differentiated if it's a binary operator:

```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>
#define show(x) std::cout << #x << ": " << x << "\n";

double fn(double u, double v) {
    double res = 0;
    for (; !(res = u * v) ;) {}
    return res;
}

int main() {
    auto fn_diff = clad::differentiate(fn, "u");
    show(fn(3, 5));
    show(fn_diff.execute(3, 5));
}
```

**Output:**
fn_diff.execute(3, 5): 0

**Expected Output:**
fn_diff.execute(3, 5): 5

2024-05-25 10:43 UTC, parth-07 commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    // FIXME: here DifferentiateVarDecl is only used to clone the declaration
What other ways did you try before DifferentiateVarDecl?

2024-05-25 10:43 UTC, parth-07 commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    while (CastExpr* condCast = dyn_cast<CastExpr>(cond))
Can these two `while` loops be replaced by: `Expr::IgnoreParenImpCasts` function?

2024-05-25 20:57 UTC, gojakuch commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    while (CastExpr* condCast = dyn_cast<CastExpr>(cond))
yes, thank you, I didn't know this exists

2024-05-25 20:58 UTC, gojakuch commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    // FIXME: here DifferentiateVarDecl is only used to clone the declaration
I have found another way, I'll push it soon.

2024-05-26 12:16 UTC, gojakuch commented
> It seems that currently for-loop condition is only differentiated if it's a binary operator. This additional check seems unnecessary and is incorrect. You should try to directly call Visit(...) function on the condition expression.

As for this, I enabled support for unary operators, added support for visiting the logical not in general. I also allowed comparison operators, which are probably the most common type of expression in for-loop conditions, and made the binary operator visitor work with them. I understand that it is a bit ugly to artificially limit the differentiation of cond, however, Clad doesn't support many other operators and if we simply visit anything that is inside cond, some tests start to crash because of complicated reasons related to trying to visit an unsupported statement (that is my guess, I spent some time trying to understand what's going on but I didn't understand much). I don't think we should add general support for other operators in this PR, so I added a fixme message to add support for other expressions in cond. this PR already covers a lot of things that were not possible or were differentiated incorrectly before, so I think visiting only these supported statements could be a common ground and a solution so far.

speaking of crashing checks, as you can see, there are some checks failing for OSX now, specifically the ForwardMode/UserDefinedTypes.C test. which is exactly what started crashing on my machine after I had tried to visit every for-loop condition regardless of its type. these errors here are different though and I don't get them on my machine with the current PR code. I'm not even sure how they are related to for loops. I would appreciate if someone more experienced took a look at these at least, maybe I could make visiting all the conds work with similar fixes then.

2024-05-26 13:39 UTC, parth-07 commented
@gojakuch You are right. We are enabling a lot of different things in this pull request. It is my bad. I thought some features (binary operator, unary operator) were supported before, but they were not. Can we please limit the scope of this pull request? Let's handle the unary operator and general support for visiting conditions in a separate pull request. 

Can you please revert the latest changes and bring the pull request to the point when you enabled binary operator support and add FIXME in the code regarding general support is missing?

2024-05-26 16:20 UTC, vgvassilev commented
In addition can you open issues for all things that this pull request discovered are not supported?

2024-05-26 18:24 UTC, gojakuch commented
> Can you please revert the latest changes and bring the pull request to the point when you enabled binary operator support and add FIXME in the code regarding general support is missing?

done in the last force-push

2024-05-26 18:45 UTC, parth-07 requested changes

2024-05-26 18:45 UTC, parth-07 commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +  // llvm::errs() << "\n\n\n\n\nretdx: \n";
Please remove the debugging statements.

2024-05-26 19:10 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +        nullptr, condVarClone->isDirectInit(), nullptr,
```suggestion
        /*Init=*/nullptr, condVarClone->isDirectInit(), nullptr,
```
We comment in the the arguments which are unclear what parameters refer to.

2024-05-26 19:10 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +        BuildOp(BO_Assign, BuildDeclRef(condVarClone), condVarClone->getInit());
I'd move the DeclRefExpr from `BuildDeclRef(condVarClone)` into a separate variable. I thin we need to clone the initializer expression of `condVarClone` if we want to use it separately. However, in this situation it is fine because on the next line we remove it. The code needs to become more clear about that. Maybe something like:

CondInit = condVarClone->getInit();
condVarClone->setInit(nullptr);
...

2024-05-26 19:10 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    cond = cond->IgnoreParenImpCasts();
Shouldn't we strip the implict casts of the init expression when forming it in the previous section?

2024-05-26 19:10 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +                 : condDiff.getExpr();
That's unreadable. We should probably expand the ternary if.

2024-05-26 19:10 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    bodyResult = bodyResultCmpd;
Can't we use `unwrapIfSingleStmt`?

2024-05-26 19:10 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      new (m_Context) ForStmt(m_Context, initDiff.getStmt(), cond, nullptr,
```suggestion
      new (m_Context) ForStmt(m_Context, initDiff.getStmt(), cond, /*condVar=*/nullptr,
```

2024-05-26 19:10 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +                         : Ldiff.getExpr()));
That is unreadable.

2024-05-26 19:10 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +                         : Rdiff.getExpr()));
Likewise. You probably can create some lambda function to avoid duplicating this code in a few places...

2024-05-27 06:22 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    // normal condition (see below).
Probably better to give an example with code, too.

2024-05-27 08:33 UTC, gojakuch commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    cond = cond->IgnoreParenImpCasts();
not always, because if there is no declaration in this for this section will just serve the purpose of differentiating the actual cond from the source code, not the one generated above. in this case it won't be unwrapped and could contain impcasts.

2024-05-27 08:34 UTC, gojakuch commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +                 : condDiff.getExpr();
I agree

2024-05-27 08:38 UTC, gojakuch commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    bodyResult = bodyResultCmpd;
I think I tried but I don't remember why I didn't put it in the PR. maybe I just accidentally reverted it together with something that didn't work out well. in any case, as far as I remember this part of code was already there, I just removed an unnecessary if condition it was wrapped into. I'll try `unwrapIfSingleStmt` again rn.

2024-05-27 08:59 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    bodyResult = bodyResultCmpd;
Let's move it in a common place and use it.

2024-05-27 15:50 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      else
No else after a return statement.

2024-05-27 15:51 UTC, vgvassilev commented on include/clad/Differentiator/CladUtils.h
> +    clang::Stmt* unwrapIfSingleStmt(clang::Stmt* S);
That operation should be in a separate commit.

2024-05-27 19:35 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      return BuildParens(Xdiff.getExpr());
We should figure out how to test this branch.

2024-05-27 20:13 UTC, gojakuch commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      return BuildParens(Xdiff.getExpr());
what do you mean, like add unit tests for this? this code is executed in the already existing tests if that's what you mean

2024-05-27 20:20 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +      return BuildParens(Xdiff.getExpr());
Codecov claims this code path is not tested. If that’s true (which is almost always the case) we should add a test.

2024-05-29 10:55 UTC, gojakuch commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    cond = cond->IgnoreParenImpCasts();
sorry, I didn't understand your question, but this line `cond = cond->IgnoreParenImpCasts();` is needed (at least for now). this way we can check if the cond expression is supported or not, specifically, if there's an assignment operator like this:
```C++
double res;
for(;(r = x);){}
```
this cond is wrapped in implicit casts to bool and parentheses. once we can safely call `Visit(cond)` regardless of its type (that is, once there's support for almost most expressions as for-loop conditions), this line can be removed. but since now we need to check if that is an assignment operator, this is needed.

2024-05-29 13:12 UTC, parth-07 commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +                     nullptr, condVarDecl->getInitStyle());
We are repeating the code of `DifferentiateVarDecl` here just because we have to take the init as `null`. Can you reuse `DifferentiateVarDecl` here by adding an extra argument such as `ignoreInit` to `DifferentiateVarDecl` function?

2024-05-29 18:53 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +    cond = cond->IgnoreParenImpCasts();
The way that it is written assumes that the line `Expr* cond = condDiff.getExpr();` may have implicit casts. Is that the case? If it is not my proposal was to move `cond->IgnoreParenImpCasts()` operation in the prior if-stmt.

2024-05-30 15:11 UTC, gojakuch commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +                     nullptr, condVarDecl->getInitStyle());
that seems reasonable. I've implemented this. the thing is though, I needed to create a separate 2-argument method that is called from the 1-argument overload because some other classes specifically override the old single-argument method and this would be messed up by adding an optional second argument.

2024-06-02 15:59 UTC, vgvassilev approved these changes
LGTM! Let's wait for @parth-07's review.

2024-06-02 19:22 UTC, parth-07 approved these changes
Looks good.

2024-06-02 19:32 UTC, vgvassilev commented
@gojakuch, can you fix the compilation error we got here?

2024-06-03 19:29 UTC, merged