Add support for `[[clad::non_differentiable]]` in reverse mode
vgvassilev/clad pull request #916
Opened 2024-05-31 10:47 UTC by MihailMihov

fixes #717 

I've added the code for handing `[[clad::non_differentiable]]` that is already present in the forward mode visitor to the one for reverse mode. I also modified the tests from forward mode, but `ReverseMode/NonDifferentiable.C` is currently failing because of an issue with differentiating operator overloads in reverse mode.

2024-06-01 09:57 UTC, parth-07 commented
> but ReverseMode/NonDifferentiable.C is currently failing because of an issue with differentiating operator overloads in reverse mode.

If we mark that operator overload as non-differentiable, then should the issue still happen?

2024-06-01 10:15 UTC, MihailMihov commented
> If we mark that operator overload as non-differentiable, then should the issue still happen?

I just tried changing the test and it still errors, but this time it is `too many arguments to function call, expected 1, have 2`, while if it tries to differentiate the operator it is `too few arguments to function call, expected 4, have 3`. I did open an issue for this and it is #917, where I put a more minimal failing test. I can try and look into the case where it fails when non-differentiable, but if I had to guess they are the same issue and fixing one would fix both cases.

2024-06-02 07:10 UTC, parth-07 commented
> but if I had to guess they are the same issue and fixing one would fix both cases.

Oh, yes, you are right. Thank you for the details.

2024-07-06 15:34 UTC, vgvassilev commented
@MihailMihov, can you rebase this pull request?

2024-07-06 15:54 UTC, vgvassilev reviewed
Can you take care of the clang-tidy suggestions and adapt the new test in such a way that we work around the pre-existing issue of #917?

2024-07-16 15:04 UTC, vaithak commented on test/Gradient/NonDifferentiable.C
> +  non_differentiable double y;
Let's also test with some pointer member types.

2024-07-16 15:09 UTC, vaithak commented on lib/Differentiator/ReverseModeVisitor.cpp
> +                                                   m_Context, /*val=*/0);
I also saw that this is 'DoubleTy` in forward mode. Can you also test that too and fix that in a separate PR, if possible?

2024-07-17 09:57 UTC, MihailMihov commented on test/Gradient/NonDifferentiable.C
> +  non_differentiable double y;
I just added an `fn_s1_field_pointer` to the test, is that what you wanted me to test?

2024-07-17 09:59 UTC, MihailMihov commented on lib/Differentiator/ReverseModeVisitor.cpp
> +                                                   m_Context, /*val=*/0);
I did change the `DoubleTy` to an `IntTy`, but that didn't actually do anything to the tests and pointers didn't work either way. I added another check for them when visiting `UO_Deref`, not sure if there isn't a better way to fix them however, but now the new test is passing.

2024-07-17 20:27 UTC, parth-07 requested changes

2024-07-17 20:27 UTC, parth-07 commented on test/Gradient/NonDifferentiable.C
> +extern "C" int printf(const char* fmt, ...);
Do we need this declaration?

2024-07-17 20:27 UTC, parth-07 commented on test/Gradient/NonDifferentiableError.C
> +  TEST_FUNC(fn_s2_mem_fn, 3, 5);  // expected-error {{attempted differentiation of function 'fn_s2_mem_fn', which is marked as non-differentiable}}
What happens if we provide a custom derivative for a function marked as non-differentiable?

2024-07-17 20:27 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        ClonedArgs.push_back(Clone(CE->getArg(i)));
Simply cloning the argument seems incorrect. What if the arguments have side-effect which can affect the derivative computation?

2024-07-17 20:27 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +                                      validLoc, ClonedArgs, validLoc)
Does the actual value of location matter here? If not, then I prefer to use `clad::utils::GetValidSLoc`. `clad::utils::GetValidSLoc` makes it clear that the actual value of the source location is not relevant.

2024-07-17 20:27 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (auto* ME = dyn_cast<MemberExpr>(diff.getExpr()))
Can it be handled more uniformly in `VisitMemberExpr`?

2024-07-17 20:27 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (auto* ME = dyn_cast<MemberExpr>(diff.getExpr()))
If `diff.getExpr_dx()` is `0`, then we would need to add a special condition here.

2024-07-17 20:27 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    auto* zero = ConstantFolder::synthesizeLiteral(m_Context.IntTy, m_Context,
I think it is better to create `zero` inside the if-condition as it is only used there.

2024-07-17 20:27 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (isLambda ||
Can you please add a test for a local variable declaration with non_differentiable attribute?

2024-07-18 08:16 UTC, MihailMihov commented on test/Gradient/NonDifferentiable.C
> +extern "C" int printf(const char* fmt, ...);
I don't actually know what it's purpose is, but it was is ForwardMode/NonDifferentiable.C, which I copied to make this test. But it's also in 28 other tests. If removed, the test still passes on my machine.

2024-07-18 08:44 UTC, MihailMihov commented on test/Gradient/NonDifferentiableError.C
> +  TEST_FUNC(fn_s2_mem_fn, 3, 5);  // expected-error {{attempted differentiation of function 'fn_s2_mem_fn', which is marked as non-differentiable}}
It still fails with the error that it's non-differentiable. I think that's better than ignoring the attribute and using the derivative, but what do you expect?

2024-07-18 09:00 UTC, MihailMihov commented on lib/Differentiator/ReverseModeVisitor.cpp
> +                                      validLoc, ClonedArgs, validLoc)
The value is probably only for diagnostics, but I agree that `GetValidSLoc` would be better, so I have changed it. By the way all of this code is taken from the forward mode and mostly kept as is, so after this is merged should I open a PR for the same things but in forward mode?

2024-07-18 09:58 UTC, MihailMihov commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (auto* ME = dyn_cast<MemberExpr>(diff.getExpr()))
> Can it be handled more uniformly in `VisitMemberExpr`?

It is already handled in `VisitMemberExpr` where we return `{clonedME, zero}`, but what happened without the above check is that it tries to build something along the lines of `*0 += ...`, when visiting the `UO_Deref`.

> If `diff.getExpr_dx()` is `0`, then we would need to add a special condition here.

With the above check I eliminate one of the cases where we could end up with a 0 above, if you can think of anything else, then we should handle those too. Do you have anything in mind?

2024-07-18 10:00 UTC, MihailMihov commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    auto* zero = ConstantFolder::synthesizeLiteral(m_Context.IntTy, m_Context,
I have changed that, also what do you think about this being `IntTy` or `DoubleTy`. In the forward mode code it was `DoubleTy`, but Vaibhav suggested changing it to `IntTy`. It didn't seem to make any difference, but maybe somewhere it will?

2024-07-18 10:11 UTC, MihailMihov commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (isLambda ||
I just added `fn_non_diff_var` to Gradient/NonDifferentiable.C test, but I believe it's not working as expected. The correct output would be 0.00 0.00 right? I'll try to get that fixed now.

2024-07-18 10:14 UTC, MihailMihov commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        ClonedArgs.push_back(Clone(CE->getArg(i)));
I'm not sure that I understand the issue here. It the arguments do have side effects then those would be kept when we clone them, is that not what is expected? When do you think that this wouldn't work correctly?

2024-07-18 14:17 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +        ClonedArgs.push_back(Clone(CE->getArg(i)));
Consider an example such as this:

```cpp
some_non_differentiable_fn_call(r = u * v, s = u + v); 
```

Now, if we simply clone the arguments then we will not generate adjoint statements for `r = u * v` and `s = u + v`. 

You don't necessarily need to fix this issue in this PR.

2024-07-18 14:17 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +                                      validLoc, ClonedArgs, validLoc)
> so after this is merged should I open a PR for the same things but in forward mode?

Yes, please do that.

2024-07-18 14:19 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (isLambda ||
Can you please create an issue for this and resolve it in a follow-up pull-request?

2024-07-18 14:25 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      if (auto* ME = dyn_cast<MemberExpr>(diff.getExpr()))
> if you can think of anything else, then we should handle those too.

I am concerned there might be many such cases... For example, `->` operator. 

It might be better to test if the `diff.getExpr_dx()` is a constant (or `0`) instead of testing if the member has a non-differentiable attribute. This is because it will help us cover more cases. For example, the adjoint of member expressions of global class objects should also be `0` and consequently they should be handled similarly but they do not have `non_differentiable` attribute.

2024-07-20 15:45 UTC, parth-07 commented on test/Gradient/NonDifferentiableError.C
> +  TEST_FUNC(fn_s2_mem_fn, 3, 5);  // expected-error {{attempted differentiation of function 'fn_s2_mem_fn', which is marked as non-differentiable}}
I agree. It is better than ignoring the attribute. The current behavior seems good then.

2024-07-20 16:00 UTC, parth-07 approved these changes
Looks good as an initial support for `[[non_differentiable]]`. Thank you for working on this.

Can you please open issues for the comments which need some future work:

- Differentiating argument expressions of non differentiable function calls. This is required because argument expressions can have side-affects.
- Supporting non differentiate attribute on local variables.
- Improve handling of non_differentiable variables in expressions such as `*` (dereference operator), `->` and so on.

2024-07-20 16:02 UTC, vgvassilev commented
Can you squash the tests into the other commit?

2024-07-20 22:13 UTC, MihailMihov commented
> Can you please open issues for the comments which need some future work:
> 
>     * Differentiating argument expressions of non differentiable function calls. This is required because argument expressions can have side-affects.
> 
>     * Supporting non differentiate attribute on local variables.
> 
>     * Improve handling of non_differentiable variables in expressions such as `*` (dereference operator), `->` and so on.

I opened issues for 1 and 3. For 2 this PR includes a basic test and fix, but more work may be necessary. Do I just create an issue saying that there might be a cleaner fix or something more specific?

2024-07-21 18:31 UTC, vgvassilev commented
> > Can you please open issues for the comments which need some future work:
> > ```
> > * Differentiating argument expressions of non differentiable function calls. This is required because argument expressions can have side-affects.
> > 
> > * Supporting non differentiate attribute on local variables.
> > 
> > * Improve handling of non_differentiable variables in expressions such as `*` (dereference operator), `->` and so on.
> > ```
> 
> I opened issues for 1 and 3. For 2 this PR includes a basic test and fix, but more work may be necessary. Do I just create an issue saying that there might be a cleaner fix or something more specific?

Yes, we should create an issue describing what this "more work may be necessary" means in technical and practical terms.

2024-07-21 19:44 UTC, merged