Bin Logical And Support
vgvassilev/clad pull request #923
Opened 2024-06-06 18:13 UTC by rohanjulka19

2024-06-11 12:24 UTC, parth-07 requested changes

2024-06-11 12:24 UTC, parth-07 commented on test/Gradient/FunctionCalls.C
> +// CHECK-NEXT:     _cond1 = c == 'a' && s[0] == 'a';
We ideally should not repeat the `c == 'a'` expression here. Here it is fine because the expression does not have any side-effect but I am concerned that it may lead to an incorrect derivative if the expression has a side-effect. Can we have something like this?

```
_cond1 = _cond0 && s[0] == 'a'
```

2024-06-11 12:24 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +          clad_compat::IfStmt_Create(m_Context, noLoc, false, nullptr, nullptr,
Please add parameter names here as, `/*parameterName=*/value`

2024-06-11 12:25 UTC, parth-07 commented
Please also improve the commit message. This guide might be helpful for improving the commit message: https://cbea.ms/git-commit/

2024-06-15 18:37 UTC, vgvassilev commented
@rohanjulka19, ping. Maybe you can take a look at https://github.com/vgvassilev/clad/blob/master/CONTRIBUTING.md#creating-a-successfull-pull-request address @parth-07's comment.

2024-06-15 19:01 UTC, rohanjulka19 commented
> https://github.com/vgvassilev/clad/blob/master/CONTRIBUTING.md#creating-a-successfull-pull-request

oh I had already addressed them, follwing the guidelines mentioned in the provided link - https://cbea.ms/git-commit/

Regarding this - https://github.com/vgvassilev/clad/blob/master/CONTRIBUTING.md#creating-a-successfull-pull-request

1. Currently there is no issue created for this I can link this with Incorrect differentiation of loop conditions in reverse mode #746  issue as this PR was opened as part of solution for this. 

2. I haven't added tests I was hoping if parth is ok with the changes then I will add the tests otherwise it gets tedious to fix them again and again. 

From next time will re-request review. I usually don't do that to prevent annoying the reviewer.

2024-06-15 19:06 UTC, vgvassilev commented
> 2\. I haven't added tests I was hoping if parth is ok with the changes then I will add the tests otherwise it gets tedious to fix them again and again.

That sounds backwards. We require tests as they help reviewers understand the overall intent of the change.

2024-06-15 19:09 UTC, rohanjulka19 commented
> > 2. I haven't added tests I was hoping if parth is ok with the changes then I will add the tests otherwise it gets tedious to fix them again and again.
> 
> That sounds backwards. We require tests as they help reviewers understand the overall intent of the change.

Yeah I guess ok will add tests to this

2024-06-17 15:27 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +                    nullptr,
```suggestion
                    /*forwSweepDiff=*/nullptr,
```

2024-06-17 15:27 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      return BinOpClone;
Can we figure out how to test this branch?

2024-06-17 15:58 UTC, rohanjulka19 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      return BinOpClone;
ok this branch will actually never be called becasue we will always receive a expression. So I will remove this ??

2024-06-17 16:25 UTC, rohanjulka19 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      return BinOpClone;
the variable which stored the condition expression. If expression is not requied to be stored then it just returns the actual condition expression, in that case it becomes equivalent to the below line only
```
 return BinOpClone;
```

2024-06-17 16:36 UTC, vgvassilev commented on lib/Differentiator/ReverseModeVisitor.cpp
> +      return BinOpClone;
Ok, if you know how to remove it please do, otherwise we need to figure out how to write a test to go via that line...

2024-06-17 16:54 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (thenDiff.getStmt()) {
Is this `if (thenDiff.getStmt)` condition required for supporting `&&` operator?

2024-06-17 17:12 UTC, rohanjulka19 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (thenDiff.getStmt()) {
this is not needed for supporting && operator. Actually while testing && support In cases where the then stmt of the if condition was empty it would throw error.

```
if (true) {} 
```
I mean this happend by mistake as the code was wrong at the time so I don't think this case will arise for && support but I anyway added this to handle empty if stmts.

2024-06-17 17:17 UTC, parth-07 commented on lib/Differentiator/ReverseModeVisitor.cpp
> +    if (thenDiff.getStmt()) {
Ah, that's a nice catch! I am glad this mistake happened :).  Can you please resolve this as a separate pull request since this is a different issue altogether?

2024-06-17 17:23 UTC, rohanjulka19 commented on test/Gradient/Gradients.C
> +// CHECK-NEXT:             _cond1 = _cond0 && (res += 3 * i * j);
ok completely missed this.

2024-06-20 12:27 UTC, vgvassilev commented
Can you properly rebase this PR?

2024-06-22 11:07 UTC, parth-07 approved these changes
Looks good.

2024-06-22 19:04 UTC, merged