Prevent Clad from trying to create a void zero literal
vgvassilev/clad pull request #989
Opened 2024-07-18 11:34 UTC by gojakuch

Previously, clad used to try to create a void zero literal when differentiating a call to a void function with literal arguments in the forward mode. This caused it to crash.

Fixes: #988

2024-07-18 11:40 UTC, gojakuch commented
@vgvassilev this should prevent #977 from failing the kokkos check

2024-07-18 12:04 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +        if (!CE->getType().getTypePtr()->isVoidType()) {
```suggestion
        if (!CE->getType()->isVoidType()) {
```

2024-07-18 13:33 UTC, vgvassilev commented on lib/Differentiator/BaseForwardModeVisitor.cpp
> +        if (!CE->getType().getTypePtr()->isVoidType()) {
On a second thought can we use `VisitorBase::getZeroInit` and teach it to return `nullptr` if we ask to get the zero init of a void type?

2024-07-19 13:28 UTC, gojakuch commented
@vgvassilev one check still fails to set up the Ubuntu apt sources

2024-07-19 14:42 UTC, vgvassilev commented on test/FirstDerivative/CallArguments.C
> -// CHECK-NEXT: return _d_x * _t0 + x * 0.F;
We will need to check if it is a double of float type to retain that type in the literal too. We have to update VisitorBase::getZeroInit with the relevant code that takes into account if the type is a float or a double.

2024-07-20 15:20 UTC, gojakuch commented on test/FirstDerivative/CallArguments.C
> -// CHECK-NEXT: return _d_x * _t0 + x * 0.F;
`VisitorBase::getZeroInit` currently only synthesises integer 0 if it's a scalar numerical type and it actually converts it to the correct type implicitly. if I edit this, I'll need to change almost every 0 entry in 37 different tests manually and I don't think it's worth the time, as I don't see what it brings. like, it only generates integer zeroes for the types for which it's safe to do this.

2024-07-20 15:35 UTC, vgvassilev commented on test/FirstDerivative/CallArguments.C
> -// CHECK-NEXT: return _d_x * _t0 + x * 0.F;
It’s worth changing because sometimes the produced code cannot compile.

2024-07-20 15:38 UTC, parth-07 requested changes

2024-07-20 15:38 UTC, parth-07 commented on test/FirstDerivative/FunctionCalls.C
> +    assert(y < 1);
The value of `y` is `1` in the `test_10` function call. The `assert` call can fail.

2024-07-20 17:06 UTC, gojakuch commented on test/FirstDerivative/CallArguments.C
> -// CHECK-NEXT: return _d_x * _t0 + x * 0.F;
I cannot think of a situation where a float or double value couldn't be created from `0`. but even if that's my mistake, I'd suggest opening this as another issue if this is worth fixing, because this is not something I've changed, it's been like that before. changing all the tests for this to work out would require some automation, because it takes an unreasonable amount of time if done manually, I think this PR needs to be merged faster than that. I've already spent half an hour on a single file file out of 37 and I'm not even half way through this file. some of the test files are short, but I'd rather have this as a separate PR and then I would automate these changes. again, this PR did not make this change, it's how Clad works on master in most cases, this PR only affects the special cases of when a zero comes from a 'constant function call'.

2024-07-20 17:40 UTC, vgvassilev commented on test/FirstDerivative/CallArguments.C
> -// CHECK-NEXT: return _d_x * _t0 + x * 0.F;
One can claim that `0.f` was correct and that PR regressed it. We can argue about that at length but I guess that something you will need to get used to when developing functionality in the core of clad.

If you say that we should merge that with a regression that's fine but then immediately after that you will have to work on the regression which does not save you a lot, right?

2024-07-20 17:51 UTC, gojakuch commented on test/FirstDerivative/CallArguments.C
> -// CHECK-NEXT: return _d_x * _t0 + x * 0.F;
well, in that case, I can stick to the less elegant issue of having this being called for void function calls only, not changing the behaviour for other cases for now, but I can add a comment there.

2024-07-20 18:07 UTC, vgvassilev commented on test/FirstDerivative/CallArguments.C
> -// CHECK-NEXT: return _d_x * _t0 + x * 0.F;
I guess we can move forward with your approach as long as you open an issue and describe what needs to be done there.

2024-07-20 18:24 UTC, gojakuch commented on test/FirstDerivative/CallArguments.C
> -// CHECK-NEXT: return _d_x * _t0 + x * 0.F;
alright, I'll open an issue then

2024-07-21 18:25 UTC, parth-07 approved these changes
Looks good.

2024-07-21 18:46 UTC, merged